"""Seed formulas data

Revision ID: 002_seed_formulas
Revises: 001_initial_schema
Create Date: 2026-02-26

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "002_seed_formulas"
down_revision: Union[str, None] = "001_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    formulas_table = sa.table(
        "formulas",
        sa.column("id", sa.BigInteger),
        sa.column("subject", sa.String),
        sa.column("category", sa.String),
        sa.column("name", sa.String),
        sa.column("latex", sa.Text),
        sa.column("description", sa.Text),
        sa.column("grade_levels", postgresql.ARRAY(sa.String)),
        sa.column("keywords", postgresql.ARRAY(sa.String)),
        sa.column("related_ids", postgresql.ARRAY(sa.BigInteger)),
    )

    op.bulk_insert(
        formulas_table,
        [
            # ==================== MATH (id 1-12) ====================
            {
                "id": 1,
                "subject": "math",
                "category": "Algebra",
                "name": "Quadratic Formula",
                "latex": r"x = \frac{-b \pm \sqrt{b^2-4ac}}{2a}",
                "description": "Finds the solutions (roots) of a quadratic equation ax^2 + bx + c = 0. The discriminant b^2-4ac determines the nature of the roots.",
                "grade_levels": ["grade-8", "grade-9", "grade-10"],
                "keywords": ["quadratic", "roots", "equation", "discriminant", "parabola"],
                "related_ids": [8, 4],
            },
            {
                "id": 2,
                "subject": "math",
                "category": "Geometry",
                "name": "Pythagorean Theorem",
                "latex": r"a^2 + b^2 = c^2",
                "description": "In a right triangle, the square of the hypotenuse (c) equals the sum of the squares of the other two sides (a and b).",
                "grade_levels": ["grade-7", "grade-8", "grade-9"],
                "keywords": ["pythagorean", "triangle", "right triangle", "hypotenuse", "sides"],
                "related_ids": [4, 12],
            },
            {
                "id": 3,
                "subject": "math",
                "category": "Algebra",
                "name": "Slope Formula",
                "latex": r"m = \frac{y_2 - y_1}{x_2 - x_1}",
                "description": "Calculates the slope (rate of change) of a line passing through two points (x1, y1) and (x2, y2).",
                "grade_levels": ["grade-7", "grade-8", "grade-9"],
                "keywords": ["slope", "line", "gradient", "rate of change", "linear"],
                "related_ids": [8, 4],
            },
            {
                "id": 4,
                "subject": "math",
                "category": "Geometry",
                "name": "Distance Formula",
                "latex": r"d = \sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}",
                "description": "Calculates the distance between two points (x1, y1) and (x2, y2) in a coordinate plane. Derived from the Pythagorean Theorem.",
                "grade_levels": ["grade-8", "grade-9", "grade-10"],
                "keywords": ["distance", "points", "coordinate", "length", "pythagorean"],
                "related_ids": [2, 3],
            },
            {
                "id": 5,
                "subject": "math",
                "category": "Geometry",
                "name": "Area of Circle",
                "latex": r"A = \pi r^2",
                "description": "Calculates the area enclosed by a circle with radius r.",
                "grade_levels": ["grade-6", "grade-7", "grade-8"],
                "keywords": ["area", "circle", "radius", "pi"],
                "related_ids": [6],
            },
            {
                "id": 6,
                "subject": "math",
                "category": "Geometry",
                "name": "Circumference",
                "latex": r"C = 2\pi r",
                "description": "Calculates the circumference (perimeter) of a circle with radius r.",
                "grade_levels": ["grade-6", "grade-7", "grade-8"],
                "keywords": ["circumference", "circle", "perimeter", "radius", "pi"],
                "related_ids": [5],
            },
            {
                "id": 7,
                "subject": "math",
                "category": "Geometry",
                "name": "Area of Triangle",
                "latex": r"A = \frac{1}{2}bh",
                "description": "Calculates the area of a triangle given its base (b) and height (h).",
                "grade_levels": ["grade-5", "grade-6", "grade-7"],
                "keywords": ["area", "triangle", "base", "height"],
                "related_ids": [2, 5],
            },
            {
                "id": 8,
                "subject": "math",
                "category": "Algebra",
                "name": "Linear Equation",
                "latex": r"y = mx + b",
                "description": "Slope-intercept form of a linear equation where m is the slope and b is the y-intercept.",
                "grade_levels": ["grade-7", "grade-8", "grade-9"],
                "keywords": ["linear", "slope", "intercept", "line", "equation"],
                "related_ids": [3, 1],
            },
            {
                "id": 9,
                "subject": "math",
                "category": "Algebra",
                "name": "Binomial Theorem",
                "latex": r"(a+b)^n = \sum_{k=0}^{n}\binom{n}{k}a^{n-k}b^k",
                "description": "Expands the power of a binomial (a+b) raised to any positive integer n using combinations.",
                "grade_levels": ["grade-10", "grade-11", "grade-12"],
                "keywords": ["binomial", "expansion", "combination", "power", "polynomial"],
                "related_ids": [1, 10],
            },
            {
                "id": 10,
                "subject": "math",
                "category": "Algebra",
                "name": "Logarithm Product Rule",
                "latex": r"\log_a(xy) = \log_a x + \log_a y",
                "description": "The logarithm of a product equals the sum of the logarithms. One of the fundamental logarithm properties.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["logarithm", "log", "product", "exponent", "property"],
                "related_ids": [9, 1],
            },
            {
                "id": 11,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Sine Rule",
                "latex": r"\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}",
                "description": "Relates the sides of a triangle to the sines of its opposite angles. Used to solve non-right triangles.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["sine", "triangle", "angle", "trigonometry", "law of sines"],
                "related_ids": [12, 2],
            },
            {
                "id": 12,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Cosine Rule",
                "latex": r"c^2 = a^2 + b^2 - 2ab\cos C",
                "description": "Generalizes the Pythagorean theorem to any triangle. Relates sides and one angle of a triangle.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["cosine", "triangle", "angle", "trigonometry", "law of cosines"],
                "related_ids": [11, 2],
            },
            # ==================== PHYSICS (id 13-22) ====================
            {
                "id": 13,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Newton's Second Law",
                "latex": r"F = ma",
                "description": "The net force on an object equals its mass times its acceleration. Fundamental law of classical mechanics.",
                "grade_levels": ["grade-8", "grade-9", "grade-10"],
                "keywords": ["force", "mass", "acceleration", "newton", "mechanics"],
                "related_ids": [19, 17],
            },
            {
                "id": 14,
                "subject": "physics",
                "category": "Energy",
                "name": "Kinetic Energy",
                "latex": r"E_k = \frac{1}{2}mv^2",
                "description": "The energy an object possesses due to its motion, depending on mass (m) and velocity (v).",
                "grade_levels": ["grade-8", "grade-9", "grade-10"],
                "keywords": ["kinetic", "energy", "velocity", "mass", "motion"],
                "related_ids": [15, 19],
            },
            {
                "id": 15,
                "subject": "physics",
                "category": "Energy",
                "name": "Potential Energy",
                "latex": r"E_p = mgh",
                "description": "The energy an object has due to its position in a gravitational field, where g is gravitational acceleration and h is height.",
                "grade_levels": ["grade-8", "grade-9", "grade-10"],
                "keywords": ["potential", "energy", "gravity", "height", "mass"],
                "related_ids": [14, 22],
            },
            {
                "id": 16,
                "subject": "physics",
                "category": "Electricity",
                "name": "Ohm's Law",
                "latex": r"V = IR",
                "description": "The voltage across a conductor is proportional to the current through it, with resistance as the proportionality constant.",
                "grade_levels": ["grade-8", "grade-9", "grade-10"],
                "keywords": ["voltage", "current", "resistance", "ohm", "circuit"],
                "related_ids": [20],
            },
            {
                "id": 17,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Speed",
                "latex": r"v = \frac{d}{t}",
                "description": "Speed equals distance traveled divided by the time taken. The most basic kinematic equation.",
                "grade_levels": ["grade-6", "grade-7", "grade-8"],
                "keywords": ["speed", "velocity", "distance", "time", "motion"],
                "related_ids": [18, 13],
            },
            {
                "id": 18,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Acceleration",
                "latex": r"a = \frac{\Delta v}{\Delta t}",
                "description": "Acceleration is the rate of change of velocity over time.",
                "grade_levels": ["grade-8", "grade-9", "grade-10"],
                "keywords": ["acceleration", "velocity", "time", "rate of change", "kinematics"],
                "related_ids": [13, 17],
            },
            {
                "id": 19,
                "subject": "physics",
                "category": "Energy",
                "name": "Work",
                "latex": r"W = Fd\cos\theta",
                "description": "Work done by a force equals the force magnitude times displacement times cosine of the angle between them.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["work", "force", "displacement", "energy", "angle"],
                "related_ids": [13, 20],
            },
            {
                "id": 20,
                "subject": "physics",
                "category": "Energy",
                "name": "Power",
                "latex": r"P = \frac{W}{t}",
                "description": "Power is the rate at which work is done or energy is transferred over time.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["power", "work", "time", "energy", "rate"],
                "related_ids": [19, 16],
            },
            {
                "id": 21,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Momentum",
                "latex": r"p = mv",
                "description": "Momentum is the product of an object's mass and velocity. Conserved in isolated systems.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["momentum", "mass", "velocity", "impulse", "conservation"],
                "related_ids": [13, 14],
            },
            {
                "id": 22,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Gravitational Force",
                "latex": r"F = G\frac{m_1 m_2}{r^2}",
                "description": "Newton's law of universal gravitation. The attractive force between two masses is proportional to their product and inversely proportional to the square of the distance between them.",
                "grade_levels": ["grade-10", "grade-11", "grade-12"],
                "keywords": ["gravity", "gravitational", "force", "mass", "universal", "newton"],
                "related_ids": [13, 15],
            },
            # ==================== CHEMISTRY (id 23-30) ====================
            {
                "id": 23,
                "subject": "chemistry",
                "category": "Gas Laws",
                "name": "Ideal Gas Law",
                "latex": r"PV = nRT",
                "description": "Relates pressure (P), volume (V), amount (n), and temperature (T) of an ideal gas using the gas constant R.",
                "grade_levels": ["grade-10", "grade-11", "grade-12"],
                "keywords": ["gas", "pressure", "volume", "temperature", "ideal", "mole"],
                "related_ids": [27, 24],
            },
            {
                "id": 24,
                "subject": "chemistry",
                "category": "General",
                "name": "Density",
                "latex": r"\rho = \frac{m}{V}",
                "description": "Density is mass per unit volume. A fundamental property used to characterize substances.",
                "grade_levels": ["grade-7", "grade-8", "grade-9"],
                "keywords": ["density", "mass", "volume", "substance", "property"],
                "related_ids": [23, 25],
            },
            {
                "id": 25,
                "subject": "chemistry",
                "category": "Solutions",
                "name": "Molarity",
                "latex": r"M = \frac{n}{V}",
                "description": "Molarity is the number of moles of solute per liter of solution. The most common unit of concentration.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["molarity", "concentration", "moles", "solution", "solute"],
                "related_ids": [27, 24],
            },
            {
                "id": 26,
                "subject": "chemistry",
                "category": "Acids and Bases",
                "name": "pH",
                "latex": r"pH = -\log[H^+]",
                "description": "pH measures the acidity of a solution as the negative logarithm of hydrogen ion concentration.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["pH", "acid", "base", "hydrogen", "concentration", "logarithm"],
                "related_ids": [25, 10],
            },
            {
                "id": 27,
                "subject": "chemistry",
                "category": "Solutions",
                "name": "Dilution",
                "latex": r"M_1V_1 = M_2V_2",
                "description": "The dilution equation relates initial and final concentrations and volumes when diluting a solution.",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["dilution", "concentration", "volume", "solution", "molarity"],
                "related_ids": [25, 23],
            },
            {
                "id": 28,
                "subject": "chemistry",
                "category": "General",
                "name": "Avogadro's Number",
                "latex": r"N = nN_A",
                "description": "Relates the number of particles (N) to moles (n) using Avogadro's number (N_A = 6.022 x 10^23).",
                "grade_levels": ["grade-9", "grade-10", "grade-11"],
                "keywords": ["avogadro", "mole", "particles", "atoms", "molecules", "number"],
                "related_ids": [25, 23],
            },
            {
                "id": 29,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Reaction Rate",
                "latex": r"r = \frac{\Delta[C]}{\Delta t}",
                "description": "The rate of a chemical reaction is the change in concentration of a reactant or product per unit time.",
                "grade_levels": ["grade-10", "grade-11", "grade-12"],
                "keywords": ["rate", "reaction", "concentration", "time", "kinetics"],
                "related_ids": [30, 25],
            },
            {
                "id": 30,
                "subject": "chemistry",
                "category": "Thermochemistry",
                "name": "Enthalpy",
                "latex": r"\Delta H = H_{products} - H_{reactants}",
                "description": "The enthalpy change of a reaction is the difference between the enthalpies of products and reactants. Negative for exothermic, positive for endothermic.",
                "grade_levels": ["grade-10", "grade-11", "grade-12"],
                "keywords": ["enthalpy", "heat", "exothermic", "endothermic", "thermochemistry", "reaction"],
                "related_ids": [29, 23],
            },
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM formulas WHERE id <= 30")
