"""Seed Cambridge curriculum Math formulas

Revision ID: 007_seed_cambridge_math
Revises: 006_add_curriculum_column
Create Date: 2026-03-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "007_seed_cambridge_math"
down_revision: Union[str, None] = "006_add_curriculum_column"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clean up any user-created formulas that would conflict with seed IDs
    op.execute("DELETE FROM formulas WHERE id > 30")
    op.execute("SELECT setval('formulas_id_seq', 440)")

    formulas_table = sa.table(
        "formulas",
        sa.column("id", sa.BigInteger),
        sa.column("subject", sa.String),
        sa.column("category", sa.String),
        sa.column("name", sa.String),
        sa.column("latex", sa.Text),
        sa.column("description", sa.Text),
        sa.column("grade_levels", postgresql.ARRAY(sa.String)),
        sa.column("keywords", postgresql.ARRAY(sa.String)),
        sa.column("related_ids", postgresql.ARRAY(sa.BigInteger)),
        sa.column("curriculum", postgresql.ARRAY(sa.String)),
    )

    op.bulk_insert(
        formulas_table,
        [
            # ================================================================
            # IGCSE Mathematics (0580/0606) — IDs 31-65
            # ================================================================
            # ---------- Algebra ----------
            {
                "id": 31,
                "subject": "math",
                "category": "Algebra",
                "name": "Simultaneous Equations (Linear)",
                "latex": r"a_1 x + b_1 y = c_1 \quad\text{and}\quad a_2 x + b_2 y = c_2",
                "description": "A pair of linear equations in two unknowns solved simultaneously by elimination or substitution to find the values of x and y.",
                "grade_levels": ["igcse"],
                "keywords": ["simultaneous", "equations", "elimination", "substitution", "linear", "two unknowns"],
                "related_ids": [1, 8, 32],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 32,
                "subject": "math",
                "category": "Algebra",
                "name": "Completing the Square",
                "latex": r"ax^2 + bx + c = a\left(x + \frac{b}{2a}\right)^2 - \frac{b^2 - 4ac}{4a}",
                "description": "Rewrites a quadratic expression in vertex form to find the turning point of a parabola or solve quadratic equations.",
                "grade_levels": ["igcse"],
                "keywords": ["completing the square", "quadratic", "vertex", "turning point", "parabola", "algebra"],
                "related_ids": [1, 33, 34],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 33,
                "subject": "math",
                "category": "Algebra",
                "name": "Difference of Two Squares",
                "latex": r"a^2 - b^2 = (a+b)(a-b)",
                "description": "A factoring pattern where the difference of two perfect squares can be written as a product of a sum and a difference.",
                "grade_levels": ["igcse"],
                "keywords": ["difference of squares", "factoring", "factorisation", "algebra", "identity"],
                "related_ids": [1, 32, 34],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 34,
                "subject": "math",
                "category": "Algebra",
                "name": "Perfect Square Trinomial",
                "latex": r"a^2 \pm 2ab + b^2 = (a \pm b)^2",
                "description": "A factoring pattern where a trinomial is the square of a binomial. Useful for completing the square and simplifying expressions.",
                "grade_levels": ["igcse"],
                "keywords": ["perfect square", "trinomial", "factoring", "factorisation", "expansion", "algebra"],
                "related_ids": [32, 33, 1],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 35,
                "subject": "math",
                "category": "Algebra",
                "name": "Linear Inequality",
                "latex": r"ax + b < c \implies x < \frac{c - b}{a} \quad (a > 0)",
                "description": "Solving a linear inequality follows the same steps as a linear equation, but the inequality sign reverses when multiplying or dividing by a negative number.",
                "grade_levels": ["igcse"],
                "keywords": ["inequality", "linear", "solve", "number line", "algebra", "less than"],
                "related_ids": [8, 31, 36],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 36,
                "subject": "math",
                "category": "Algebra",
                "name": "Arithmetic Sequence — nth Term",
                "latex": r"u_n = a + (n-1)d",
                "description": "Gives the nth term of an arithmetic sequence where a is the first term and d is the common difference between consecutive terms.",
                "grade_levels": ["igcse"],
                "keywords": ["arithmetic", "sequence", "nth term", "common difference", "linear sequence", "series"],
                "related_ids": [37, 38, 39],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 37,
                "subject": "math",
                "category": "Algebra",
                "name": "Geometric Sequence — nth Term",
                "latex": r"u_n = ar^{n-1}",
                "description": "Gives the nth term of a geometric sequence where a is the first term and r is the common ratio between consecutive terms.",
                "grade_levels": ["igcse"],
                "keywords": ["geometric", "sequence", "nth term", "common ratio", "exponential", "series"],
                "related_ids": [36, 39, 40],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 38,
                "subject": "math",
                "category": "Algebra",
                "name": "Sum of Arithmetic Series",
                "latex": r"S_n = \frac{n}{2}(2a + (n-1)d) = \frac{n}{2}(a + l)",
                "description": "Calculates the sum of the first n terms of an arithmetic series, where a is the first term, d the common difference, and l the last term.",
                "grade_levels": ["igcse"],
                "keywords": ["arithmetic", "series", "sum", "sigma", "first n terms", "algebra"],
                "related_ids": [36, 39, 78],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 39,
                "subject": "math",
                "category": "Algebra",
                "name": "Sum of Geometric Series",
                "latex": r"S_n = \frac{a(1 - r^n)}{1 - r}, \quad r \neq 1",
                "description": "Calculates the sum of the first n terms of a geometric series where a is the first term and r is the common ratio.",
                "grade_levels": ["igcse"],
                "keywords": ["geometric", "series", "sum", "common ratio", "finite", "algebra"],
                "related_ids": [37, 38, 80],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Functions ----------
            {
                "id": 40,
                "subject": "math",
                "category": "Functions",
                "name": "Composite Function",
                "latex": r"(f \circ g)(x) = f(g(x))",
                "description": "A composite function applies one function to the result of another. First evaluate the inner function g(x), then apply f to that result.",
                "grade_levels": ["igcse"],
                "keywords": ["composite", "function", "composition", "fg", "nested", "mapping"],
                "related_ids": [41, 37],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 41,
                "subject": "math",
                "category": "Functions",
                "name": "Inverse Function",
                "latex": r"f(f^{-1}(x)) = f^{-1}(f(x)) = x",
                "description": "The inverse function reverses the effect of the original function. Found by swapping x and y in y = f(x) and solving for y.",
                "grade_levels": ["igcse"],
                "keywords": ["inverse", "function", "reverse", "one-to-one", "mapping", "reflection"],
                "related_ids": [40, 8],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Coordinate Geometry ----------
            {
                "id": 42,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Midpoint Formula",
                "latex": r"M = \left(\frac{x_1 + x_2}{2},\; \frac{y_1 + y_2}{2}\right)",
                "description": "Finds the midpoint of a line segment connecting two points (x1, y1) and (x2, y2) by averaging their coordinates.",
                "grade_levels": ["igcse"],
                "keywords": ["midpoint", "coordinates", "average", "line segment", "geometry"],
                "related_ids": [3, 4, 43],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 43,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Equation of a Line (Point-Slope Form)",
                "latex": r"y - y_1 = m(x - x_1)",
                "description": "Defines a straight line passing through the point (x1, y1) with gradient m. Useful when given a point and slope.",
                "grade_levels": ["igcse"],
                "keywords": ["point-slope", "equation", "line", "gradient", "coordinate geometry", "straight line"],
                "related_ids": [3, 8, 44],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 44,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Perpendicular Gradient",
                "latex": r"m_1 \times m_2 = -1",
                "description": "Two lines are perpendicular if and only if the product of their gradients is -1. The perpendicular gradient is the negative reciprocal.",
                "grade_levels": ["igcse"],
                "keywords": ["perpendicular", "gradient", "normal", "negative reciprocal", "right angle", "lines"],
                "related_ids": [3, 43, 45],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 45,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Equation of a Circle",
                "latex": r"(x - a)^2 + (y - b)^2 = r^2",
                "description": "The equation of a circle with centre (a, b) and radius r. All points on the circle are at distance r from the centre.",
                "grade_levels": ["igcse"],
                "keywords": ["circle", "equation", "centre", "radius", "coordinate geometry", "locus"],
                "related_ids": [4, 5, 44],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Geometry ----------
            {
                "id": 46,
                "subject": "math",
                "category": "Geometry",
                "name": "Volume of Cylinder",
                "latex": r"V = \pi r^2 h",
                "description": "Calculates the volume of a cylinder with base radius r and height h. Equals the area of the circular base times the height.",
                "grade_levels": ["igcse"],
                "keywords": ["volume", "cylinder", "radius", "height", "3D shape", "prism"],
                "related_ids": [5, 47, 50],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 47,
                "subject": "math",
                "category": "Geometry",
                "name": "Volume of Cone",
                "latex": r"V = \frac{1}{3}\pi r^2 h",
                "description": "Calculates the volume of a cone with base radius r and perpendicular height h. Equals one-third of the cylinder with the same base and height.",
                "grade_levels": ["igcse"],
                "keywords": ["volume", "cone", "radius", "height", "3D shape", "pyramid"],
                "related_ids": [46, 48, 5],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 48,
                "subject": "math",
                "category": "Geometry",
                "name": "Volume of Sphere",
                "latex": r"V = \frac{4}{3}\pi r^3",
                "description": "Calculates the volume of a sphere with radius r. Used in problems involving balls, bubbles, and spherical containers.",
                "grade_levels": ["igcse"],
                "keywords": ["volume", "sphere", "radius", "3D shape", "ball", "globe"],
                "related_ids": [47, 49, 5],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 49,
                "subject": "math",
                "category": "Geometry",
                "name": "Surface Area of Sphere",
                "latex": r"A = 4\pi r^2",
                "description": "Calculates the total surface area of a sphere with radius r. Exactly four times the area of its great circle.",
                "grade_levels": ["igcse"],
                "keywords": ["surface area", "sphere", "radius", "3D shape", "area"],
                "related_ids": [48, 50, 5],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 50,
                "subject": "math",
                "category": "Geometry",
                "name": "Surface Area of Cylinder",
                "latex": r"A = 2\pi r h + 2\pi r^2",
                "description": "The total surface area of a cylinder includes the curved surface area (2*pi*r*h) plus two circular ends (2*pi*r^2).",
                "grade_levels": ["igcse"],
                "keywords": ["surface area", "cylinder", "curved surface", "radius", "height", "3D shape"],
                "related_ids": [46, 49, 6],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 51,
                "subject": "math",
                "category": "Geometry",
                "name": "Arc Length",
                "latex": r"\text{Arc length} = \frac{\theta}{360} \times 2\pi r",
                "description": "Calculates the length of an arc of a circle where theta is the central angle in degrees and r is the radius.",
                "grade_levels": ["igcse"],
                "keywords": ["arc", "length", "circle", "angle", "sector", "circumference"],
                "related_ids": [6, 52, 5],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 52,
                "subject": "math",
                "category": "Geometry",
                "name": "Sector Area",
                "latex": r"\text{Sector area} = \frac{\theta}{360} \times \pi r^2",
                "description": "Calculates the area of a sector of a circle where theta is the central angle in degrees and r is the radius.",
                "grade_levels": ["igcse"],
                "keywords": ["sector", "area", "circle", "angle", "fraction", "pi"],
                "related_ids": [5, 51, 6],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 53,
                "subject": "math",
                "category": "Geometry",
                "name": "Similar Shapes — Area Ratio",
                "latex": r"\frac{A_1}{A_2} = \left(\frac{l_1}{l_2}\right)^2",
                "description": "When two shapes are similar with linear scale factor k, their areas are in the ratio k squared.",
                "grade_levels": ["igcse"],
                "keywords": ["similar", "shapes", "area", "ratio", "scale factor", "enlargement"],
                "related_ids": [54, 7, 46],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 54,
                "subject": "math",
                "category": "Geometry",
                "name": "Similar Shapes — Volume Ratio",
                "latex": r"\frac{V_1}{V_2} = \left(\frac{l_1}{l_2}\right)^3",
                "description": "When two 3D shapes are similar with linear scale factor k, their volumes are in the ratio k cubed.",
                "grade_levels": ["igcse"],
                "keywords": ["similar", "shapes", "volume", "ratio", "scale factor", "enlargement", "3D"],
                "related_ids": [53, 46, 48],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Trigonometry ----------
            {
                "id": 55,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Sine Ratio (SOH)",
                "latex": r"\sin\theta = \frac{\text{opposite}}{\text{hypotenuse}}",
                "description": "In a right-angled triangle, the sine of an angle equals the length of the opposite side divided by the hypotenuse.",
                "grade_levels": ["igcse"],
                "keywords": ["sine", "sin", "SOH CAH TOA", "right triangle", "trigonometry", "opposite", "hypotenuse"],
                "related_ids": [56, 57, 2],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 56,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Cosine Ratio (CAH)",
                "latex": r"\cos\theta = \frac{\text{adjacent}}{\text{hypotenuse}}",
                "description": "In a right-angled triangle, the cosine of an angle equals the length of the adjacent side divided by the hypotenuse.",
                "grade_levels": ["igcse"],
                "keywords": ["cosine", "cos", "SOH CAH TOA", "right triangle", "trigonometry", "adjacent", "hypotenuse"],
                "related_ids": [55, 57, 2],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 57,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Tangent Ratio (TOA)",
                "latex": r"\tan\theta = \frac{\text{opposite}}{\text{adjacent}}",
                "description": "In a right-angled triangle, the tangent of an angle equals the length of the opposite side divided by the adjacent side.",
                "grade_levels": ["igcse"],
                "keywords": ["tangent", "tan", "SOH CAH TOA", "right triangle", "trigonometry", "opposite", "adjacent"],
                "related_ids": [55, 56, 2],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 58,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Area of Triangle Using Sine",
                "latex": r"A = \frac{1}{2}ab\sin C",
                "description": "Calculates the area of any triangle given two sides a and b and the included angle C. Does not require the height.",
                "grade_levels": ["igcse"],
                "keywords": ["area", "triangle", "sine", "included angle", "trigonometry", "non-right"],
                "related_ids": [7, 11, 55],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Vectors ----------
            {
                "id": 59,
                "subject": "math",
                "category": "Vectors",
                "name": "Magnitude of a Vector",
                "latex": r"|\mathbf{v}| = \sqrt{x^2 + y^2}",
                "description": "The magnitude (length) of a two-dimensional vector v = (x, y) is found using the Pythagorean theorem.",
                "grade_levels": ["igcse"],
                "keywords": ["magnitude", "vector", "length", "modulus", "Pythagoras", "distance"],
                "related_ids": [2, 4, 60],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 60,
                "subject": "math",
                "category": "Vectors",
                "name": "Position Vector",
                "latex": r"\overrightarrow{AB} = \mathbf{b} - \mathbf{a}",
                "description": "The displacement vector from point A to point B equals the position vector of B minus the position vector of A.",
                "grade_levels": ["igcse"],
                "keywords": ["position vector", "displacement", "vector", "subtraction", "direction", "geometry"],
                "related_ids": [59, 42, 4],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Statistics ----------
            {
                "id": 61,
                "subject": "math",
                "category": "Statistics",
                "name": "Mean from Frequency Table",
                "latex": r"\bar{x} = \frac{\sum fx}{\sum f}",
                "description": "Calculates the mean of grouped or ungrouped data from a frequency table by dividing the sum of (frequency times value) by the total frequency.",
                "grade_levels": ["igcse"],
                "keywords": ["mean", "average", "frequency", "table", "statistics", "grouped data"],
                "related_ids": [62, 63],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 62,
                "subject": "math",
                "category": "Statistics",
                "name": "Probability (Basic)",
                "latex": r"P(A) = \frac{\text{number of favourable outcomes}}{\text{total number of outcomes}}",
                "description": "The probability of an event A is the ratio of favourable outcomes to total equally likely outcomes. Always between 0 and 1.",
                "grade_levels": ["igcse"],
                "keywords": ["probability", "outcomes", "favourable", "chance", "likelihood", "event"],
                "related_ids": [63, 61],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 63,
                "subject": "math",
                "category": "Statistics",
                "name": "Combined Probability (Independent Events)",
                "latex": r"P(A \cap B) = P(A) \times P(B)",
                "description": "For two independent events, the probability of both occurring equals the product of their individual probabilities.",
                "grade_levels": ["igcse"],
                "keywords": ["probability", "independent", "combined", "multiplication", "and", "events"],
                "related_ids": [62, 87],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Number ----------
            {
                "id": 64,
                "subject": "math",
                "category": "Number",
                "name": "Percentage Change",
                "latex": r"\text{Percentage change} = \frac{\text{new} - \text{original}}{\text{original}} \times 100\%",
                "description": "Calculates the percentage increase or decrease of a value relative to its original amount.",
                "grade_levels": ["igcse"],
                "keywords": ["percentage", "change", "increase", "decrease", "profit", "loss"],
                "related_ids": [65, 8],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 65,
                "subject": "math",
                "category": "Number",
                "name": "Compound Interest",
                "latex": r"A = P\left(1 + \frac{r}{100}\right)^n",
                "description": "Calculates the total amount A after n periods of compound interest, where P is the principal and r is the percentage rate per period.",
                "grade_levels": ["igcse"],
                "keywords": ["compound interest", "principal", "rate", "exponential growth", "finance", "investment"],
                "related_ids": [64, 37],
                "curriculum": ["cambridge-igcse"],
            },
            # ================================================================
            # AS-Level Mathematics (9709 Paper 1/5/6) — IDs 66-100
            # ================================================================
            # ---------- Pure 1 ----------
            {
                "id": 66,
                "subject": "math",
                "category": "Algebra",
                "name": "Discriminant",
                "latex": r"\Delta = b^2 - 4ac",
                "description": "The discriminant determines the nature of roots of ax^2+bx+c=0: two distinct real roots if positive, one repeated root if zero, no real roots if negative.",
                "grade_levels": ["as-level"],
                "keywords": ["discriminant", "quadratic", "roots", "real", "nature", "delta"],
                "related_ids": [1, 32, 67],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 67,
                "subject": "math",
                "category": "Algebra",
                "name": "Factor Theorem",
                "latex": r"\text{If } f(a) = 0, \text{ then } (x - a) \text{ is a factor of } f(x)",
                "description": "States that (x - a) is a factor of a polynomial f(x) if and only if f(a) = 0. Used to factorise polynomials by testing possible roots.",
                "grade_levels": ["as-level"],
                "keywords": ["factor theorem", "polynomial", "root", "factor", "divisibility", "algebra"],
                "related_ids": [68, 66, 1],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 68,
                "subject": "math",
                "category": "Algebra",
                "name": "Remainder Theorem",
                "latex": r"\text{When } f(x) \text{ is divided by } (x - a), \text{ the remainder is } f(a)",
                "description": "States that when a polynomial f(x) is divided by (x - a), the remainder equals f(a). Useful for finding remainders without long division.",
                "grade_levels": ["as-level"],
                "keywords": ["remainder theorem", "polynomial", "division", "remainder", "factor", "algebra"],
                "related_ids": [67, 66, 1],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 69,
                "subject": "math",
                "category": "Algebra",
                "name": "Binomial Expansion Coefficient (nCr)",
                "latex": r"\binom{n}{r} = \frac{n!}{r!(n-r)!}",
                "description": "The binomial coefficient gives the number of ways to choose r items from n. Used as coefficients in the binomial expansion of (a+b)^n.",
                "grade_levels": ["as-level"],
                "keywords": ["binomial", "coefficient", "combination", "choose", "nCr", "expansion", "factorial"],
                "related_ids": [9, 90, 91],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 70,
                "subject": "math",
                "category": "Series",
                "name": "Arithmetic Series Sum (Sn)",
                "latex": r"S_n = \frac{n}{2}[2a + (n-1)d]",
                "description": "The sum of the first n terms of an arithmetic series with first term a and common difference d. Equivalent to n/2 times (first + last).",
                "grade_levels": ["as-level"],
                "keywords": ["arithmetic", "series", "sum", "sigma", "first n terms", "progression"],
                "related_ids": [36, 38, 71],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 71,
                "subject": "math",
                "category": "Series",
                "name": "Geometric Series Sum (Sn)",
                "latex": r"S_n = \frac{a(1 - r^n)}{1 - r}, \quad r \neq 1",
                "description": "The sum of the first n terms of a geometric series with first term a and common ratio r.",
                "grade_levels": ["as-level"],
                "keywords": ["geometric", "series", "sum", "common ratio", "finite", "progression"],
                "related_ids": [37, 39, 72],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 72,
                "subject": "math",
                "category": "Series",
                "name": "Sum to Infinity of Geometric Series",
                "latex": r"S_\infty = \frac{a}{1 - r}, \quad |r| < 1",
                "description": "A convergent geometric series with |r| < 1 has a finite sum to infinity. The series diverges if |r| >= 1.",
                "grade_levels": ["as-level"],
                "keywords": ["geometric", "series", "infinity", "convergent", "sum", "limit"],
                "related_ids": [71, 37, 39],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 73,
                "subject": "math",
                "category": "Calculus",
                "name": "Differentiation — Power Rule",
                "latex": r"\frac{d}{dx}(x^n) = nx^{n-1}",
                "description": "The derivative of x^n is n times x to the power (n-1). The fundamental rule for differentiating polynomial terms.",
                "grade_levels": ["as-level"],
                "keywords": ["differentiation", "derivative", "power rule", "calculus", "gradient", "rate of change"],
                "related_ids": [74, 76, 82],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 74,
                "subject": "math",
                "category": "Calculus",
                "name": "Chain Rule",
                "latex": r"\frac{dy}{dx} = \frac{dy}{du} \times \frac{du}{dx}",
                "description": "Used to differentiate composite functions. If y = f(g(x)), the derivative is f'(g(x)) times g'(x).",
                "grade_levels": ["as-level"],
                "keywords": ["chain rule", "differentiation", "composite", "derivative", "calculus", "substitution"],
                "related_ids": [73, 40, 75],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 75,
                "subject": "math",
                "category": "Calculus",
                "name": "Equation of Tangent and Normal",
                "latex": r"y - y_1 = m(x - x_1), \quad m = f'(x_1)",
                "description": "The tangent to a curve at a point has gradient equal to the derivative at that point. The normal is perpendicular to the tangent with gradient -1/m.",
                "grade_levels": ["as-level"],
                "keywords": ["tangent", "normal", "gradient", "differentiation", "curve", "perpendicular"],
                "related_ids": [73, 43, 44],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 76,
                "subject": "math",
                "category": "Calculus",
                "name": "Integration — Power Rule",
                "latex": r"\int x^n \, dx = \frac{x^{n+1}}{n+1} + C, \quad n \neq -1",
                "description": "The reverse of differentiation for polynomial terms. The constant of integration C accounts for the unknown constant lost during differentiation.",
                "grade_levels": ["as-level"],
                "keywords": ["integration", "antiderivative", "power rule", "calculus", "constant", "indefinite"],
                "related_ids": [73, 77, 82],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 77,
                "subject": "math",
                "category": "Calculus",
                "name": "Definite Integral — Area Under Curve",
                "latex": r"\int_a^b f(x)\,dx = F(b) - F(a)",
                "description": "The definite integral from a to b gives the signed area between the curve y = f(x) and the x-axis. Evaluated using the Fundamental Theorem of Calculus.",
                "grade_levels": ["as-level"],
                "keywords": ["definite integral", "area", "curve", "limits", "calculus", "fundamental theorem"],
                "related_ids": [76, 78, 73],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 78,
                "subject": "math",
                "category": "Calculus",
                "name": "Trapezium Rule",
                "latex": r"\int_a^b f(x)\,dx \approx \frac{h}{2}\left[y_0 + y_n + 2(y_1 + y_2 + \cdots + y_{n-1})\right]",
                "description": "A numerical method for approximating a definite integral by dividing the area into n trapezoids of width h = (b-a)/n.",
                "grade_levels": ["as-level"],
                "keywords": ["trapezium rule", "numerical", "integration", "approximation", "area", "trapezoid"],
                "related_ids": [77, 76],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 79,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Equation of Circle (Completing the Square)",
                "latex": r"x^2 + y^2 + 2gx + 2fy + c = 0 \implies \text{centre } (-g, -f), \; r = \sqrt{g^2 + f^2 - c}",
                "description": "The general form of a circle equation can be converted to centre-radius form by completing the square on both x and y terms.",
                "grade_levels": ["as-level"],
                "keywords": ["circle", "completing the square", "centre", "radius", "general form", "coordinate geometry"],
                "related_ids": [45, 32, 4],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 80,
                "subject": "math",
                "category": "Circular Measure",
                "name": "Arc Length (Radians)",
                "latex": r"s = r\theta",
                "description": "The length of an arc of a circle equals the radius times the angle in radians. A simpler form than the degree-based formula.",
                "grade_levels": ["as-level"],
                "keywords": ["arc length", "radian", "circle", "angle", "sector", "circular measure"],
                "related_ids": [51, 81, 6],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 81,
                "subject": "math",
                "category": "Circular Measure",
                "name": "Sector Area (Radians)",
                "latex": r"A = \frac{1}{2}r^2\theta",
                "description": "The area of a sector of a circle with radius r and angle theta in radians. Half the product of r-squared and the angle.",
                "grade_levels": ["as-level"],
                "keywords": ["sector", "area", "radian", "circle", "angle", "circular measure"],
                "related_ids": [52, 80, 5],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 82,
                "subject": "math",
                "category": "Circular Measure",
                "name": "Radian-Degree Conversion",
                "latex": r"\theta_{\text{rad}} = \frac{\pi}{180} \times \theta_{\text{deg}}",
                "description": "Converts an angle from degrees to radians by multiplying by pi/180. One full revolution is 2*pi radians or 360 degrees.",
                "grade_levels": ["as-level"],
                "keywords": ["radian", "degree", "conversion", "angle", "pi", "circular measure"],
                "related_ids": [80, 81, 51],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Trigonometry (AS) ----------
            {
                "id": 83,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Pythagorean Trigonometric Identity",
                "latex": r"\sin^2\theta + \cos^2\theta = 1",
                "description": "The fundamental trigonometric identity relating sine and cosine. Derived from the Pythagorean theorem on the unit circle.",
                "grade_levels": ["as-level"],
                "keywords": ["identity", "Pythagorean", "sin", "cos", "trigonometry", "unit circle"],
                "related_ids": [55, 56, 84],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 84,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Tangent Identity",
                "latex": r"\tan\theta = \frac{\sin\theta}{\cos\theta}",
                "description": "Tangent is defined as the ratio of sine to cosine. Used to convert between trigonometric functions and solve equations.",
                "grade_levels": ["as-level"],
                "keywords": ["tangent", "identity", "sin", "cos", "ratio", "trigonometry"],
                "related_ids": [83, 55, 57],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 85,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Small Angle Approximations",
                "latex": r"\sin\theta \approx \theta, \quad \cos\theta \approx 1 - \frac{\theta^2}{2}, \quad \tan\theta \approx \theta",
                "description": "For small angles measured in radians, sine and tangent are approximately equal to the angle, and cosine is approximately 1 minus half the angle squared.",
                "grade_levels": ["as-level"],
                "keywords": ["small angle", "approximation", "radian", "sin", "cos", "tan", "limit"],
                "related_ids": [83, 84, 82],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Statistics 1 ----------
            {
                "id": 86,
                "subject": "math",
                "category": "Statistics",
                "name": "Addition Law of Probability",
                "latex": r"P(A \cup B) = P(A) + P(B) - P(A \cap B)",
                "description": "The probability of A or B occurring equals the sum of their individual probabilities minus the probability of both occurring. Avoids double-counting.",
                "grade_levels": ["as-level"],
                "keywords": ["probability", "union", "addition", "or", "mutually exclusive", "events"],
                "related_ids": [62, 87, 63],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 87,
                "subject": "math",
                "category": "Statistics",
                "name": "Conditional Probability",
                "latex": r"P(A|B) = \frac{P(A \cap B)}{P(B)}",
                "description": "The probability of event A occurring given that event B has already occurred. The probability of both events divided by the probability of the conditioning event.",
                "grade_levels": ["as-level"],
                "keywords": ["conditional", "probability", "given", "Bayes", "dependent", "events"],
                "related_ids": [86, 62, 63],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 88,
                "subject": "math",
                "category": "Statistics",
                "name": "Permutations (nPr)",
                "latex": r"{}^nP_r = \frac{n!}{(n-r)!}",
                "description": "The number of ordered arrangements of r items chosen from n distinct items. Order matters in permutations.",
                "grade_levels": ["as-level"],
                "keywords": ["permutation", "arrangement", "order", "factorial", "counting", "nPr"],
                "related_ids": [69, 89, 91],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 89,
                "subject": "math",
                "category": "Statistics",
                "name": "Combinations (nCr)",
                "latex": r"{}^nC_r = \frac{n!}{r!(n-r)!}",
                "description": "The number of ways to choose r items from n distinct items where order does not matter. Used in probability and the binomial distribution.",
                "grade_levels": ["as-level"],
                "keywords": ["combination", "choose", "selection", "factorial", "counting", "nCr"],
                "related_ids": [69, 88, 90],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 90,
                "subject": "math",
                "category": "Statistics",
                "name": "Binomial Distribution",
                "latex": r"P(X = r) = \binom{n}{r} p^r (1-p)^{n-r}",
                "description": "Gives the probability of exactly r successes in n independent trials, each with probability p of success.",
                "grade_levels": ["as-level"],
                "keywords": ["binomial", "distribution", "probability", "trials", "success", "discrete"],
                "related_ids": [89, 69, 91],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 91,
                "subject": "math",
                "category": "Statistics",
                "name": "Expected Value of Binomial Distribution",
                "latex": r"E(X) = np",
                "description": "The expected (mean) number of successes in a binomial distribution with n trials and probability p of success on each trial.",
                "grade_levels": ["as-level"],
                "keywords": ["expected value", "mean", "binomial", "distribution", "np", "average"],
                "related_ids": [90, 92, 61],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 92,
                "subject": "math",
                "category": "Statistics",
                "name": "Normal Distribution Standardisation",
                "latex": r"z = \frac{x - \mu}{\sigma}",
                "description": "Converts a value x from a normal distribution with mean mu and standard deviation sigma into a standard normal z-score.",
                "grade_levels": ["as-level"],
                "keywords": ["normal", "distribution", "z-score", "standardisation", "mean", "standard deviation"],
                "related_ids": [91, 90, 61],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Mechanics 1 ----------
            {
                "id": 93,
                "subject": "math",
                "category": "Mechanics",
                "name": "SUVAT — v = u + at",
                "latex": r"v = u + at",
                "description": "Relates final velocity v to initial velocity u, constant acceleration a, and time t. Used when displacement is not needed.",
                "grade_levels": ["as-level"],
                "keywords": ["SUVAT", "velocity", "acceleration", "time", "kinematics", "constant acceleration"],
                "related_ids": [94, 95, 96],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 94,
                "subject": "math",
                "category": "Mechanics",
                "name": "SUVAT — s = ut + ½at²",
                "latex": r"s = ut + \frac{1}{2}at^2",
                "description": "Gives displacement s in terms of initial velocity u, acceleration a, and time t. Used when final velocity is not needed.",
                "grade_levels": ["as-level"],
                "keywords": ["SUVAT", "displacement", "acceleration", "time", "kinematics", "constant acceleration"],
                "related_ids": [93, 95, 96],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 95,
                "subject": "math",
                "category": "Mechanics",
                "name": "SUVAT — v² = u² + 2as",
                "latex": r"v^2 = u^2 + 2as",
                "description": "Relates final velocity squared to initial velocity squared, acceleration, and displacement. Used when time is not needed.",
                "grade_levels": ["as-level"],
                "keywords": ["SUVAT", "velocity", "displacement", "acceleration", "kinematics", "energy"],
                "related_ids": [93, 94, 96],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 96,
                "subject": "math",
                "category": "Mechanics",
                "name": "SUVAT — s = ½(u + v)t",
                "latex": r"s = \frac{1}{2}(u + v)t",
                "description": "Calculates displacement as the average of initial and final velocities multiplied by time. Used when acceleration is not needed.",
                "grade_levels": ["as-level"],
                "keywords": ["SUVAT", "displacement", "average velocity", "time", "kinematics", "constant acceleration"],
                "related_ids": [93, 94, 95],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 97,
                "subject": "math",
                "category": "Mechanics",
                "name": "Friction Force",
                "latex": r"F = \mu R",
                "description": "The friction force F equals the coefficient of friction mu multiplied by the normal reaction force R. Acts to oppose motion or tendency to move.",
                "grade_levels": ["as-level"],
                "keywords": ["friction", "coefficient", "normal reaction", "force", "rough surface", "mechanics"],
                "related_ids": [93, 98, 13],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 98,
                "subject": "math",
                "category": "Mechanics",
                "name": "Moment of a Force",
                "latex": r"\text{Moment} = F \times d",
                "description": "The moment (turning effect) of a force about a point equals the force multiplied by the perpendicular distance from the point to the line of action of the force.",
                "grade_levels": ["as-level"],
                "keywords": ["moment", "torque", "force", "distance", "equilibrium", "turning effect"],
                "related_ids": [97, 13, 93],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Extra AS formulas to fill IDs 99-100 ----------
            {
                "id": 99,
                "subject": "math",
                "category": "Mechanics",
                "name": "Newton's Second Law (Mechanics)",
                "latex": r"F = ma",
                "description": "The resultant force on a particle equals mass times acceleration. The fundamental equation of motion used throughout Cambridge AS Mechanics.",
                "grade_levels": ["as-level"],
                "keywords": ["Newton", "force", "mass", "acceleration", "resultant", "mechanics", "equation of motion"],
                "related_ids": [13, 93, 97],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 100,
                "subject": "math",
                "category": "Mechanics",
                "name": "Weight",
                "latex": r"W = mg",
                "description": "The weight of an object equals its mass times the acceleration due to gravity (g = 9.8 or 10 m/s^2). Weight acts vertically downward.",
                "grade_levels": ["as-level"],
                "keywords": ["weight", "mass", "gravity", "force", "vertical", "mechanics"],
                "related_ids": [99, 97, 13],
                "curriculum": ["cambridge-as"],
            },
            # ================================================================
            # A2-Level Mathematics (9709 Paper 3/4/7) — IDs 101-130
            # ================================================================
            # ---------- Pure 3 ----------
            {
                "id": 101,
                "subject": "math",
                "category": "Algebra",
                "name": "Modulus Function",
                "latex": r"|x| = \begin{cases} x & \text{if } x \geq 0 \\ -x & \text{if } x < 0 \end{cases}",
                "description": "The modulus (absolute value) of x gives the non-negative value of x. Equations involving modulus are solved by considering separate cases.",
                "grade_levels": ["a2-level"],
                "keywords": ["modulus", "absolute value", "piecewise", "cases", "inequality", "function"],
                "related_ids": [35, 41, 102],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 102,
                "subject": "math",
                "category": "Algebra",
                "name": "Natural Logarithm",
                "latex": r"\ln x = \log_e x, \quad e^{\ln x} = x",
                "description": "The natural logarithm is the logarithm with base e (approximately 2.718). It is the inverse of the exponential function e^x.",
                "grade_levels": ["a2-level"],
                "keywords": ["natural logarithm", "ln", "exponential", "inverse", "base e", "log"],
                "related_ids": [10, 103, 104],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 103,
                "subject": "math",
                "category": "Algebra",
                "name": "Exponential Growth and Decay",
                "latex": r"y = Ae^{kt}",
                "description": "Models exponential growth (k > 0) or decay (k < 0) over time t, where A is the initial value. Used for population, radioactive decay, and cooling problems.",
                "grade_levels": ["a2-level"],
                "keywords": ["exponential", "growth", "decay", "modelling", "rate", "differential equation"],
                "related_ids": [102, 113, 65],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 104,
                "subject": "math",
                "category": "Algebra",
                "name": "Logarithm Change of Base",
                "latex": r"\log_a x = \frac{\log_b x}{\log_b a} = \frac{\ln x}{\ln a}",
                "description": "Converts a logarithm from one base to another. Commonly used to evaluate logarithms using a calculator's ln or log10 buttons.",
                "grade_levels": ["a2-level"],
                "keywords": ["logarithm", "change of base", "conversion", "ln", "log", "algebra"],
                "related_ids": [10, 102, 103],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 105,
                "subject": "math",
                "category": "Calculus",
                "name": "Product Rule",
                "latex": r"\frac{d}{dx}(uv) = u\frac{dv}{dx} + v\frac{du}{dx}",
                "description": "Used to differentiate the product of two functions. The derivative of uv is u times dv/dx plus v times du/dx.",
                "grade_levels": ["a2-level"],
                "keywords": ["product rule", "differentiation", "derivative", "calculus", "multiply", "functions"],
                "related_ids": [73, 106, 74],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 106,
                "subject": "math",
                "category": "Calculus",
                "name": "Quotient Rule",
                "latex": r"\frac{d}{dx}\left(\frac{u}{v}\right) = \frac{v\frac{du}{dx} - u\frac{dv}{dx}}{v^2}",
                "description": "Used to differentiate the quotient of two functions. The derivative of u/v involves the denominator squared.",
                "grade_levels": ["a2-level"],
                "keywords": ["quotient rule", "differentiation", "derivative", "calculus", "division", "functions"],
                "related_ids": [73, 105, 74],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 107,
                "subject": "math",
                "category": "Calculus",
                "name": "Implicit Differentiation",
                "latex": r"\frac{d}{dx}[f(y)] = f'(y)\frac{dy}{dx}",
                "description": "Differentiates an equation where y is not explicitly expressed as a function of x. Apply the chain rule to every y term.",
                "grade_levels": ["a2-level"],
                "keywords": ["implicit", "differentiation", "chain rule", "dy/dx", "calculus", "equation"],
                "related_ids": [74, 105, 108],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 108,
                "subject": "math",
                "category": "Calculus",
                "name": "Parametric Differentiation",
                "latex": r"\frac{dy}{dx} = \frac{\frac{dy}{dt}}{\frac{dx}{dt}}",
                "description": "When x and y are given in terms of a parameter t, the gradient dy/dx is found by dividing dy/dt by dx/dt.",
                "grade_levels": ["a2-level"],
                "keywords": ["parametric", "differentiation", "parameter", "gradient", "calculus", "chain rule"],
                "related_ids": [74, 107, 75],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 109,
                "subject": "math",
                "category": "Calculus",
                "name": "Integration by Parts",
                "latex": r"\int u\,dv = uv - \int v\,du",
                "description": "Reverses the product rule for integration. Choose u and dv so that the resulting integral is simpler than the original.",
                "grade_levels": ["a2-level"],
                "keywords": ["integration by parts", "calculus", "product", "LIATE", "reverse product rule"],
                "related_ids": [105, 76, 110],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 110,
                "subject": "math",
                "category": "Calculus",
                "name": "Integration by Substitution",
                "latex": r"\int f(g(x))g'(x)\,dx = \int f(u)\,du, \quad u = g(x)",
                "description": "Reverses the chain rule for integration. Substitute u = g(x) to simplify the integrand, then convert back to x.",
                "grade_levels": ["a2-level"],
                "keywords": ["integration", "substitution", "reverse chain rule", "calculus", "change of variable"],
                "related_ids": [74, 76, 109],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 111,
                "subject": "math",
                "category": "Calculus",
                "name": "Partial Fractions Decomposition",
                "latex": r"\frac{px + q}{(ax+b)(cx+d)} = \frac{A}{ax+b} + \frac{B}{cx+d}",
                "description": "Decomposes a rational expression into simpler fractions that can be integrated individually. Used for distinct linear factors.",
                "grade_levels": ["a2-level"],
                "keywords": ["partial fractions", "decomposition", "rational", "integration", "linear factors", "algebra"],
                "related_ids": [76, 109, 67],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 112,
                "subject": "math",
                "category": "Calculus",
                "name": "Separation of Variables (ODE)",
                "latex": r"\frac{dy}{dx} = f(x)g(y) \implies \int \frac{1}{g(y)}\,dy = \int f(x)\,dx",
                "description": "Solves first-order ordinary differential equations by moving all y terms to one side and all x terms to the other, then integrating both sides.",
                "grade_levels": ["a2-level"],
                "keywords": ["separation of variables", "differential equation", "ODE", "calculus", "first order"],
                "related_ids": [76, 103, 113],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 113,
                "subject": "math",
                "category": "Calculus",
                "name": "Integrating Factor",
                "latex": r"\frac{dy}{dx} + P(x)y = Q(x), \quad \text{I.F.} = e^{\int P(x)\,dx}",
                "description": "Solves first-order linear ODEs by multiplying through by the integrating factor, making the left side an exact derivative.",
                "grade_levels": ["a2-level"],
                "keywords": ["integrating factor", "differential equation", "ODE", "linear", "first order", "calculus"],
                "related_ids": [112, 102, 76],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Trigonometry (A2) ----------
            {
                "id": 114,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Double Angle — sin 2A",
                "latex": r"\sin 2A = 2\sin A\cos A",
                "description": "Expresses the sine of double an angle in terms of sine and cosine of the original angle. Used in integration and solving trig equations.",
                "grade_levels": ["a2-level"],
                "keywords": ["double angle", "sin", "identity", "trigonometry", "2A", "formula"],
                "related_ids": [83, 115, 116],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 115,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Double Angle — cos 2A",
                "latex": r"\cos 2A = \cos^2 A - \sin^2 A = 2\cos^2 A - 1 = 1 - 2\sin^2 A",
                "description": "Three equivalent forms for cosine of double an angle. The choice of form depends on the context of the problem.",
                "grade_levels": ["a2-level"],
                "keywords": ["double angle", "cos", "identity", "trigonometry", "2A", "formula"],
                "related_ids": [83, 114, 117],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 116,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Addition Formula — sin(A ± B)",
                "latex": r"\sin(A \pm B) = \sin A\cos B \pm \cos A\sin B",
                "description": "Expands the sine of a sum or difference of two angles. The sign in the result matches the sign in the argument.",
                "grade_levels": ["a2-level"],
                "keywords": ["addition formula", "compound angle", "sin", "trigonometry", "sum", "difference"],
                "related_ids": [114, 117, 83],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 117,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Addition Formula — cos(A ± B)",
                "latex": r"\cos(A \pm B) = \cos A\cos B \mp \sin A\sin B",
                "description": "Expands the cosine of a sum or difference of two angles. Note the sign flips: cos(A+B) uses minus, cos(A-B) uses plus.",
                "grade_levels": ["a2-level"],
                "keywords": ["addition formula", "compound angle", "cos", "trigonometry", "sum", "difference"],
                "related_ids": [115, 116, 83],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 118,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Harmonic Form (R sin/cos)",
                "latex": r"a\sin\theta + b\cos\theta = R\sin(\theta + \alpha), \quad R = \sqrt{a^2 + b^2}, \; \tan\alpha = \frac{b}{a}",
                "description": "Combines a sine and cosine expression into a single sinusoidal function. Useful for finding maximum/minimum values and solving equations.",
                "grade_levels": ["a2-level"],
                "keywords": ["harmonic form", "R formula", "amplitude", "phase", "trigonometry", "maximum", "minimum"],
                "related_ids": [116, 117, 83],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Complex Numbers ----------
            {
                "id": 119,
                "subject": "math",
                "category": "Complex Numbers",
                "name": "Modulus of a Complex Number",
                "latex": r"|z| = |a + bi| = \sqrt{a^2 + b^2}",
                "description": "The modulus of a complex number z = a + bi is the distance from the origin to the point (a, b) on the Argand diagram.",
                "grade_levels": ["a2-level"],
                "keywords": ["modulus", "complex number", "magnitude", "Argand", "distance", "absolute value"],
                "related_ids": [59, 120, 121],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 120,
                "subject": "math",
                "category": "Complex Numbers",
                "name": "Argument of a Complex Number",
                "latex": r"\arg(z) = \arctan\left(\frac{b}{a}\right)",
                "description": "The argument of z = a + bi is the angle measured anticlockwise from the positive real axis to the line joining the origin to z. Care is needed with the quadrant.",
                "grade_levels": ["a2-level"],
                "keywords": ["argument", "complex number", "angle", "Argand", "arctan", "phase"],
                "related_ids": [119, 121, 57],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 121,
                "subject": "math",
                "category": "Complex Numbers",
                "name": "Polar (Trigonometric) Form",
                "latex": r"z = r(\cos\theta + i\sin\theta)",
                "description": "Expresses a complex number using its modulus r and argument theta. Also written as r*cis(theta). Essential for multiplication, division, and powers.",
                "grade_levels": ["a2-level"],
                "keywords": ["polar form", "trigonometric form", "modulus-argument", "complex number", "cis"],
                "related_ids": [119, 120, 122],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 122,
                "subject": "math",
                "category": "Complex Numbers",
                "name": "De Moivre's Theorem",
                "latex": r"[r(\cos\theta + i\sin\theta)]^n = r^n(\cos n\theta + i\sin n\theta)",
                "description": "Raises a complex number in polar form to the power n by raising the modulus to the power n and multiplying the argument by n. Works for all integer n.",
                "grade_levels": ["a2-level"],
                "keywords": ["de Moivre", "theorem", "complex", "power", "roots", "polar form"],
                "related_ids": [121, 119, 120],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Vectors (A2) ----------
            {
                "id": 123,
                "subject": "math",
                "category": "Vectors",
                "name": "Scalar (Dot) Product",
                "latex": r"\mathbf{a} \cdot \mathbf{b} = |\mathbf{a}||\mathbf{b}|\cos\theta",
                "description": "The scalar product of two vectors equals the product of their magnitudes times the cosine of the angle between them. Also computed as a1*b1 + a2*b2 + a3*b3.",
                "grade_levels": ["a2-level"],
                "keywords": ["scalar product", "dot product", "vectors", "angle", "perpendicular", "cosine"],
                "related_ids": [59, 124, 125],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 124,
                "subject": "math",
                "category": "Vectors",
                "name": "Equation of a Line (Vector Form)",
                "latex": r"\mathbf{r} = \mathbf{a} + t\mathbf{b}",
                "description": "The position vector of any point on a line through point A (with position vector a) in the direction of vector b, where t is a scalar parameter.",
                "grade_levels": ["a2-level"],
                "keywords": ["vector equation", "line", "direction", "parameter", "position vector", "3D"],
                "related_ids": [60, 123, 125],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 125,
                "subject": "math",
                "category": "Vectors",
                "name": "Angle Between Two Vectors",
                "latex": r"\cos\theta = \frac{\mathbf{a} \cdot \mathbf{b}}{|\mathbf{a}||\mathbf{b}|}",
                "description": "The angle between two vectors is found using the dot product formula rearranged. If the dot product is zero, the vectors are perpendicular.",
                "grade_levels": ["a2-level"],
                "keywords": ["angle", "vectors", "dot product", "cosine", "perpendicular", "direction"],
                "related_ids": [123, 59, 124],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Statistics 2 ----------
            {
                "id": 126,
                "subject": "math",
                "category": "Statistics",
                "name": "Poisson Distribution",
                "latex": r"P(X = r) = \frac{e^{-\lambda}\lambda^r}{r!}",
                "description": "Gives the probability of r events occurring in a fixed interval when events happen at a constant average rate lambda independently of each other.",
                "grade_levels": ["a2-level"],
                "keywords": ["Poisson", "distribution", "probability", "lambda", "rate", "discrete"],
                "related_ids": [90, 92, 127],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 127,
                "subject": "math",
                "category": "Statistics",
                "name": "Confidence Interval for Mean",
                "latex": r"\bar{x} \pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}}",
                "description": "Gives a range of plausible values for the population mean based on a sample. The z-value depends on the confidence level (e.g., 1.96 for 95%).",
                "grade_levels": ["a2-level"],
                "keywords": ["confidence interval", "mean", "z-score", "sample", "normal", "estimation"],
                "related_ids": [92, 126, 61],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Additional A2 formulas to fill IDs 128-130 ----------
            {
                "id": 128,
                "subject": "math",
                "category": "Calculus",
                "name": "Derivative of Exponential Function",
                "latex": r"\frac{d}{dx}(e^{kx}) = ke^{kx}",
                "description": "The exponential function e^(kx) differentiates to k times itself. This self-replicating property makes e^x unique among all functions.",
                "grade_levels": ["a2-level"],
                "keywords": ["exponential", "derivative", "differentiation", "e", "calculus", "natural"],
                "related_ids": [73, 102, 103],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 129,
                "subject": "math",
                "category": "Calculus",
                "name": "Derivative of ln x",
                "latex": r"\frac{d}{dx}(\ln x) = \frac{1}{x}",
                "description": "The derivative of the natural logarithm of x is 1/x. This means the integral of 1/x is ln|x| + C.",
                "grade_levels": ["a2-level"],
                "keywords": ["ln", "logarithm", "derivative", "differentiation", "reciprocal", "calculus"],
                "related_ids": [73, 102, 76],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 130,
                "subject": "math",
                "category": "Calculus",
                "name": "Derivative of Trigonometric Functions",
                "latex": r"\frac{d}{dx}(\sin x) = \cos x, \quad \frac{d}{dx}(\cos x) = -\sin x",
                "description": "The fundamental trigonometric derivatives. Sine differentiates to cosine, and cosine differentiates to negative sine.",
                "grade_levels": ["a2-level"],
                "keywords": ["trigonometric", "derivative", "sin", "cos", "differentiation", "calculus"],
                "related_ids": [73, 83, 114],
                "curriculum": ["cambridge-a2"],
            },
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM formulas WHERE id >= 31 AND id <= 130")
