"""Seed Cambridge Physics formulas

Revision ID: 008_seed_cambridge_physics
Revises: 007_seed_cambridge_math
Create Date: 2026-03-03
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "008_seed_cambridge_physics"
down_revision: Union[str, None] = "007_seed_cambridge_math"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    formulas_table = sa.table(
        "formulas",
        sa.column("id", sa.BigInteger),
        sa.column("subject", sa.String),
        sa.column("category", sa.String),
        sa.column("name", sa.String),
        sa.column("latex", sa.Text),
        sa.column("description", sa.Text),
        sa.column("grade_levels", postgresql.ARRAY(sa.String)),
        sa.column("keywords", postgresql.ARRAY(sa.String)),
        sa.column("related_ids", postgresql.ARRAY(sa.BigInteger)),
        sa.column("curriculum", postgresql.ARRAY(sa.String)),
    )

    op.bulk_insert(
        formulas_table,
        [
            # ==================== IGCSE PHYSICS (0625) — IDs 131-160 ====================
            # ---------- General Physics ----------
            {
                "id": 131,
                "subject": "physics",
                "category": "General Physics",
                "name": "Density",
                "latex": r"\rho = \frac{m}{V}",
                "description": "Density is the mass per unit volume of a substance. It is a characteristic property used to identify materials.",
                "grade_levels": ["igcse"],
                "keywords": ["density", "mass", "volume", "substance", "property", "rho"],
                "related_ids": [132, 138],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 132,
                "subject": "physics",
                "category": "General Physics",
                "name": "Speed",
                "latex": r"v = \frac{d}{t}",
                "description": "Speed is the distance travelled per unit time. It is a scalar quantity with no direction.",
                "grade_levels": ["igcse"],
                "keywords": ["speed", "distance", "time", "velocity", "motion", "scalar"],
                "related_ids": [17, 133, 134],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 133,
                "subject": "physics",
                "category": "General Physics",
                "name": "Acceleration",
                "latex": r"a = \frac{\Delta v}{\Delta t}",
                "description": "Acceleration is the rate of change of velocity with respect to time. A negative value indicates deceleration.",
                "grade_levels": ["igcse"],
                "keywords": ["acceleration", "velocity", "time", "deceleration", "kinematics", "rate"],
                "related_ids": [18, 132, 134],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 134,
                "subject": "physics",
                "category": "General Physics",
                "name": "Force (Newton's Second Law)",
                "latex": r"F = ma",
                "description": "The resultant force acting on an object equals its mass multiplied by its acceleration. This is Newton's second law of motion.",
                "grade_levels": ["igcse"],
                "keywords": ["force", "mass", "acceleration", "newton", "resultant", "dynamics"],
                "related_ids": [13, 133, 135],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 135,
                "subject": "physics",
                "category": "General Physics",
                "name": "Weight",
                "latex": r"W = mg",
                "description": "Weight is the gravitational force acting on an object, equal to its mass times the gravitational field strength (g = 9.81 m/s^2 on Earth).",
                "grade_levels": ["igcse"],
                "keywords": ["weight", "mass", "gravity", "gravitational", "force", "g"],
                "related_ids": [134, 15, 136],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 136,
                "subject": "physics",
                "category": "General Physics",
                "name": "Moment of a Force",
                "latex": r"\text{Moment} = F \times d",
                "description": "The moment of a force about a pivot is the product of the force and the perpendicular distance from the pivot to the line of action of the force.",
                "grade_levels": ["igcse"],
                "keywords": ["moment", "force", "distance", "pivot", "torque", "turning effect"],
                "related_ids": [134, 137],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 137,
                "subject": "physics",
                "category": "General Physics",
                "name": "Pressure",
                "latex": r"p = \frac{F}{A}",
                "description": "Pressure is the force acting per unit area. It is measured in pascals (Pa).",
                "grade_levels": ["igcse"],
                "keywords": ["pressure", "force", "area", "pascal", "surface"],
                "related_ids": [134, 138],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 138,
                "subject": "physics",
                "category": "General Physics",
                "name": "Pressure in a Liquid",
                "latex": r"p = \rho g h",
                "description": "The pressure at a depth h in a liquid is the product of the liquid's density, gravitational field strength, and depth below the surface.",
                "grade_levels": ["igcse"],
                "keywords": ["pressure", "liquid", "depth", "density", "hydrostatic", "fluid"],
                "related_ids": [131, 137],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 139,
                "subject": "physics",
                "category": "General Physics",
                "name": "Hooke's Law",
                "latex": r"F = kx",
                "description": "The force needed to extend or compress a spring is directly proportional to the extension or compression, where k is the spring constant.",
                "grade_levels": ["igcse"],
                "keywords": ["hooke", "spring", "extension", "force", "elastic", "spring constant"],
                "related_ids": [134, 140],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 140,
                "subject": "physics",
                "category": "General Physics",
                "name": "Spring Constant",
                "latex": r"k = \frac{F}{x}",
                "description": "The spring constant is the ratio of the applied force to the extension produced. A higher value means a stiffer spring.",
                "grade_levels": ["igcse"],
                "keywords": ["spring constant", "stiffness", "force", "extension", "hooke", "elastic"],
                "related_ids": [139, 134],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Thermal Physics ----------
            {
                "id": 141,
                "subject": "physics",
                "category": "Thermal Physics",
                "name": "Specific Heat Capacity",
                "latex": r"Q = mc\Delta T",
                "description": "The energy required to change the temperature of a substance depends on its mass, specific heat capacity, and the temperature change.",
                "grade_levels": ["igcse"],
                "keywords": ["heat", "specific heat capacity", "temperature", "energy", "thermal", "calorimetry"],
                "related_ids": [142, 143],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 142,
                "subject": "physics",
                "category": "Thermal Physics",
                "name": "Latent Heat",
                "latex": r"Q = mL",
                "description": "The energy required to change the state of a substance without changing its temperature, where L is the specific latent heat.",
                "grade_levels": ["igcse"],
                "keywords": ["latent heat", "phase change", "melting", "boiling", "vaporisation", "fusion"],
                "related_ids": [141, 143],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 143,
                "subject": "physics",
                "category": "Thermal Physics",
                "name": "Gas Law (Combined)",
                "latex": r"\frac{P_1 V_1}{T_1} = \frac{P_2 V_2}{T_2}",
                "description": "The combined gas law relates pressure, volume, and absolute temperature of a fixed mass of gas. Temperature must be in kelvin.",
                "grade_levels": ["igcse"],
                "keywords": ["gas law", "pressure", "volume", "temperature", "kelvin", "boyle", "charles"],
                "related_ids": [141, 137],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 144,
                "subject": "physics",
                "category": "Thermal Physics",
                "name": "Thermal Expansion (Linear)",
                "latex": r"\Delta L = L_0 \alpha \Delta T",
                "description": "The change in length of a solid when heated is proportional to its original length, the coefficient of linear expansion, and the temperature change.",
                "grade_levels": ["igcse"],
                "keywords": ["thermal expansion", "linear", "length", "temperature", "coefficient", "heating"],
                "related_ids": [141, 143],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Waves ----------
            {
                "id": 145,
                "subject": "physics",
                "category": "Waves",
                "name": "Wave Speed Equation",
                "latex": r"v = f\lambda",
                "description": "The speed of a wave equals its frequency multiplied by its wavelength. Applies to all types of waves.",
                "grade_levels": ["igcse"],
                "keywords": ["wave", "speed", "frequency", "wavelength", "oscillation"],
                "related_ids": [146, 147],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 146,
                "subject": "physics",
                "category": "Waves",
                "name": "Frequency and Period",
                "latex": r"f = \frac{1}{T}",
                "description": "Frequency is the reciprocal of the period. Frequency measures cycles per second (Hz), while period is the time for one complete cycle.",
                "grade_levels": ["igcse"],
                "keywords": ["frequency", "period", "hertz", "cycle", "oscillation", "wave"],
                "related_ids": [145, 147],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 147,
                "subject": "physics",
                "category": "Waves",
                "name": "Snell's Law",
                "latex": r"n_1 \sin\theta_1 = n_2 \sin\theta_2",
                "description": "Snell's law relates the angles of incidence and refraction to the refractive indices of two media at a boundary.",
                "grade_levels": ["igcse"],
                "keywords": ["snell", "refraction", "angle", "refractive index", "boundary", "light"],
                "related_ids": [148, 149],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 148,
                "subject": "physics",
                "category": "Waves",
                "name": "Refractive Index",
                "latex": r"n = \frac{c}{v}",
                "description": "The refractive index of a medium is the ratio of the speed of light in a vacuum to the speed of light in that medium.",
                "grade_levels": ["igcse"],
                "keywords": ["refractive index", "speed of light", "medium", "optics", "refraction"],
                "related_ids": [147, 149],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 149,
                "subject": "physics",
                "category": "Waves",
                "name": "Critical Angle",
                "latex": r"\sin C = \frac{1}{n}",
                "description": "The critical angle is the angle of incidence above which total internal reflection occurs when light passes from a denser to a less dense medium.",
                "grade_levels": ["igcse"],
                "keywords": ["critical angle", "total internal reflection", "refractive index", "optics", "fibre"],
                "related_ids": [147, 148],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 150,
                "subject": "physics",
                "category": "Waves",
                "name": "Magnification",
                "latex": r"m = \frac{\text{image height}}{\text{object height}}",
                "description": "Magnification is the ratio of the image height to the object height. A value greater than 1 means the image is enlarged.",
                "grade_levels": ["igcse"],
                "keywords": ["magnification", "image", "object", "lens", "mirror", "optics"],
                "related_ids": [147, 148],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Electricity ----------
            {
                "id": 151,
                "subject": "physics",
                "category": "Electricity",
                "name": "Current",
                "latex": r"I = \frac{Q}{t}",
                "description": "Electric current is the rate of flow of electric charge. One ampere is one coulomb of charge flowing per second.",
                "grade_levels": ["igcse"],
                "keywords": ["current", "charge", "time", "ampere", "coulomb", "flow"],
                "related_ids": [16, 152, 153],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 152,
                "subject": "physics",
                "category": "Electricity",
                "name": "Ohm's Law",
                "latex": r"V = IR",
                "description": "The potential difference across a conductor is proportional to the current through it, provided temperature remains constant.",
                "grade_levels": ["igcse"],
                "keywords": ["ohm", "voltage", "current", "resistance", "circuit", "conductor"],
                "related_ids": [16, 151, 153],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 153,
                "subject": "physics",
                "category": "Electricity",
                "name": "Electrical Power",
                "latex": r"P = IV",
                "description": "Electrical power is the rate of energy transfer in a circuit, equal to the product of current and potential difference.",
                "grade_levels": ["igcse"],
                "keywords": ["power", "current", "voltage", "energy", "watt", "electrical"],
                "related_ids": [152, 154, 155],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 154,
                "subject": "physics",
                "category": "Electricity",
                "name": "Power (Current and Resistance)",
                "latex": r"P = I^2 R",
                "description": "Electrical power dissipated in a resistor can be calculated from the current squared times the resistance.",
                "grade_levels": ["igcse"],
                "keywords": ["power", "current", "resistance", "dissipation", "heating", "joule"],
                "related_ids": [152, 153, 155],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 155,
                "subject": "physics",
                "category": "Electricity",
                "name": "Power (Voltage and Resistance)",
                "latex": r"P = \frac{V^2}{R}",
                "description": "Electrical power can also be expressed as the square of the voltage divided by the resistance.",
                "grade_levels": ["igcse"],
                "keywords": ["power", "voltage", "resistance", "energy transfer", "circuit"],
                "related_ids": [152, 153, 154],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 156,
                "subject": "physics",
                "category": "Electricity",
                "name": "Electrical Energy",
                "latex": r"E = Pt",
                "description": "The electrical energy transferred is the product of power and time. Energy is measured in joules when power is in watts and time in seconds.",
                "grade_levels": ["igcse"],
                "keywords": ["energy", "power", "time", "joule", "kilowatt-hour", "transfer"],
                "related_ids": [153, 152],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 157,
                "subject": "physics",
                "category": "Electricity",
                "name": "Resistors in Series",
                "latex": r"R_t = R_1 + R_2 + R_3",
                "description": "The total resistance of resistors connected in series is the sum of their individual resistances.",
                "grade_levels": ["igcse"],
                "keywords": ["resistors", "series", "total resistance", "circuit", "addition"],
                "related_ids": [152, 158],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 158,
                "subject": "physics",
                "category": "Electricity",
                "name": "Resistors in Parallel",
                "latex": r"\frac{1}{R_t} = \frac{1}{R_1} + \frac{1}{R_2} + \frac{1}{R_3}",
                "description": "The reciprocal of the total resistance of parallel resistors equals the sum of the reciprocals of their individual resistances.",
                "grade_levels": ["igcse"],
                "keywords": ["resistors", "parallel", "total resistance", "circuit", "reciprocal"],
                "related_ids": [152, 157],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 159,
                "subject": "physics",
                "category": "Electricity",
                "name": "EMF and Terminal PD",
                "latex": r"\varepsilon = I(R + r)",
                "description": "The electromotive force of a source equals the current times the sum of external resistance and internal resistance.",
                "grade_levels": ["igcse"],
                "keywords": ["emf", "terminal pd", "internal resistance", "voltage", "battery", "source"],
                "related_ids": [152, 157, 183],
                "curriculum": ["cambridge-igcse"],
            },
            # ---------- Nuclear Physics ----------
            {
                "id": 160,
                "subject": "physics",
                "category": "Nuclear Physics",
                "name": "Half-Life and Activity",
                "latex": r"A = \frac{A_0}{2^n}",
                "description": "After n half-lives, the activity (or count rate) of a radioactive sample is the original activity divided by 2 to the power n.",
                "grade_levels": ["igcse"],
                "keywords": ["half-life", "activity", "radioactive", "decay", "count rate", "nuclear"],
                "related_ids": [208, 209],
                "curriculum": ["cambridge-igcse"],
            },
            # ==================== AS PHYSICS (9702) — IDs 161-185 ====================
            # ---------- Kinematics ----------
            {
                "id": 161,
                "subject": "physics",
                "category": "Kinematics",
                "name": "SUVAT: Final Velocity",
                "latex": r"v = u + at",
                "description": "The final velocity equals the initial velocity plus the product of acceleration and time. One of the four SUVAT equations of uniformly accelerated motion.",
                "grade_levels": ["as-level"],
                "keywords": ["suvat", "velocity", "acceleration", "time", "kinematics", "uniform"],
                "related_ids": [133, 162, 163],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 162,
                "subject": "physics",
                "category": "Kinematics",
                "name": "SUVAT: Displacement (Time)",
                "latex": r"s = ut + \frac{1}{2}at^2",
                "description": "Displacement equals initial velocity times time plus half the acceleration times time squared. Used when final velocity is unknown.",
                "grade_levels": ["as-level"],
                "keywords": ["suvat", "displacement", "acceleration", "time", "kinematics", "motion"],
                "related_ids": [161, 163, 164],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 163,
                "subject": "physics",
                "category": "Kinematics",
                "name": "SUVAT: Velocity-Displacement",
                "latex": r"v^2 = u^2 + 2as",
                "description": "The square of final velocity equals the square of initial velocity plus twice the product of acceleration and displacement. Used when time is unknown.",
                "grade_levels": ["as-level"],
                "keywords": ["suvat", "velocity", "displacement", "acceleration", "kinematics"],
                "related_ids": [161, 162, 164],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 164,
                "subject": "physics",
                "category": "Kinematics",
                "name": "SUVAT: Average Velocity",
                "latex": r"s = \frac{1}{2}(u + v)t",
                "description": "Displacement equals half the sum of initial and final velocities multiplied by time. Used when acceleration is unknown.",
                "grade_levels": ["as-level"],
                "keywords": ["suvat", "displacement", "average velocity", "time", "kinematics"],
                "related_ids": [161, 162, 163],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 165,
                "subject": "physics",
                "category": "Kinematics",
                "name": "Projectile Horizontal Range",
                "latex": r"R = \frac{u^2 \sin 2\theta}{g}",
                "description": "The horizontal range of a projectile launched at angle theta with initial speed u, assuming level ground and no air resistance.",
                "grade_levels": ["as-level"],
                "keywords": ["projectile", "range", "angle", "velocity", "gravity", "trajectory"],
                "related_ids": [162, 166],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 166,
                "subject": "physics",
                "category": "Kinematics",
                "name": "Projectile Maximum Height",
                "latex": r"H = \frac{u^2 \sin^2\theta}{2g}",
                "description": "The maximum height reached by a projectile launched at angle theta with initial speed u, in the absence of air resistance.",
                "grade_levels": ["as-level"],
                "keywords": ["projectile", "maximum height", "angle", "velocity", "gravity"],
                "related_ids": [163, 165],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Dynamics ----------
            {
                "id": 167,
                "subject": "physics",
                "category": "Dynamics",
                "name": "Momentum",
                "latex": r"p = mv",
                "description": "Linear momentum is the product of mass and velocity. It is a vector quantity conserved in all collisions.",
                "grade_levels": ["as-level"],
                "keywords": ["momentum", "mass", "velocity", "linear", "vector", "conservation"],
                "related_ids": [21, 168, 169],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 168,
                "subject": "physics",
                "category": "Dynamics",
                "name": "Impulse",
                "latex": r"F\Delta t = \Delta p",
                "description": "Impulse is the product of force and time interval, equal to the change in momentum. It represents the effect of a force acting over time.",
                "grade_levels": ["as-level"],
                "keywords": ["impulse", "force", "time", "momentum", "change", "collision"],
                "related_ids": [167, 134, 169],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 169,
                "subject": "physics",
                "category": "Dynamics",
                "name": "Conservation of Momentum",
                "latex": r"m_1 u_1 + m_2 u_2 = m_1 v_1 + m_2 v_2",
                "description": "In a closed system with no external forces, the total momentum before a collision equals the total momentum after the collision.",
                "grade_levels": ["as-level"],
                "keywords": ["conservation", "momentum", "collision", "closed system", "interaction"],
                "related_ids": [167, 168, 170],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 170,
                "subject": "physics",
                "category": "Dynamics",
                "name": "Elastic Collision KE Conservation",
                "latex": r"\frac{1}{2}m_1 u_1^2 + \frac{1}{2}m_2 u_2^2 = \frac{1}{2}m_1 v_1^2 + \frac{1}{2}m_2 v_2^2",
                "description": "In a perfectly elastic collision, both momentum and kinetic energy are conserved. Total kinetic energy before equals total kinetic energy after.",
                "grade_levels": ["as-level"],
                "keywords": ["elastic", "collision", "kinetic energy", "conservation", "inelastic"],
                "related_ids": [14, 169, 167],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Forces ----------
            {
                "id": 171,
                "subject": "physics",
                "category": "Forces",
                "name": "Torque (Moment of a Force)",
                "latex": r"\tau = Fd",
                "description": "Torque is the product of force and the perpendicular distance from the pivot to the line of action of the force. It causes rotational motion.",
                "grade_levels": ["as-level"],
                "keywords": ["torque", "moment", "force", "distance", "rotation", "pivot"],
                "related_ids": [136, 172, 173],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 172,
                "subject": "physics",
                "category": "Forces",
                "name": "Equilibrium Conditions",
                "latex": r"\sum F = 0 \quad \text{and} \quad \sum \tau = 0",
                "description": "For a body in static equilibrium, the vector sum of all forces and the sum of all moments about any point must both equal zero.",
                "grade_levels": ["as-level"],
                "keywords": ["equilibrium", "forces", "moments", "static", "balanced", "resultant"],
                "related_ids": [171, 134, 173],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 173,
                "subject": "physics",
                "category": "Forces",
                "name": "Centre of Gravity",
                "latex": r"\bar{x} = \frac{\sum m_i x_i}{\sum m_i}",
                "description": "The centre of gravity is the point where the entire weight of a body can be considered to act. It is the mass-weighted average position.",
                "grade_levels": ["as-level"],
                "keywords": ["centre of gravity", "center of mass", "weight", "balance", "position"],
                "related_ids": [135, 171, 172],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Work, Energy and Power ----------
            {
                "id": 174,
                "subject": "physics",
                "category": "Work, Energy and Power",
                "name": "Work Done",
                "latex": r"W = Fs\cos\theta",
                "description": "Work done by a force is the product of the force, the displacement, and the cosine of the angle between them. No work is done if the force is perpendicular to the displacement.",
                "grade_levels": ["as-level"],
                "keywords": ["work", "force", "displacement", "angle", "energy transfer", "joule"],
                "related_ids": [19, 175, 176],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 175,
                "subject": "physics",
                "category": "Work, Energy and Power",
                "name": "Kinetic Energy",
                "latex": r"E_k = \frac{1}{2}mv^2",
                "description": "Kinetic energy is the energy of a body due to its motion, proportional to its mass and the square of its velocity.",
                "grade_levels": ["as-level"],
                "keywords": ["kinetic energy", "mass", "velocity", "motion", "joule"],
                "related_ids": [14, 176, 174],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 176,
                "subject": "physics",
                "category": "Work, Energy and Power",
                "name": "Gravitational Potential Energy",
                "latex": r"E_p = mgh",
                "description": "Gravitational potential energy is the energy stored in an object due to its height above a reference level in a uniform gravitational field.",
                "grade_levels": ["as-level"],
                "keywords": ["gravitational", "potential energy", "height", "mass", "gravity"],
                "related_ids": [15, 175, 177],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 177,
                "subject": "physics",
                "category": "Work, Energy and Power",
                "name": "Efficiency",
                "latex": r"\eta = \frac{\text{useful energy output}}{\text{total energy input}} \times 100\%",
                "description": "Efficiency is the ratio of useful energy output to total energy input, expressed as a percentage. No real machine is 100% efficient.",
                "grade_levels": ["as-level"],
                "keywords": ["efficiency", "energy", "useful", "output", "input", "percentage"],
                "related_ids": [174, 178],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 178,
                "subject": "physics",
                "category": "Work, Energy and Power",
                "name": "Power (Force and Velocity)",
                "latex": r"P = Fv",
                "description": "The power delivered by a constant force on a body moving at velocity v equals the product of force and velocity.",
                "grade_levels": ["as-level"],
                "keywords": ["power", "force", "velocity", "rate", "energy", "watt"],
                "related_ids": [20, 174, 177],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Waves ----------
            {
                "id": 179,
                "subject": "physics",
                "category": "Waves",
                "name": "Intensity",
                "latex": r"I = \frac{P}{A}",
                "description": "Intensity is the power transmitted per unit area perpendicular to the direction of wave propagation. It is measured in W/m^2.",
                "grade_levels": ["as-level"],
                "keywords": ["intensity", "power", "area", "wave", "energy", "propagation"],
                "related_ids": [145, 153],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 180,
                "subject": "physics",
                "category": "Waves",
                "name": "Interference Path Difference",
                "latex": r"\Delta x = n\lambda \quad \text{(constructive)}, \quad \Delta x = (n+\tfrac{1}{2})\lambda \quad \text{(destructive)}",
                "description": "Constructive interference occurs when the path difference is a whole number of wavelengths; destructive interference when it is an odd number of half wavelengths.",
                "grade_levels": ["as-level"],
                "keywords": ["interference", "path difference", "constructive", "destructive", "wavelength", "superposition"],
                "related_ids": [145, 181],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 181,
                "subject": "physics",
                "category": "Waves",
                "name": "Diffraction Grating",
                "latex": r"d\sin\theta = n\lambda",
                "description": "The diffraction grating equation relates the slit spacing d, the diffraction angle, the order number n, and the wavelength of light.",
                "grade_levels": ["as-level"],
                "keywords": ["diffraction", "grating", "wavelength", "angle", "order", "slit spacing"],
                "related_ids": [145, 180],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 182,
                "subject": "physics",
                "category": "Waves",
                "name": "Doppler Effect",
                "latex": r"f' = f\frac{v}{v \pm v_s}",
                "description": "The observed frequency changes when the source moves relative to the observer. Use minus when the source approaches and plus when it recedes.",
                "grade_levels": ["as-level"],
                "keywords": ["doppler", "frequency", "source", "observer", "sound", "wave"],
                "related_ids": [145, 146],
                "curriculum": ["cambridge-as"],
            },
            # ---------- Electricity ----------
            {
                "id": 183,
                "subject": "physics",
                "category": "Electricity",
                "name": "Potential Divider",
                "latex": r"V_{\text{out}} = V_{\text{in}} \times \frac{R_2}{R_1 + R_2}",
                "description": "A potential divider splits the input voltage across two series resistors in proportion to their resistances.",
                "grade_levels": ["as-level"],
                "keywords": ["potential divider", "voltage divider", "resistor", "circuit", "output voltage"],
                "related_ids": [152, 157, 159],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 184,
                "subject": "physics",
                "category": "Electricity",
                "name": "Kirchhoff's Laws",
                "latex": r"\sum I_{\text{in}} = \sum I_{\text{out}} \quad \text{and} \quad \sum \varepsilon = \sum IR",
                "description": "Kirchhoff's first law states that current into a junction equals current out. The second law states that the sum of EMFs around a loop equals the sum of potential drops.",
                "grade_levels": ["as-level"],
                "keywords": ["kirchhoff", "junction", "loop", "current", "emf", "conservation"],
                "related_ids": [151, 152, 159],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 185,
                "subject": "physics",
                "category": "Electricity",
                "name": "Resistivity",
                "latex": r"\rho = \frac{RA}{L}",
                "description": "Resistivity is a material property relating resistance to the cross-sectional area and length of a conductor. It is measured in ohm-metres.",
                "grade_levels": ["as-level"],
                "keywords": ["resistivity", "resistance", "area", "length", "material", "conductor"],
                "related_ids": [152, 157, 158],
                "curriculum": ["cambridge-as"],
            },
            # ==================== A2 PHYSICS (9702) — IDs 186-210 ====================
            # ---------- Circular Motion ----------
            {
                "id": 186,
                "subject": "physics",
                "category": "Circular Motion",
                "name": "Angular Velocity",
                "latex": r"\omega = 2\pi f",
                "description": "Angular velocity is the rate of change of angle, equal to 2 pi times the frequency of rotation. Measured in radians per second.",
                "grade_levels": ["a2-level"],
                "keywords": ["angular velocity", "frequency", "rotation", "radian", "circular motion", "omega"],
                "related_ids": [146, 187, 188],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 187,
                "subject": "physics",
                "category": "Circular Motion",
                "name": "Centripetal Acceleration",
                "latex": r"a = \frac{v^2}{r} = \omega^2 r",
                "description": "Centripetal acceleration is directed towards the centre of the circular path and equals the square of the speed divided by the radius.",
                "grade_levels": ["a2-level"],
                "keywords": ["centripetal", "acceleration", "circular", "radius", "velocity", "centre"],
                "related_ids": [186, 188],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 188,
                "subject": "physics",
                "category": "Circular Motion",
                "name": "Centripetal Force",
                "latex": r"F = \frac{mv^2}{r}",
                "description": "The centripetal force is the net inward force required to maintain circular motion, equal to mass times centripetal acceleration.",
                "grade_levels": ["a2-level"],
                "keywords": ["centripetal", "force", "circular motion", "radius", "mass", "velocity"],
                "related_ids": [134, 186, 187],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Gravitational Fields ----------
            {
                "id": 189,
                "subject": "physics",
                "category": "Gravitational Fields",
                "name": "Gravitational Field Strength",
                "latex": r"g = \frac{GM}{r^2}",
                "description": "The gravitational field strength at a distance r from a point mass M is given by Newton's law of gravitation. It decreases with the square of the distance.",
                "grade_levels": ["a2-level"],
                "keywords": ["gravitational field", "strength", "mass", "distance", "newton", "inverse square"],
                "related_ids": [22, 135, 190],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 190,
                "subject": "physics",
                "category": "Gravitational Fields",
                "name": "Gravitational Potential",
                "latex": r"\phi = -\frac{GM}{r}",
                "description": "Gravitational potential at a point is the work done per unit mass in bringing a test mass from infinity to that point. It is always negative.",
                "grade_levels": ["a2-level"],
                "keywords": ["gravitational potential", "work", "mass", "infinity", "negative", "field"],
                "related_ids": [189, 191, 192],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 191,
                "subject": "physics",
                "category": "Gravitational Fields",
                "name": "Orbital Speed",
                "latex": r"v = \sqrt{\frac{GM}{r}}",
                "description": "The orbital speed of a satellite is determined by the mass of the central body and the orbital radius. Derived by equating gravitational and centripetal forces.",
                "grade_levels": ["a2-level"],
                "keywords": ["orbital", "speed", "satellite", "gravity", "radius", "circular orbit"],
                "related_ids": [188, 189, 192],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 192,
                "subject": "physics",
                "category": "Gravitational Fields",
                "name": "Escape Velocity and Kepler's Third Law",
                "latex": r"v_e = \sqrt{\frac{2GM}{r}} \quad \text{and} \quad T^2 = \frac{4\pi^2}{GM} r^3",
                "description": "Escape velocity is the minimum speed to leave a gravitational field. Kepler's third law states the square of orbital period is proportional to the cube of orbital radius.",
                "grade_levels": ["a2-level"],
                "keywords": ["escape velocity", "kepler", "orbital period", "gravity", "radius", "satellite"],
                "related_ids": [189, 190, 191],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Electric Fields ----------
            {
                "id": 193,
                "subject": "physics",
                "category": "Electric Fields",
                "name": "Coulomb's Law",
                "latex": r"F = \frac{kQ_1 Q_2}{r^2}",
                "description": "The electrostatic force between two point charges is proportional to the product of the charges and inversely proportional to the square of the distance between them.",
                "grade_levels": ["a2-level"],
                "keywords": ["coulomb", "electrostatic", "force", "charge", "distance", "inverse square"],
                "related_ids": [22, 194, 195],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 194,
                "subject": "physics",
                "category": "Electric Fields",
                "name": "Electric Field Strength",
                "latex": r"E = \frac{F}{Q} = \frac{kQ}{r^2}",
                "description": "Electric field strength is the force per unit positive charge. For a point charge, it follows an inverse square law with distance.",
                "grade_levels": ["a2-level"],
                "keywords": ["electric field", "strength", "charge", "force", "point charge", "inverse square"],
                "related_ids": [193, 195],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 195,
                "subject": "physics",
                "category": "Electric Fields",
                "name": "Uniform Electric Field and Electric Potential",
                "latex": r"E = \frac{V}{d} \quad \text{(uniform)} \quad \text{and} \quad V = \frac{kQ}{r} \quad \text{(point charge)}",
                "description": "In a uniform field between parallel plates, field strength equals voltage over separation. The potential due to a point charge is kQ/r.",
                "grade_levels": ["a2-level"],
                "keywords": ["electric field", "uniform", "voltage", "parallel plates", "electric potential", "point charge"],
                "related_ids": [152, 193, 194],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Capacitance ----------
            {
                "id": 196,
                "subject": "physics",
                "category": "Capacitance",
                "name": "Capacitance",
                "latex": r"C = \frac{Q}{V}",
                "description": "Capacitance is the ratio of charge stored on a capacitor to the potential difference across it. Measured in farads (F).",
                "grade_levels": ["a2-level"],
                "keywords": ["capacitance", "charge", "voltage", "farad", "capacitor", "storage"],
                "related_ids": [197, 198, 199],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 197,
                "subject": "physics",
                "category": "Capacitance",
                "name": "Energy Stored in a Capacitor",
                "latex": r"E = \frac{1}{2}CV^2 = \frac{1}{2}QV",
                "description": "The energy stored in a charged capacitor can be calculated from the capacitance and voltage, or from the charge and voltage.",
                "grade_levels": ["a2-level"],
                "keywords": ["energy", "capacitor", "stored", "voltage", "charge", "joule"],
                "related_ids": [196, 198],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 198,
                "subject": "physics",
                "category": "Capacitance",
                "name": "Parallel Plate Capacitor",
                "latex": r"C = \frac{\varepsilon_0 A}{d}",
                "description": "The capacitance of a parallel plate capacitor depends on the plate area A, plate separation d, and the permittivity of free space.",
                "grade_levels": ["a2-level"],
                "keywords": ["parallel plate", "capacitor", "area", "separation", "permittivity", "dielectric"],
                "related_ids": [196, 195],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 199,
                "subject": "physics",
                "category": "Capacitance",
                "name": "RC Circuit: Time Constant and Exponential Decay",
                "latex": r"\tau = RC, \quad Q = Q_0 e^{-t/RC}",
                "description": "The time constant tau = RC is the time for charge to fall to 1/e of its initial value. During discharge, charge, current, and voltage all decay exponentially.",
                "grade_levels": ["a2-level"],
                "keywords": ["time constant", "RC circuit", "exponential decay", "capacitor", "discharge", "charging"],
                "related_ids": [196, 197, 152],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Magnetic Fields ----------
            {
                "id": 200,
                "subject": "physics",
                "category": "Magnetic Fields",
                "name": "Force on a Current-Carrying Wire",
                "latex": r"F = BIL\sin\theta",
                "description": "The force on a current-carrying conductor in a magnetic field depends on the flux density, current, length, and the angle between the wire and field.",
                "grade_levels": ["a2-level"],
                "keywords": ["force", "magnetic field", "current", "wire", "flux density", "motor effect"],
                "related_ids": [201, 202],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 201,
                "subject": "physics",
                "category": "Magnetic Fields",
                "name": "Force on a Moving Charge",
                "latex": r"F = Bqv\sin\theta",
                "description": "A charged particle moving through a magnetic field experiences a force perpendicular to both its velocity and the field direction.",
                "grade_levels": ["a2-level"],
                "keywords": ["force", "charge", "magnetic field", "velocity", "lorentz", "deflection"],
                "related_ids": [200, 188],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 202,
                "subject": "physics",
                "category": "Magnetic Fields",
                "name": "Magnetic Flux and Faraday's Law",
                "latex": r"\Phi = BA\cos\theta, \quad \varepsilon = -\frac{d\Phi}{dt}",
                "description": "Magnetic flux is the product of flux density, area, and cosine of the angle. Faraday's law states the induced EMF equals the negative rate of change of flux linkage (Lenz's law).",
                "grade_levels": ["a2-level"],
                "keywords": ["magnetic flux", "faraday", "induction", "emf", "lenz", "weber", "electromagnetic"],
                "related_ids": [200, 203],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 203,
                "subject": "physics",
                "category": "Magnetic Fields",
                "name": "Transformer Equation",
                "latex": r"\frac{N_s}{N_p} = \frac{V_s}{V_p}",
                "description": "The ratio of secondary to primary turns in a transformer equals the ratio of secondary to primary voltages. An ideal transformer conserves power.",
                "grade_levels": ["a2-level"],
                "keywords": ["transformer", "turns ratio", "voltage", "primary", "secondary", "induction"],
                "related_ids": [202, 153],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Oscillations ----------
            {
                "id": 204,
                "subject": "physics",
                "category": "Oscillations",
                "name": "Simple Harmonic Motion (Displacement)",
                "latex": r"x = A\sin(\omega t)",
                "description": "The displacement in SHM varies sinusoidally with time, where A is the amplitude and omega is the angular frequency.",
                "grade_levels": ["a2-level"],
                "keywords": ["SHM", "displacement", "amplitude", "angular frequency", "sinusoidal", "oscillation"],
                "related_ids": [186, 205, 206],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 205,
                "subject": "physics",
                "category": "Oscillations",
                "name": "SHM Acceleration Condition",
                "latex": r"a = -\omega^2 x",
                "description": "In SHM the acceleration is proportional to the displacement from equilibrium and directed towards it. This is the defining equation of SHM.",
                "grade_levels": ["a2-level"],
                "keywords": ["SHM", "acceleration", "displacement", "angular frequency", "restoring force"],
                "related_ids": [186, 204, 206],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 206,
                "subject": "physics",
                "category": "Oscillations",
                "name": "Period of Pendulum and Mass-Spring System",
                "latex": r"T = 2\pi\sqrt{\frac{l}{g}} \quad \text{(pendulum)}, \quad T = 2\pi\sqrt{\frac{m}{k}} \quad \text{(spring)}",
                "description": "The period of a simple pendulum depends on length and g; the period of a mass-spring system depends on mass and spring constant. Neither depends on amplitude for small oscillations.",
                "grade_levels": ["a2-level"],
                "keywords": ["pendulum", "spring", "period", "length", "mass", "spring constant", "SHM"],
                "related_ids": [139, 204, 205],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Quantum Physics ----------
            {
                "id": 207,
                "subject": "physics",
                "category": "Quantum Physics",
                "name": "Photon Energy",
                "latex": r"E = hf",
                "description": "The energy of a photon is directly proportional to its frequency, where h is Planck's constant (6.63 x 10^-34 J s).",
                "grade_levels": ["a2-level"],
                "keywords": ["photon", "energy", "frequency", "planck", "quantum", "light"],
                "related_ids": [208, 209],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 208,
                "subject": "physics",
                "category": "Quantum Physics",
                "name": "Photoelectric Equation and de Broglie Wavelength",
                "latex": r"hf = \phi + KE_{\max} \quad \text{and} \quad \lambda = \frac{h}{p} = \frac{h}{mv}",
                "description": "The photoelectric equation relates photon energy to the work function and maximum kinetic energy of emitted electrons. De Broglie's relation gives the wavelength associated with a particle of momentum p.",
                "grade_levels": ["a2-level"],
                "keywords": ["photoelectric", "work function", "de broglie", "wavelength", "momentum", "wave-particle duality"],
                "related_ids": [167, 207, 160],
                "curriculum": ["cambridge-a2"],
            },
            # ---------- Nuclear Physics ----------
            {
                "id": 209,
                "subject": "physics",
                "category": "Nuclear Physics",
                "name": "Mass-Energy Equivalence",
                "latex": r"E = mc^2",
                "description": "Einstein's mass-energy equivalence shows that mass and energy are interchangeable. A small mass defect releases enormous energy in nuclear reactions.",
                "grade_levels": ["a2-level"],
                "keywords": ["mass-energy", "einstein", "nuclear", "speed of light", "equivalence", "binding"],
                "related_ids": [160, 210],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 210,
                "subject": "physics",
                "category": "Nuclear Physics",
                "name": "Radioactive Decay Law and Half-Life",
                "latex": r"N = N_0 e^{-\lambda t}, \quad t_{1/2} = \frac{\ln 2}{\lambda}, \quad B = \frac{\Delta m \cdot c^2}{A}",
                "description": "Undecayed nuclei decrease exponentially with decay constant lambda. Half-life relates to the decay constant by ln2/lambda. Binding energy per nucleon is the total binding energy divided by mass number A.",
                "grade_levels": ["a2-level"],
                "keywords": ["radioactive", "decay", "half-life", "decay constant", "binding energy", "nucleon", "exponential"],
                "related_ids": [160, 209],
                "curriculum": ["cambridge-a2"],
            },
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM formulas WHERE id >= 131 AND id <= 210")
