"""Seed Cambridge Chemistry formulas

Revision ID: 009_seed_cambridge_chemistry
Revises: 008_seed_cambridge_physics
Create Date: 2026-03-03
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "009_seed_cambridge_chemistry"
down_revision: Union[str, None] = "008_seed_cambridge_physics"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    formulas_table = sa.table(
        "formulas",
        sa.column("id", sa.BigInteger),
        sa.column("subject", sa.String),
        sa.column("category", sa.String),
        sa.column("name", sa.String),
        sa.column("latex", sa.Text),
        sa.column("description", sa.Text),
        sa.column("grade_levels", postgresql.ARRAY(sa.String)),
        sa.column("keywords", postgresql.ARRAY(sa.String)),
        sa.column("related_ids", postgresql.ARRAY(sa.BigInteger)),
        sa.column("curriculum", postgresql.ARRAY(sa.String)),
    )

    op.bulk_insert(
        formulas_table,
        [
            # ============================================================
            # IGCSE Chemistry (0620) — IDs 211-230
            # ============================================================
            {
                "id": 211,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Number of Moles from Mass",
                "latex": r"n = \frac{m}{M_r}",
                "description": "Calculates the number of moles (n) by dividing the mass of a substance (m) by its relative formula mass (Mr). This is the most fundamental mole calculation in chemistry.",
                "grade_levels": ["igcse"],
                "keywords": ["moles", "mass", "relative formula mass", "amount of substance", "stoichiometry", "Mr"],
                "related_ids": [212, 214, 28],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 212,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Mass from Moles",
                "latex": r"m = n \times M_r",
                "description": "Calculates the mass of a substance by multiplying the number of moles by its relative formula mass. Used to determine how much product forms or reactant is needed.",
                "grade_levels": ["igcse"],
                "keywords": ["mass", "moles", "relative formula mass", "stoichiometry", "calculation", "Mr"],
                "related_ids": [211, 213, 28],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 213,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Molar Gas Volume at RTP",
                "latex": r"n = \frac{V}{24 \text{ dm}^3}",
                "description": "At room temperature and pressure (RTP, 25 degrees C and 1 atm), one mole of any gas occupies 24 dm cubed. Used to convert between gas volume and moles.",
                "grade_levels": ["igcse"],
                "keywords": ["gas volume", "molar volume", "RTP", "moles", "24 dm3", "room temperature"],
                "related_ids": [211, 232, 23],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 214,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Concentration from Moles and Volume",
                "latex": r"c = \frac{n}{V}",
                "description": "Concentration (in mol/dm cubed) equals the number of moles of solute divided by the volume of solution in dm cubed. Essential for solution chemistry calculations.",
                "grade_levels": ["igcse"],
                "keywords": ["concentration", "molarity", "moles", "volume", "solution", "mol/dm3"],
                "related_ids": [211, 25, 215],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 215,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Relative Formula Mass",
                "latex": r"M_r = \sum A_r \text{ of all atoms in the formula}",
                "description": "The relative formula mass is the sum of the relative atomic masses of all atoms in a chemical formula. It is dimensionless and taken from the periodic table.",
                "grade_levels": ["igcse"],
                "keywords": ["relative formula mass", "Mr", "relative atomic mass", "Ar", "periodic table", "molecular mass"],
                "related_ids": [211, 212, 216],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 216,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Percentage Composition by Mass",
                "latex": r"\text{Percentage of element} = \frac{A_r \times \text{number of atoms}}{M_r} \times 100\%",
                "description": "Calculates the mass percentage of each element in a compound using relative atomic masses and the relative formula mass.",
                "grade_levels": ["igcse"],
                "keywords": ["percentage composition", "mass percent", "element", "Ar", "Mr", "compound"],
                "related_ids": [215, 217, 211],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 217,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Empirical Formula Calculation",
                "latex": r"\text{Empirical formula: divide each mole ratio by the smallest}",
                "description": "The empirical formula is found by converting mass percentages to moles, then dividing each value by the smallest mole value to get the simplest whole-number ratio of atoms.",
                "grade_levels": ["igcse"],
                "keywords": ["empirical formula", "simplest ratio", "moles", "composition", "molecular formula", "stoichiometry"],
                "related_ids": [216, 211, 215],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 218,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Percentage Yield",
                "latex": r"\text{Percentage yield} = \frac{\text{actual yield}}{\text{theoretical yield}} \times 100\%",
                "description": "Compares the actual mass of product obtained to the maximum theoretical mass predicted by stoichiometry. A yield below 100% indicates losses during the reaction or purification.",
                "grade_levels": ["igcse"],
                "keywords": ["percentage yield", "actual yield", "theoretical yield", "efficiency", "stoichiometry", "loss"],
                "related_ids": [219, 212, 211],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 219,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Percentage Purity",
                "latex": r"\text{Percentage purity} = \frac{\text{mass of pure substance}}{\text{mass of impure sample}} \times 100\%",
                "description": "Measures how pure a sample is by comparing the mass of the desired substance to the total mass of the sample including impurities.",
                "grade_levels": ["igcse"],
                "keywords": ["percentage purity", "impurities", "pure substance", "sample", "stoichiometry", "analysis"],
                "related_ids": [218, 212, 211],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 220,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Atom Economy",
                "latex": r"\text{Atom economy} = \frac{M_r \text{ of desired product}}{\sum M_r \text{ of all products}} \times 100\%",
                "description": "Measures the efficiency of a reaction by comparing the formula mass of the desired product to the total formula mass of all products. Higher atom economy means less waste.",
                "grade_levels": ["igcse"],
                "keywords": ["atom economy", "green chemistry", "efficiency", "waste", "desired product", "sustainability"],
                "related_ids": [218, 215, 211],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 221,
                "subject": "chemistry",
                "category": "Electrochemistry",
                "name": "Charge in Electrolysis",
                "latex": r"Q = I \times t",
                "description": "The total electric charge (in coulombs) passed during electrolysis equals the current (in amps) multiplied by the time (in seconds). Fundamental to quantitative electrolysis.",
                "grade_levels": ["igcse"],
                "keywords": ["charge", "current", "time", "electrolysis", "coulombs", "electricity"],
                "related_ids": [222, 16, 244],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 222,
                "subject": "chemistry",
                "category": "Electrochemistry",
                "name": "Faraday's Law Mass Calculation",
                "latex": r"m = \frac{Q \times A_r}{z \times F}",
                "description": "Calculates the mass of substance deposited or liberated during electrolysis, where Q is charge, Ar is relative atomic mass, z is the number of electrons transferred per ion, and F is the Faraday constant (96500 C/mol).",
                "grade_levels": ["igcse"],
                "keywords": ["Faraday", "electrolysis", "mass", "charge", "deposition", "Faraday constant"],
                "related_ids": [221, 211, 28],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 223,
                "subject": "chemistry",
                "category": "Chemical Energetics",
                "name": "Energy Change from Bond Energies",
                "latex": r"\Delta H = \sum E(\text{bonds broken}) - \sum E(\text{bonds formed})",
                "description": "The overall energy change of a reaction equals the total energy required to break bonds in the reactants minus the total energy released when new bonds form in the products.",
                "grade_levels": ["igcse"],
                "keywords": ["bond energy", "enthalpy", "exothermic", "endothermic", "energy change", "bonds"],
                "related_ids": [30, 236, 224],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 224,
                "subject": "chemistry",
                "category": "Chemical Energetics",
                "name": "Exothermic and Endothermic Sign Convention",
                "latex": r"\text{Exothermic: } \Delta H < 0 \quad;\quad \text{Endothermic: } \Delta H > 0",
                "description": "In exothermic reactions, energy is released to the surroundings and enthalpy change is negative. In endothermic reactions, energy is absorbed from the surroundings and enthalpy change is positive.",
                "grade_levels": ["igcse"],
                "keywords": ["exothermic", "endothermic", "enthalpy", "energy transfer", "sign convention", "delta H"],
                "related_ids": [223, 30, 236],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 225,
                "subject": "chemistry",
                "category": "Rates of Reaction",
                "name": "Rate of Reaction (IGCSE)",
                "latex": r"\text{Rate} = \frac{\text{change in quantity of reactant or product}}{\text{time taken}}",
                "description": "The rate of a chemical reaction measures how quickly reactants are consumed or products are formed, expressed as the change in a measurable quantity divided by the time interval.",
                "grade_levels": ["igcse"],
                "keywords": ["rate", "reaction", "time", "speed", "quantity", "measurement"],
                "related_ids": [29, 241, 242],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 226,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Concentration in g/dm cubed",
                "latex": r"c \;(\text{g/dm}^3) = c \;(\text{mol/dm}^3) \times M_r",
                "description": "Converts between concentration in grams per dm cubed and moles per dm cubed by multiplying or dividing by the relative formula mass.",
                "grade_levels": ["igcse"],
                "keywords": ["concentration", "grams per dm3", "mol per dm3", "conversion", "Mr", "solution"],
                "related_ids": [214, 215, 25],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 227,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Water of Crystallisation",
                "latex": r"\text{Moles of water} = \frac{\text{mass loss on heating}}{18}",
                "description": "Determines the number of moles of water of crystallisation in a hydrated salt by dividing the mass lost upon heating by the molar mass of water (18 g/mol).",
                "grade_levels": ["igcse"],
                "keywords": ["hydrated", "anhydrous", "water of crystallisation", "heating", "mass loss", "moles"],
                "related_ids": [211, 215, 212],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 228,
                "subject": "chemistry",
                "category": "Stoichiometry",
                "name": "Moles from Solution Volume and Concentration",
                "latex": r"n = c \times V",
                "description": "Calculates the number of moles of solute in a solution by multiplying the concentration (mol/dm cubed) by the volume (in dm cubed). Remember to convert cm cubed to dm cubed by dividing by 1000.",
                "grade_levels": ["igcse"],
                "keywords": ["moles", "concentration", "volume", "solution", "titration", "calculation"],
                "related_ids": [214, 211, 25],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 229,
                "subject": "chemistry",
                "category": "Electrochemistry",
                "name": "Number of Moles of Electrons",
                "latex": r"n_e = \frac{Q}{F} = \frac{I \times t}{96500}",
                "description": "Calculates the number of moles of electrons transferred during electrolysis using the total charge and the Faraday constant (96500 C/mol).",
                "grade_levels": ["igcse"],
                "keywords": ["moles of electrons", "Faraday constant", "electrolysis", "charge", "current", "time"],
                "related_ids": [221, 222, 28],
                "curriculum": ["cambridge-igcse"],
            },
            {
                "id": 230,
                "subject": "chemistry",
                "category": "Chemical Energetics",
                "name": "Energy Change from Temperature Rise",
                "latex": r"q = mc\Delta T",
                "description": "Calculates the heat energy change in a solution using the mass of solution (m), specific heat capacity (c, usually 4.18 J/g/K for water), and the temperature change (delta T).",
                "grade_levels": ["igcse"],
                "keywords": ["heat energy", "temperature change", "specific heat capacity", "calorimetry", "q=mcT", "enthalpy"],
                "related_ids": [223, 224, 30],
                "curriculum": ["cambridge-igcse"],
            },
            # ============================================================
            # AS Chemistry (9701) — IDs 231-250
            # ============================================================
            {
                "id": 231,
                "subject": "chemistry",
                "category": "Amount of Substance",
                "name": "Ideal Gas Equation",
                "latex": r"PV = nRT",
                "description": "Relates the pressure (P, in Pa), volume (V, in m cubed), number of moles (n), gas constant (R = 8.314 J/mol/K), and temperature (T, in K) of an ideal gas.",
                "grade_levels": ["as-level", "a2-level"],
                "keywords": ["ideal gas", "pressure", "volume", "temperature", "gas constant", "PV=nRT"],
                "related_ids": [23, 213, 232],
                "curriculum": ["cambridge-as", "cambridge-a2"],
            },
            {
                "id": 232,
                "subject": "chemistry",
                "category": "Amount of Substance",
                "name": "Molar Gas Volume at STP",
                "latex": r"V_m = 22.4 \text{ dm}^3 \text{ mol}^{-1} \;\text{(STP)}\quad;\quad V_m = 24.0 \text{ dm}^3 \text{ mol}^{-1} \;\text{(RTP)}",
                "description": "At standard temperature and pressure (0 degrees C, 1 atm) one mole of gas occupies 22.4 dm cubed; at room temperature and pressure (25 degrees C, 1 atm) it occupies 24.0 dm cubed.",
                "grade_levels": ["as-level"],
                "keywords": ["molar volume", "STP", "RTP", "22.4", "24.0", "gas volume", "moles"],
                "related_ids": [213, 231, 211],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 233,
                "subject": "chemistry",
                "category": "Amount of Substance",
                "name": "Concentration from Titration",
                "latex": r"c_A = \frac{n_A}{V_A} = \frac{c_B \times V_B \times \text{ratio}_A}{V_A \times \text{ratio}_B}",
                "description": "Determines the unknown concentration of an analyte from titration data using the known concentration and volume of the titrant and the stoichiometric mole ratio from the balanced equation.",
                "grade_levels": ["as-level"],
                "keywords": ["titration", "concentration", "analyte", "titrant", "mole ratio", "volumetric analysis"],
                "related_ids": [214, 228, 211],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 234,
                "subject": "chemistry",
                "category": "Amount of Substance",
                "name": "Back Titration Calculation",
                "latex": r"n_{\text{analyte}} = n_{\text{added}} - n_{\text{excess}}",
                "description": "In back titration, an excess of reagent is added to the analyte and the unreacted excess is titrated. The moles of analyte equal the initial moles added minus the moles of excess found by titration.",
                "grade_levels": ["as-level"],
                "keywords": ["back titration", "excess", "analyte", "indirect titration", "moles", "calculation"],
                "related_ids": [233, 214, 211],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 235,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Standard Enthalpy Change from Formation Enthalpies",
                "latex": r"\Delta H^{\circ}_{\text{rxn}} = \sum \Delta H^{\circ}_f (\text{products}) - \sum \Delta H^{\circ}_f (\text{reactants})",
                "description": "The standard enthalpy change of a reaction equals the sum of the standard enthalpies of formation of the products minus the sum of the standard enthalpies of formation of the reactants.",
                "grade_levels": ["as-level", "a2-level"],
                "keywords": ["enthalpy of formation", "Hess's law", "standard enthalpy", "reaction enthalpy", "thermochemistry", "products minus reactants"],
                "related_ids": [30, 236, 223],
                "curriculum": ["cambridge-as", "cambridge-a2"],
            },
            {
                "id": 236,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Hess's Law Cycle",
                "latex": r"\Delta H_1 = \Delta H_2 + \Delta H_3",
                "description": "Hess's law states that the total enthalpy change for a reaction is independent of the route taken. An energy cycle with alternative pathways allows calculation of unknown enthalpy changes.",
                "grade_levels": ["as-level"],
                "keywords": ["Hess's law", "energy cycle", "enthalpy", "route", "indirect", "thermochemistry"],
                "related_ids": [235, 30, 237],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 237,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Bond Enthalpy Calculation",
                "latex": r"\Delta H = \sum \text{(bond enthalpies of bonds broken)} - \sum \text{(bond enthalpies of bonds formed)}",
                "description": "Estimates the enthalpy change of a gaseous reaction from average bond enthalpies. Energy is required to break bonds (endothermic) and released when bonds form (exothermic).",
                "grade_levels": ["as-level"],
                "keywords": ["bond enthalpy", "bond energy", "bonds broken", "bonds formed", "gaseous reaction", "estimation"],
                "related_ids": [223, 235, 238],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 238,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Mean Bond Enthalpy",
                "latex": r"\bar{E}(\text{bond}) = \frac{\sum \Delta H \text{ for breaking that bond type across many molecules}}{\text{number of bonds}}",
                "description": "The mean bond enthalpy is an average value for the energy needed to break a particular type of bond across different molecular environments. It provides an estimate, not an exact value.",
                "grade_levels": ["as-level"],
                "keywords": ["mean bond enthalpy", "average", "bond dissociation", "estimation", "gaseous", "approximation"],
                "related_ids": [237, 223, 235],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 239,
                "subject": "chemistry",
                "category": "Chemical Equilibrium",
                "name": "Equilibrium Constant Kc",
                "latex": r"K_c = \frac{[C]^c [D]^d}{[A]^a [B]^b} \quad \text{for } aA + bB \rightleftharpoons cC + dD",
                "description": "The equilibrium constant Kc is the ratio of the product concentrations raised to their stoichiometric powers divided by the reactant concentrations raised to their powers, all at equilibrium.",
                "grade_levels": ["as-level", "a2-level"],
                "keywords": ["equilibrium constant", "Kc", "concentration", "products", "reactants", "stoichiometry"],
                "related_ids": [240, 255, 214],
                "curriculum": ["cambridge-as", "cambridge-a2"],
            },
            {
                "id": 240,
                "subject": "chemistry",
                "category": "Chemical Equilibrium",
                "name": "Kc and Equilibrium Position",
                "latex": r"K_c \gg 1 \;\Rightarrow\; \text{products favoured}\quad;\quad K_c \ll 1 \;\Rightarrow\; \text{reactants favoured}",
                "description": "A large Kc indicates the equilibrium lies to the right (products favoured), while a small Kc indicates it lies to the left (reactants favoured). Kc changes only with temperature.",
                "grade_levels": ["as-level"],
                "keywords": ["equilibrium position", "Kc", "products favoured", "reactants favoured", "temperature", "Le Chatelier"],
                "related_ids": [239, 255, 256],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 241,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Rate Equation",
                "latex": r"\text{rate} = k[A]^m[B]^n",
                "description": "The rate equation expresses the rate of reaction in terms of the rate constant (k) and the concentrations of reactants raised to their respective orders (m and n), which are determined experimentally.",
                "grade_levels": ["as-level", "a2-level"],
                "keywords": ["rate equation", "rate constant", "order", "concentration", "kinetics", "experimentally determined"],
                "related_ids": [29, 242, 243],
                "curriculum": ["cambridge-as", "cambridge-a2"],
            },
            {
                "id": 242,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Order of Reaction from Rate Data",
                "latex": r"\text{If doubling } [A] \text{ doubles rate} \Rightarrow \text{first order in } A \;;\; \text{quadruples rate} \Rightarrow \text{second order}",
                "description": "The order of reaction with respect to a reactant is determined by observing how the rate changes when the concentration of that reactant is changed while others are held constant.",
                "grade_levels": ["as-level"],
                "keywords": ["order of reaction", "rate data", "first order", "second order", "zero order", "initial rates"],
                "related_ids": [241, 243, 29],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 243,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Half-life of First Order Reaction",
                "latex": r"t_{1/2} = \frac{\ln 2}{k} = \frac{0.693}{k}",
                "description": "For a first-order reaction, the half-life is constant and independent of the initial concentration. It equals the natural log of 2 divided by the rate constant k.",
                "grade_levels": ["as-level", "a2-level"],
                "keywords": ["half-life", "first order", "rate constant", "ln 2", "constant half-life", "decay"],
                "related_ids": [241, 242, 267],
                "curriculum": ["cambridge-as", "cambridge-a2"],
            },
            {
                "id": 244,
                "subject": "chemistry",
                "category": "Electrochemistry",
                "name": "Standard Cell EMF",
                "latex": r"E^{\circ}_{\text{cell}} = E^{\circ}_{\text{cathode}} - E^{\circ}_{\text{anode}}",
                "description": "The standard electromotive force of an electrochemical cell equals the standard electrode potential of the cathode (reduction) minus the standard electrode potential of the anode (oxidation).",
                "grade_levels": ["as-level", "a2-level"],
                "keywords": ["standard cell EMF", "electrode potential", "cathode", "anode", "electrochemistry", "voltage"],
                "related_ids": [221, 245, 269],
                "curriculum": ["cambridge-as", "cambridge-a2"],
            },
            {
                "id": 245,
                "subject": "chemistry",
                "category": "Electrochemistry",
                "name": "Oxidation Number Rules",
                "latex": r"\text{Ox. no. of element} = 0\;;\; \text{sum in compound} = 0\;;\; \text{sum in ion} = \text{charge}",
                "description": "Oxidation numbers follow set rules: elements in their standard state have oxidation number 0, the sum of oxidation numbers in a neutral compound is 0, and in a polyatomic ion it equals the ion charge.",
                "grade_levels": ["as-level"],
                "keywords": ["oxidation number", "oxidation state", "redox", "rules", "compound", "ion charge"],
                "related_ids": [244, 221, 222],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 246,
                "subject": "chemistry",
                "category": "Organic Chemistry",
                "name": "Index of Hydrogen Deficiency (IHD)",
                "latex": r"\text{IHD} = \frac{2C + 2 + N - H - X}{2}",
                "description": "The degree of unsaturation (IHD) calculates the number of rings plus double bonds in a molecule, where C is carbons, H is hydrogens, N is nitrogens, and X is halogens.",
                "grade_levels": ["as-level", "a2-level"],
                "keywords": ["degree of unsaturation", "IHD", "double bond", "ring", "molecular formula", "organic"],
                "related_ids": [217, 215, 211],
                "curriculum": ["cambridge-as", "cambridge-a2"],
            },
            {
                "id": 247,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Enthalpy Change from Combustion Data",
                "latex": r"\Delta H^{\circ}_{\text{rxn}} = \sum \Delta H^{\circ}_c (\text{reactants}) - \sum \Delta H^{\circ}_c (\text{products})",
                "description": "Using Hess's law with combustion data, the reaction enthalpy equals the sum of combustion enthalpies of reactants minus the sum of combustion enthalpies of products (note the reversed sign compared to formation data).",
                "grade_levels": ["as-level"],
                "keywords": ["enthalpy of combustion", "Hess's law", "combustion data", "energy cycle", "thermochemistry", "calculation"],
                "related_ids": [235, 236, 30],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 248,
                "subject": "chemistry",
                "category": "Amount of Substance",
                "name": "Moles from Gas Volume (Ideal Gas)",
                "latex": r"n = \frac{PV}{RT}",
                "description": "Rearrangement of the ideal gas equation to find the number of moles of a gas from measured pressure, volume, and temperature. Ensure SI units: Pa, m cubed, and K.",
                "grade_levels": ["as-level"],
                "keywords": ["moles", "ideal gas", "pressure", "volume", "temperature", "calculation"],
                "related_ids": [231, 213, 211],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 249,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Overall Order of Reaction",
                "latex": r"\text{Overall order} = m + n \quad \text{for rate} = k[A]^m[B]^n",
                "description": "The overall order of a reaction is the sum of the individual orders with respect to each reactant in the rate equation. It determines the units of the rate constant k.",
                "grade_levels": ["as-level"],
                "keywords": ["overall order", "rate equation", "sum of orders", "rate constant units", "kinetics", "reaction order"],
                "related_ids": [241, 242, 243],
                "curriculum": ["cambridge-as"],
            },
            {
                "id": 250,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Enthalpy of Neutralisation",
                "latex": r"\Delta H_{\text{neut}} = \frac{q}{n} = \frac{mc\Delta T}{n_{\text{water formed}}}",
                "description": "The enthalpy of neutralisation is the enthalpy change per mole of water formed when an acid reacts with a base. Calculated from calorimetry data using q=mcDeltaT divided by moles of water.",
                "grade_levels": ["as-level"],
                "keywords": ["neutralisation", "enthalpy", "acid", "base", "calorimetry", "water formed"],
                "related_ids": [230, 235, 214],
                "curriculum": ["cambridge-as"],
            },
            # ============================================================
            # A2 Chemistry (9701) — IDs 251-270
            # ============================================================
            {
                "id": 251,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Lattice Energy (Born-Haber Cycle)",
                "latex": r"\Delta H^{\circ}_{\text{latt}} = \Delta H^{\circ}_{\text{f}} - \Delta H^{\circ}_{\text{at}} - \Delta H^{\circ}_{\text{IE}} - \Delta H^{\circ}_{\text{at}} - \Delta H^{\circ}_{\text{EA}}",
                "description": "Lattice energy is calculated using a Born-Haber cycle that combines formation enthalpy, atomisation enthalpies, ionisation energies, and electron affinities according to Hess's law.",
                "grade_levels": ["a2-level"],
                "keywords": ["lattice energy", "Born-Haber cycle", "formation enthalpy", "ionisation energy", "Hess's law", "ionic bonding"],
                "related_ids": [236, 252, 235],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 252,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Electron Affinity",
                "latex": r"X(g) + e^- \rightarrow X^-(g) \quad \Delta H^{\circ}_{\text{EA}}",
                "description": "Electron affinity is the enthalpy change when one mole of electrons is added to one mole of gaseous atoms to form one mole of gaseous anions. First electron affinity is usually exothermic.",
                "grade_levels": ["a2-level"],
                "keywords": ["electron affinity", "enthalpy", "gaseous", "anion", "exothermic", "Born-Haber"],
                "related_ids": [251, 253, 236],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 253,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Enthalpy of Hydration",
                "latex": r"M^{z+}(g) + \text{aq} \rightarrow M^{z+}(aq) \quad \Delta H^{\circ}_{\text{hyd}}",
                "description": "The enthalpy of hydration is the enthalpy change when one mole of gaseous ions is dissolved in sufficient water to form an infinitely dilute solution. It is always exothermic.",
                "grade_levels": ["a2-level"],
                "keywords": ["enthalpy of hydration", "gaseous ions", "aqueous", "dissolving", "exothermic", "lattice energy"],
                "related_ids": [251, 254, 252],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 254,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Entropy Change of Reaction",
                "latex": r"\Delta S^{\circ} = \sum S^{\circ}(\text{products}) - \sum S^{\circ}(\text{reactants})",
                "description": "The standard entropy change of a reaction is the sum of the standard molar entropies of the products minus the sum of the standard molar entropies of the reactants.",
                "grade_levels": ["a2-level"],
                "keywords": ["entropy", "disorder", "standard entropy", "products", "reactants", "thermodynamics"],
                "related_ids": [255, 235, 30],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 255,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Gibbs Free Energy",
                "latex": r"\Delta G = \Delta H - T\Delta S",
                "description": "Gibbs free energy combines enthalpy and entropy to predict reaction feasibility. A reaction is thermodynamically feasible (spontaneous) when delta G is negative.",
                "grade_levels": ["a2-level"],
                "keywords": ["Gibbs free energy", "spontaneity", "feasibility", "enthalpy", "entropy", "temperature"],
                "related_ids": [254, 256, 235],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 256,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Spontaneity Condition",
                "latex": r"\Delta G < 0 \;\Rightarrow\; \text{reaction is feasible (spontaneous)}",
                "description": "A reaction is thermodynamically spontaneous when delta G is negative. This can occur when delta H is sufficiently negative (exothermic) or T delta S is sufficiently positive (entropy increase at high temperature).",
                "grade_levels": ["a2-level"],
                "keywords": ["spontaneous", "feasible", "Gibbs", "delta G negative", "thermodynamics", "feasibility condition"],
                "related_ids": [255, 254, 235],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 257,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Equilibrium Constant Kp",
                "latex": r"K_p = \frac{p_C^{\,c} \; p_D^{\,d}}{p_A^{\,a} \; p_B^{\,b}}",
                "description": "The equilibrium constant Kp is expressed in terms of partial pressures for gaseous equilibria. Each partial pressure is raised to the power of its stoichiometric coefficient.",
                "grade_levels": ["a2-level"],
                "keywords": ["Kp", "partial pressure", "equilibrium constant", "gaseous", "stoichiometry", "equilibrium"],
                "related_ids": [239, 258, 231],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 258,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Partial Pressure",
                "latex": r"p_A = x_A \times P_{\text{total}}",
                "description": "The partial pressure of a gas in a mixture equals its mole fraction (x) multiplied by the total pressure. The sum of all partial pressures equals the total pressure (Dalton's law).",
                "grade_levels": ["a2-level"],
                "keywords": ["partial pressure", "mole fraction", "total pressure", "Dalton's law", "gas mixture", "equilibrium"],
                "related_ids": [257, 231, 239],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 259,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Ionic Product of Water",
                "latex": r"K_w = [H^+][OH^-] = 1.0 \times 10^{-14} \;\text{mol}^2\text{dm}^{-6} \;\text{at 25°C}",
                "description": "The ionic product of water is the product of hydrogen ion and hydroxide ion concentrations. At 25 degrees C it equals 10 to the power of negative 14. It increases with temperature.",
                "grade_levels": ["a2-level"],
                "keywords": ["ionic product", "Kw", "water", "hydrogen ion", "hydroxide ion", "autoionisation"],
                "related_ids": [260, 261, 26],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 260,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Acid Dissociation Constant Ka",
                "latex": r"K_a = \frac{[H^+][A^-]}{[HA]}",
                "description": "The acid dissociation constant Ka measures the strength of a weak acid. A larger Ka indicates a stronger acid with greater degree of dissociation in aqueous solution.",
                "grade_levels": ["a2-level"],
                "keywords": ["Ka", "acid dissociation", "weak acid", "equilibrium", "dissociation constant", "acid strength"],
                "related_ids": [261, 259, 26],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 261,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Base Dissociation Constant Kb",
                "latex": r"K_b = \frac{[BH^+][OH^-]}{[B]}",
                "description": "The base dissociation constant Kb measures the strength of a weak base. It is related to Ka through the ionic product of water: Ka times Kb equals Kw.",
                "grade_levels": ["a2-level"],
                "keywords": ["Kb", "base dissociation", "weak base", "equilibrium", "dissociation constant", "base strength"],
                "related_ids": [260, 259, 26],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 262,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "pH Calculation",
                "latex": r"pH = -\log_{10}[H^+]",
                "description": "The pH of a solution is the negative base-10 logarithm of the hydrogen ion concentration. Lower pH means more acidic; pH 7 is neutral at 25 degrees C.",
                "grade_levels": ["a2-level"],
                "keywords": ["pH", "hydrogen ion", "logarithm", "acidity", "concentration", "scale"],
                "related_ids": [26, 263, 260],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 263,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "pOH and Relationship to pH",
                "latex": r"pOH = -\log_{10}[OH^-] \quad;\quad pH + pOH = 14 \;\text{at 25°C}",
                "description": "pOH is the negative base-10 logarithm of the hydroxide ion concentration. At 25 degrees C, pH and pOH always sum to 14 due to the ionic product of water.",
                "grade_levels": ["a2-level"],
                "keywords": ["pOH", "hydroxide ion", "pH", "relationship", "14", "water"],
                "related_ids": [262, 259, 26],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 264,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Henderson-Hasselbalch Equation",
                "latex": r"pH = pK_a + \log_{10}\frac{[A^-]}{[HA]}",
                "description": "Calculates the pH of a buffer solution from the pKa of the weak acid and the ratio of conjugate base concentration to weak acid concentration. Essential for buffer calculations.",
                "grade_levels": ["a2-level"],
                "keywords": ["Henderson-Hasselbalch", "buffer", "pKa", "conjugate base", "weak acid", "buffer pH"],
                "related_ids": [260, 262, 259],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 265,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Solubility Product Ksp",
                "latex": r"K_{sp} = [M^{a+}]^m [X^{b-}]^n \quad \text{for } M_m X_n",
                "description": "The solubility product is the equilibrium constant for a sparingly soluble ionic compound dissolving in water. It equals the product of the ion concentrations each raised to their stoichiometric powers.",
                "grade_levels": ["a2-level"],
                "keywords": ["solubility product", "Ksp", "sparingly soluble", "ionic compound", "precipitation", "equilibrium"],
                "related_ids": [239, 260, 259],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 266,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Arrhenius Equation",
                "latex": r"k = A e^{-\frac{E_a}{RT}}",
                "description": "Relates the rate constant (k) to the activation energy (Ea), temperature (T), gas constant (R), and the pre-exponential factor (A). Shows that rate constant increases exponentially with temperature.",
                "grade_levels": ["a2-level"],
                "keywords": ["Arrhenius", "activation energy", "rate constant", "temperature", "exponential", "pre-exponential factor"],
                "related_ids": [241, 267, 243],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 267,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Determining Ea from Graph (ln k vs 1/T)",
                "latex": r"\ln k = \ln A - \frac{E_a}{R} \times \frac{1}{T} \quad;\quad \text{gradient} = -\frac{E_a}{R}",
                "description": "Plotting ln k against 1/T gives a straight line with gradient equal to negative Ea/R. The activation energy is calculated from the gradient multiplied by negative R.",
                "grade_levels": ["a2-level"],
                "keywords": ["Arrhenius plot", "ln k", "1/T", "gradient", "activation energy", "graphical method"],
                "related_ids": [266, 241, 243],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 268,
                "subject": "chemistry",
                "category": "Electrochemistry",
                "name": "Nernst Equation",
                "latex": r"E = E^{\circ} - \frac{RT}{zF}\ln Q",
                "description": "The Nernst equation calculates the electrode potential under non-standard conditions using the standard potential, temperature, number of electrons transferred (z), Faraday constant (F), and the reaction quotient (Q).",
                "grade_levels": ["a2-level"],
                "keywords": ["Nernst equation", "electrode potential", "non-standard", "reaction quotient", "Faraday", "electrochemistry"],
                "related_ids": [244, 269, 266],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 269,
                "subject": "chemistry",
                "category": "Electrochemistry",
                "name": "Faraday's Laws of Electrolysis (Quantitative)",
                "latex": r"m = \frac{M_r \times I \times t}{z \times F}",
                "description": "Quantitative form of Faraday's law for A2: the mass deposited during electrolysis equals the molar mass times current times time, divided by the number of electrons transferred per ion times the Faraday constant (96485 C/mol).",
                "grade_levels": ["a2-level"],
                "keywords": ["Faraday's law", "electrolysis", "mass deposited", "current", "molar mass", "quantitative"],
                "related_ids": [222, 221, 268],
                "curriculum": ["cambridge-a2"],
            },
            {
                "id": 270,
                "subject": "chemistry",
                "category": "Energetics",
                "name": "Enthalpy of Solution from Lattice Energy and Hydration",
                "latex": r"\Delta H^{\circ}_{\text{sol}} = -\Delta H^{\circ}_{\text{latt}} + \Delta H^{\circ}_{\text{hyd(cation)}} + \Delta H^{\circ}_{\text{hyd(anion)}}",
                "description": "The standard enthalpy of solution can be calculated using a Hess's law cycle: it equals the negative of the lattice energy plus the sum of the enthalpies of hydration of the individual ions.",
                "grade_levels": ["a2-level"],
                "keywords": ["enthalpy of solution", "lattice energy", "hydration enthalpy", "dissolving", "Hess's law", "Born-Haber"],
                "related_ids": [251, 253, 236],
                "curriculum": ["cambridge-a2"],
            },
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM formulas WHERE id >= 211 AND id <= 270")
