"""Seed NCEA (New Zealand) curriculum Math formulas

Revision ID: 010_seed_ncea_math
Revises: 009_seed_cambridge_chemistry
Create Date: 2026-03-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "010_seed_ncea_math"
down_revision: Union[str, None] = "009_seed_cambridge_chemistry"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    formulas_table = sa.table(
        "formulas",
        sa.column("id", sa.BigInteger),
        sa.column("subject", sa.String),
        sa.column("category", sa.String),
        sa.column("name", sa.String),
        sa.column("latex", sa.Text),
        sa.column("description", sa.Text),
        sa.column("grade_levels", postgresql.ARRAY(sa.String)),
        sa.column("keywords", postgresql.ARRAY(sa.String)),
        sa.column("related_ids", postgresql.ARRAY(sa.BigInteger)),
        sa.column("curriculum", postgresql.ARRAY(sa.String)),
    )

    op.bulk_insert(
        formulas_table,
        [
            # ================================================================
            # NCEA Level 1 (Year 11) — IDs 271-293
            # ================================================================
            # ---------- Number ----------
            {
                "id": 271,
                "subject": "math",
                "category": "Number",
                "name": "Percentage of an Amount",
                "latex": r"\text{Amount} = \frac{p}{100} \times \text{Total}",
                "description": "Calculates a given percentage p of a total quantity. Multiply the total by the percentage expressed as a decimal.",
                "grade_levels": ["ncea-1"],
                "keywords": ["percentage", "amount", "fraction", "proportion", "calculate", "number"],
                "related_ids": [272, 273, 64],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 272,
                "subject": "math",
                "category": "Number",
                "name": "Percentage Increase / Decrease",
                "latex": r"\text{New value} = \text{Original} \times \left(1 \pm \frac{p}{100}\right)",
                "description": "Increases or decreases a value by a given percentage p. Use addition for increase and subtraction for decrease.",
                "grade_levels": ["ncea-1"],
                "keywords": ["percentage", "increase", "decrease", "change", "markup", "discount"],
                "related_ids": [271, 64, 273],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 273,
                "subject": "math",
                "category": "Number",
                "name": "GST Calculation (15%)",
                "latex": r"\text{GST inclusive} = \text{Price} \times 1.15, \quad \text{GST} = \text{Inclusive} - \frac{\text{Inclusive}}{1.15}",
                "description": "New Zealand Goods and Services Tax is 15%. To add GST multiply by 1.15; to find the GST component of an inclusive price divide by 1.15 and subtract.",
                "grade_levels": ["ncea-1"],
                "keywords": ["GST", "tax", "goods and services", "15 percent", "inclusive", "New Zealand"],
                "related_ids": [271, 272, 274],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 274,
                "subject": "math",
                "category": "Number",
                "name": "Simple Interest",
                "latex": r"I = PRT",
                "description": "Calculates simple interest where P is the principal, R is the annual interest rate as a decimal, and T is the time in years. Interest is not compounded.",
                "grade_levels": ["ncea-1"],
                "keywords": ["simple interest", "principal", "rate", "time", "finance", "investment"],
                "related_ids": [275, 273, 65],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 275,
                "subject": "math",
                "category": "Number",
                "name": "Compound Interest",
                "latex": r"A = P(1 + r)^n",
                "description": "Calculates the total amount A after n compounding periods, where P is the principal and r is the interest rate per period as a decimal.",
                "grade_levels": ["ncea-1"],
                "keywords": ["compound interest", "principal", "rate", "exponential growth", "finance", "investment"],
                "related_ids": [274, 65, 271],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 276,
                "subject": "math",
                "category": "Number",
                "name": "Currency Conversion",
                "latex": r"\text{Foreign} = \text{NZD} \times \text{Exchange Rate}",
                "description": "Converts between New Zealand dollars and a foreign currency using the exchange rate. Divide by the rate to convert back to NZD.",
                "grade_levels": ["ncea-1"],
                "keywords": ["currency", "conversion", "exchange rate", "NZD", "foreign", "money"],
                "related_ids": [271, 272, 273],
                "curriculum": ["ncea-1"],
            },
            # ---------- Algebra ----------
            {
                "id": 277,
                "subject": "math",
                "category": "Algebra",
                "name": "Solving Linear Equations",
                "latex": r"ax + b = c \implies x = \frac{c - b}{a}",
                "description": "Solves a linear equation in one variable by isolating x. Subtract b from both sides then divide by a.",
                "grade_levels": ["ncea-1"],
                "keywords": ["linear", "equation", "solve", "variable", "algebra", "one step"],
                "related_ids": [8, 278, 35],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 278,
                "subject": "math",
                "category": "Algebra",
                "name": "Simultaneous Equations (Two Variables)",
                "latex": r"a_1 x + b_1 y = c_1 \quad\text{and}\quad a_2 x + b_2 y = c_2",
                "description": "A system of two linear equations solved by elimination or substitution to find the unique values of x and y that satisfy both equations.",
                "grade_levels": ["ncea-1"],
                "keywords": ["simultaneous", "equations", "elimination", "substitution", "linear", "two variables"],
                "related_ids": [31, 277, 8],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 279,
                "subject": "math",
                "category": "Algebra",
                "name": "Expanding Brackets",
                "latex": r"a(b + c) = ab + ac \quad\text{and}\quad (a+b)(c+d) = ac + ad + bc + bd",
                "description": "Distributes terms by multiplying each term inside the brackets by the term outside (single bracket) or using FOIL for two binomials.",
                "grade_levels": ["ncea-1"],
                "keywords": ["expanding", "brackets", "distributive", "FOIL", "multiply", "algebra"],
                "related_ids": [280, 281, 33],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 280,
                "subject": "math",
                "category": "Algebra",
                "name": "Factoring Quadratics",
                "latex": r"x^2 + bx + c = (x + p)(x + q) \quad\text{where } p + q = b,\; pq = c",
                "description": "Factors a monic quadratic trinomial by finding two numbers that add to b and multiply to c. Essential for solving quadratic equations.",
                "grade_levels": ["ncea-1"],
                "keywords": ["factoring", "factorising", "quadratic", "trinomial", "algebra", "roots"],
                "related_ids": [279, 281, 33],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 281,
                "subject": "math",
                "category": "Algebra",
                "name": "Quadratic Formula",
                "latex": r"x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}",
                "description": "Finds the roots of any quadratic equation ax^2 + bx + c = 0. Works for all quadratics, including those that cannot be factored easily.",
                "grade_levels": ["ncea-1"],
                "keywords": ["quadratic", "formula", "roots", "discriminant", "equation", "solve"],
                "related_ids": [1, 280, 282],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 282,
                "subject": "math",
                "category": "Algebra",
                "name": "Completing the Square",
                "latex": r"x^2 + bx = \left(x + \frac{b}{2}\right)^2 - \left(\frac{b}{2}\right)^2",
                "description": "Rewrites a quadratic expression in perfect-square form. Useful for finding the vertex of a parabola and solving quadratic equations.",
                "grade_levels": ["ncea-1"],
                "keywords": ["completing the square", "quadratic", "vertex", "turning point", "algebra", "parabola"],
                "related_ids": [32, 281, 280],
                "curriculum": ["ncea-1"],
            },
            # ---------- Measurement ----------
            {
                "id": 283,
                "subject": "math",
                "category": "Geometry",
                "name": "Pythagoras' Theorem",
                "latex": r"a^2 + b^2 = c^2",
                "description": "In a right-angled triangle, the square of the hypotenuse c equals the sum of the squares of the other two sides a and b.",
                "grade_levels": ["ncea-1"],
                "keywords": ["Pythagoras", "right triangle", "hypotenuse", "sides", "geometry", "theorem"],
                "related_ids": [2, 284, 4],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 284,
                "subject": "math",
                "category": "Trigonometry",
                "name": "SOH CAH TOA",
                "latex": r"\sin\theta = \frac{O}{H}, \quad \cos\theta = \frac{A}{H}, \quad \tan\theta = \frac{O}{A}",
                "description": "The three basic trigonometric ratios for a right-angled triangle: sine (opposite/hypotenuse), cosine (adjacent/hypotenuse), tangent (opposite/adjacent).",
                "grade_levels": ["ncea-1"],
                "keywords": ["SOH CAH TOA", "sine", "cosine", "tangent", "right triangle", "trigonometry", "ratio"],
                "related_ids": [55, 56, 57, 283],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 285,
                "subject": "math",
                "category": "Geometry",
                "name": "Area of a Triangle",
                "latex": r"A = \frac{1}{2}bh",
                "description": "Calculates the area of a triangle given its base b and perpendicular height h.",
                "grade_levels": ["ncea-1"],
                "keywords": ["area", "triangle", "base", "height", "geometry", "measurement"],
                "related_ids": [7, 286, 283],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 286,
                "subject": "math",
                "category": "Geometry",
                "name": "Area of a Circle",
                "latex": r"A = \pi r^2",
                "description": "Calculates the area enclosed by a circle with radius r. Pi is approximately 3.14159.",
                "grade_levels": ["ncea-1"],
                "keywords": ["area", "circle", "radius", "pi", "geometry", "measurement"],
                "related_ids": [5, 285, 288],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 287,
                "subject": "math",
                "category": "Geometry",
                "name": "Volume of a Prism",
                "latex": r"V = A_{\text{base}} \times h",
                "description": "The volume of any prism equals the area of its uniform cross-section (base) multiplied by its height (length).",
                "grade_levels": ["ncea-1"],
                "keywords": ["volume", "prism", "cross-section", "base area", "height", "3D shape"],
                "related_ids": [288, 46, 289],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 288,
                "subject": "math",
                "category": "Geometry",
                "name": "Volume of a Cylinder",
                "latex": r"V = \pi r^2 h",
                "description": "Calculates the volume of a cylinder with circular base radius r and height h. A cylinder is a prism with a circular cross-section.",
                "grade_levels": ["ncea-1"],
                "keywords": ["volume", "cylinder", "radius", "height", "3D shape", "circular prism"],
                "related_ids": [46, 286, 287],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 289,
                "subject": "math",
                "category": "Geometry",
                "name": "Surface Area (Prisms and Cylinders)",
                "latex": r"SA_{\text{cylinder}} = 2\pi r h + 2\pi r^2",
                "description": "The total surface area of a cylinder includes the curved surface (2*pi*r*h) plus two circular ends. For other prisms, sum the areas of all faces.",
                "grade_levels": ["ncea-1"],
                "keywords": ["surface area", "cylinder", "prism", "faces", "3D shape", "measurement"],
                "related_ids": [50, 288, 287],
                "curriculum": ["ncea-1"],
            },
            # ---------- Statistics ----------
            {
                "id": 290,
                "subject": "math",
                "category": "Statistics",
                "name": "Mean (Average)",
                "latex": r"\bar{x} = \frac{\sum x_i}{n}",
                "description": "The arithmetic mean is the sum of all data values divided by the number of values. A measure of the centre of a data set.",
                "grade_levels": ["ncea-1"],
                "keywords": ["mean", "average", "sum", "data", "statistics", "centre"],
                "related_ids": [291, 61, 292],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 291,
                "subject": "math",
                "category": "Statistics",
                "name": "Median",
                "latex": r"\text{Median} = \text{middle value of ordered data}",
                "description": "The median is the middle value when data is arranged in order. For an even number of values, it is the mean of the two middle values.",
                "grade_levels": ["ncea-1"],
                "keywords": ["median", "middle", "order", "data", "statistics", "centre"],
                "related_ids": [290, 292, 61],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 292,
                "subject": "math",
                "category": "Statistics",
                "name": "Probability of an Event",
                "latex": r"P(\text{event}) = \frac{\text{number of favourable outcomes}}{\text{total number of outcomes}}",
                "description": "The theoretical probability of an event is the ratio of favourable outcomes to the total number of equally likely outcomes.",
                "grade_levels": ["ncea-1"],
                "keywords": ["probability", "event", "outcomes", "favourable", "chance", "likelihood"],
                "related_ids": [62, 290, 293],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 293,
                "subject": "math",
                "category": "Statistics",
                "name": "Relative Frequency",
                "latex": r"\text{Relative frequency} = \frac{\text{frequency of outcome}}{\text{total number of trials}}",
                "description": "An experimental estimate of probability based on repeated trials. As the number of trials increases, relative frequency approaches the theoretical probability.",
                "grade_levels": ["ncea-1"],
                "keywords": ["relative frequency", "experimental", "probability", "trials", "proportion", "statistics"],
                "related_ids": [292, 62, 290],
                "curriculum": ["ncea-1"],
            },
            # ================================================================
            # NCEA Level 2 (Year 12) — IDs 294-318
            # ================================================================
            # ---------- Algebra ----------
            {
                "id": 294,
                "subject": "math",
                "category": "Algebra",
                "name": "Quadratic Formula with Discriminant",
                "latex": r"x = \frac{-b \pm \sqrt{\Delta}}{2a}, \quad \Delta = b^2 - 4ac",
                "description": "Extends the quadratic formula by explicitly identifying the discriminant Delta. If Delta > 0 there are two real roots; Delta = 0 gives one repeated root; Delta < 0 gives no real roots.",
                "grade_levels": ["ncea-2"],
                "keywords": ["quadratic", "discriminant", "roots", "real", "nature", "delta", "formula"],
                "related_ids": [1, 66, 281],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 295,
                "subject": "math",
                "category": "Algebra",
                "name": "Exponential Equations",
                "latex": r"a^x = b \implies x = \frac{\ln b}{\ln a}",
                "description": "Solves exponential equations by taking logarithms of both sides. The unknown exponent is isolated using the logarithm change-of-base property.",
                "grade_levels": ["ncea-2"],
                "keywords": ["exponential", "equation", "logarithm", "solve", "power", "index"],
                "related_ids": [296, 297, 104],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 296,
                "subject": "math",
                "category": "Algebra",
                "name": "Logarithm Definition",
                "latex": r"\log_a b = c \iff a^c = b",
                "description": "The logarithm base a of b is the exponent c to which a must be raised to produce b. Logarithms are the inverse of exponentiation.",
                "grade_levels": ["ncea-2"],
                "keywords": ["logarithm", "definition", "base", "exponent", "inverse", "log"],
                "related_ids": [295, 297, 102],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 297,
                "subject": "math",
                "category": "Algebra",
                "name": "Logarithm Laws",
                "latex": r"\log_a(xy) = \log_a x + \log_a y, \quad \log_a\!\left(\frac{x}{y}\right) = \log_a x - \log_a y, \quad \log_a(x^n) = n\log_a x",
                "description": "The three fundamental log laws: the product rule, quotient rule, and power rule. Used to simplify and solve logarithmic expressions and equations.",
                "grade_levels": ["ncea-2"],
                "keywords": ["logarithm", "laws", "product", "quotient", "power", "rules", "log"],
                "related_ids": [10, 296, 295],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 298,
                "subject": "math",
                "category": "Algebra",
                "name": "Graphing Quadratics — Vertex Form",
                "latex": r"y = a(x - h)^2 + k",
                "description": "The vertex form of a quadratic function with vertex at (h, k). The parameter a controls the width and direction of opening of the parabola.",
                "grade_levels": ["ncea-2"],
                "keywords": ["quadratic", "vertex", "parabola", "graph", "turning point", "transformation"],
                "related_ids": [282, 281, 299],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 299,
                "subject": "math",
                "category": "Algebra",
                "name": "Equation of a Parabola",
                "latex": r"y = ax^2 + bx + c, \quad \text{vertex at } x = -\frac{b}{2a}",
                "description": "The standard form of a parabola with the x-coordinate of the vertex found by -b/(2a). Substitute back to find the y-coordinate of the vertex.",
                "grade_levels": ["ncea-2"],
                "keywords": ["parabola", "equation", "vertex", "axis of symmetry", "quadratic", "graph"],
                "related_ids": [298, 281, 282],
                "curriculum": ["ncea-2"],
            },
            # ---------- Calculus ----------
            {
                "id": 300,
                "subject": "math",
                "category": "Calculus",
                "name": "Derivative — Power Rule",
                "latex": r"\frac{d}{dx}(x^n) = nx^{n-1}",
                "description": "The derivative of x raised to the power n is n times x raised to (n-1). The fundamental rule for differentiating polynomial terms.",
                "grade_levels": ["ncea-2"],
                "keywords": ["derivative", "power rule", "differentiation", "calculus", "polynomial", "gradient"],
                "related_ids": [73, 301, 302],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 301,
                "subject": "math",
                "category": "Calculus",
                "name": "Gradient of a Tangent",
                "latex": r"m = f'(a) = \left.\frac{dy}{dx}\right|_{x=a}",
                "description": "The gradient of the tangent to a curve y = f(x) at the point where x = a equals the derivative evaluated at x = a.",
                "grade_levels": ["ncea-2"],
                "keywords": ["gradient", "tangent", "derivative", "slope", "curve", "instantaneous"],
                "related_ids": [300, 302, 75],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 302,
                "subject": "math",
                "category": "Calculus",
                "name": "Equation of a Tangent Line",
                "latex": r"y - f(a) = f'(a)(x - a)",
                "description": "The equation of the tangent to y = f(x) at x = a uses the point (a, f(a)) and gradient f'(a) in point-slope form.",
                "grade_levels": ["ncea-2"],
                "keywords": ["tangent", "equation", "line", "derivative", "point-slope", "calculus"],
                "related_ids": [301, 75, 43],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 303,
                "subject": "math",
                "category": "Calculus",
                "name": "Finding Maximum and Minimum",
                "latex": r"f'(x) = 0; \quad f''(x) > 0 \implies \text{min}, \quad f''(x) < 0 \implies \text{max}",
                "description": "Stationary points occur where the first derivative is zero. The second derivative test determines whether each is a local maximum, minimum, or inflection point.",
                "grade_levels": ["ncea-2"],
                "keywords": ["maximum", "minimum", "stationary point", "second derivative", "optimisation", "turning point"],
                "related_ids": [300, 301, 304],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 304,
                "subject": "math",
                "category": "Calculus",
                "name": "Anti-derivative (Integration)",
                "latex": r"\int x^n \, dx = \frac{x^{n+1}}{n+1} + C, \quad n \neq -1",
                "description": "The reverse of differentiation for power functions. The constant C is included because the derivative of any constant is zero.",
                "grade_levels": ["ncea-2"],
                "keywords": ["anti-derivative", "integration", "power rule", "constant", "indefinite", "calculus"],
                "related_ids": [76, 300, 305],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 305,
                "subject": "math",
                "category": "Calculus",
                "name": "Area Under a Curve",
                "latex": r"\text{Area} = \int_a^b f(x)\,dx",
                "description": "The definite integral from a to b gives the signed area between the curve y = f(x) and the x-axis. Evaluated using the Fundamental Theorem of Calculus.",
                "grade_levels": ["ncea-2"],
                "keywords": ["area", "curve", "definite integral", "limits", "calculus", "fundamental theorem"],
                "related_ids": [77, 304, 300],
                "curriculum": ["ncea-2"],
            },
            # ---------- Trigonometry ----------
            {
                "id": 306,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Sine Rule",
                "latex": r"\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}",
                "description": "Relates each side of a triangle to the sine of its opposite angle. Used to solve non-right-angled triangles when given AAS or ASA.",
                "grade_levels": ["ncea-2"],
                "keywords": ["sine rule", "triangle", "law of sines", "non-right", "angle", "trigonometry"],
                "related_ids": [11, 307, 308],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 307,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Cosine Rule",
                "latex": r"c^2 = a^2 + b^2 - 2ab\cos C",
                "description": "Generalises Pythagoras' theorem to any triangle. Used when given SAS or SSS to find an unknown side or angle.",
                "grade_levels": ["ncea-2"],
                "keywords": ["cosine rule", "triangle", "law of cosines", "non-right", "Pythagoras", "trigonometry"],
                "related_ids": [12, 306, 283],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 308,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Area of a Triangle Using Sine",
                "latex": r"A = \frac{1}{2}ab\sin C",
                "description": "Calculates the area of any triangle given two sides a and b and the included angle C. Does not require the perpendicular height.",
                "grade_levels": ["ncea-2"],
                "keywords": ["area", "triangle", "sine", "included angle", "trigonometry", "non-right"],
                "related_ids": [58, 306, 285],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 309,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Trigonometric Graphs — Transformations",
                "latex": r"y = A\sin(Bx + C) + D",
                "description": "A is the amplitude, 2*pi/B is the period, -C/B is the phase shift, and D is the vertical shift. Applies to sin, cos, and tan graphs.",
                "grade_levels": ["ncea-2"],
                "keywords": ["amplitude", "period", "phase shift", "trig graph", "transformation", "sinusoidal"],
                "related_ids": [284, 306, 310],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 310,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Reciprocal Trigonometric Functions",
                "latex": r"\sec\theta = \frac{1}{\cos\theta}, \quad \csc\theta = \frac{1}{\sin\theta}, \quad \cot\theta = \frac{1}{\tan\theta}",
                "description": "Secant, cosecant, and cotangent are the reciprocals of cosine, sine, and tangent respectively. Used in advanced trigonometric identities and calculus.",
                "grade_levels": ["ncea-2"],
                "keywords": ["secant", "cosecant", "cotangent", "reciprocal", "trigonometry", "identity"],
                "related_ids": [284, 309, 83],
                "curriculum": ["ncea-2"],
            },
            # ---------- Statistics ----------
            {
                "id": 311,
                "subject": "math",
                "category": "Statistics",
                "name": "Normal Distribution — Z-Score",
                "latex": r"z = \frac{x - \mu}{\sigma}",
                "description": "Standardises a value x from a normal distribution with mean mu and standard deviation sigma into a z-score on the standard normal distribution.",
                "grade_levels": ["ncea-2"],
                "keywords": ["z-score", "normal distribution", "standardise", "mean", "standard deviation", "statistics"],
                "related_ids": [92, 312, 290],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 312,
                "subject": "math",
                "category": "Statistics",
                "name": "Expected Value (Probability Distribution)",
                "latex": r"E(X) = \sum x_i \cdot P(x_i)",
                "description": "The expected value of a discrete random variable is the sum of each value multiplied by its probability. Represents the long-run average outcome.",
                "grade_levels": ["ncea-2"],
                "keywords": ["expected value", "probability distribution", "mean", "random variable", "discrete", "statistics"],
                "related_ids": [91, 311, 292],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 313,
                "subject": "math",
                "category": "Statistics",
                "name": "Margin of Error",
                "latex": r"\text{Margin of error} \approx \frac{1}{\sqrt{n}}",
                "description": "A quick estimate of the margin of error for a sample proportion, where n is the sample size. Used in NCEA to assess the reliability of survey results.",
                "grade_levels": ["ncea-2"],
                "keywords": ["margin of error", "sample", "proportion", "survey", "reliability", "statistics"],
                "related_ids": [314, 311, 290],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 314,
                "subject": "math",
                "category": "Statistics",
                "name": "Confidence Interval for a Proportion",
                "latex": r"\hat{p} \pm z^* \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}",
                "description": "Estimates a range for the true population proportion based on a sample proportion p-hat, sample size n, and critical z-value for the desired confidence level.",
                "grade_levels": ["ncea-2"],
                "keywords": ["confidence interval", "proportion", "sample", "z-value", "estimation", "statistics"],
                "related_ids": [127, 313, 311],
                "curriculum": ["ncea-2"],
            },
            # ---------- Coordinate Geometry ----------
            {
                "id": 315,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Distance Formula",
                "latex": r"d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}",
                "description": "Calculates the straight-line distance between two points (x1, y1) and (x2, y2) in the coordinate plane. Derived from Pythagoras' theorem.",
                "grade_levels": ["ncea-2"],
                "keywords": ["distance", "formula", "coordinate", "points", "Pythagoras", "length"],
                "related_ids": [4, 316, 283],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 316,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Midpoint Formula",
                "latex": r"M = \left(\frac{x_1 + x_2}{2},\; \frac{y_1 + y_2}{2}\right)",
                "description": "Finds the midpoint of a line segment connecting two points by averaging their x-coordinates and y-coordinates separately.",
                "grade_levels": ["ncea-2"],
                "keywords": ["midpoint", "coordinates", "average", "line segment", "geometry", "centre"],
                "related_ids": [42, 315, 317],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 317,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Gradient (Slope)",
                "latex": r"m = \frac{y_2 - y_1}{x_2 - x_1}",
                "description": "The gradient of a straight line through two points measures its steepness. Positive gradient slopes upward; negative gradient slopes downward.",
                "grade_levels": ["ncea-2"],
                "keywords": ["gradient", "slope", "rate of change", "steepness", "line", "coordinate geometry"],
                "related_ids": [3, 318, 315],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 318,
                "subject": "math",
                "category": "Coordinate Geometry",
                "name": "Equation of a Straight Line",
                "latex": r"y = mx + c \quad\text{or}\quad y - y_1 = m(x - x_1)",
                "description": "The equation of a line in slope-intercept form (y = mx + c) or point-slope form. m is the gradient and c is the y-intercept.",
                "grade_levels": ["ncea-2"],
                "keywords": ["equation", "line", "gradient", "y-intercept", "point-slope", "coordinate geometry"],
                "related_ids": [8, 43, 317],
                "curriculum": ["ncea-2"],
            },
            # ================================================================
            # NCEA Level 3 (Year 13) — IDs 319-340
            # ================================================================
            # ---------- Calculus ----------
            {
                "id": 319,
                "subject": "math",
                "category": "Calculus",
                "name": "Chain Rule",
                "latex": r"\frac{dy}{dx} = \frac{dy}{du} \times \frac{du}{dx}",
                "description": "Differentiates composite functions. If y = f(g(x)), the derivative is f'(g(x)) multiplied by g'(x).",
                "grade_levels": ["ncea-3"],
                "keywords": ["chain rule", "composite", "differentiation", "derivative", "calculus", "substitution"],
                "related_ids": [74, 300, 320],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 320,
                "subject": "math",
                "category": "Calculus",
                "name": "Product Rule",
                "latex": r"\frac{d}{dx}(uv) = u\frac{dv}{dx} + v\frac{du}{dx}",
                "description": "Differentiates the product of two functions u and v. The derivative is the first times the derivative of the second plus the second times the derivative of the first.",
                "grade_levels": ["ncea-3"],
                "keywords": ["product rule", "differentiation", "derivative", "multiply", "functions", "calculus"],
                "related_ids": [105, 319, 321],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 321,
                "subject": "math",
                "category": "Calculus",
                "name": "Quotient Rule",
                "latex": r"\frac{d}{dx}\!\left(\frac{u}{v}\right) = \frac{v\frac{du}{dx} - u\frac{dv}{dx}}{v^2}",
                "description": "Differentiates the quotient of two functions. The numerator is (bottom times derivative of top minus top times derivative of bottom) over the bottom squared.",
                "grade_levels": ["ncea-3"],
                "keywords": ["quotient rule", "differentiation", "derivative", "division", "functions", "calculus"],
                "related_ids": [106, 320, 319],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 322,
                "subject": "math",
                "category": "Calculus",
                "name": "Derivatives of Trigonometric Functions",
                "latex": r"\frac{d}{dx}(\sin x) = \cos x, \quad \frac{d}{dx}(\cos x) = -\sin x, \quad \frac{d}{dx}(\tan x) = \sec^2 x",
                "description": "The standard derivatives of the three primary trigonometric functions. Essential building blocks for differentiating trigonometric expressions.",
                "grade_levels": ["ncea-3"],
                "keywords": ["derivative", "trigonometric", "sin", "cos", "tan", "sec", "calculus"],
                "related_ids": [130, 319, 310],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 323,
                "subject": "math",
                "category": "Calculus",
                "name": "Derivative of e^x and ln(x)",
                "latex": r"\frac{d}{dx}(e^x) = e^x, \quad \frac{d}{dx}(\ln x) = \frac{1}{x}",
                "description": "The exponential function e^x is its own derivative, and the derivative of ln(x) is 1/x. These are fundamental results used throughout calculus.",
                "grade_levels": ["ncea-3"],
                "keywords": ["exponential", "derivative", "e", "ln", "natural logarithm", "calculus"],
                "related_ids": [128, 129, 296],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 324,
                "subject": "math",
                "category": "Calculus",
                "name": "Integration of Trigonometric Functions",
                "latex": r"\int \sin x\,dx = -\cos x + C, \quad \int \cos x\,dx = \sin x + C",
                "description": "The anti-derivatives of sine and cosine. Sine integrates to negative cosine, and cosine integrates to sine, plus the constant of integration.",
                "grade_levels": ["ncea-3"],
                "keywords": ["integration", "trigonometric", "sin", "cos", "anti-derivative", "calculus"],
                "related_ids": [322, 304, 130],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 325,
                "subject": "math",
                "category": "Calculus",
                "name": "Integration by Substitution",
                "latex": r"\int f(g(x))\,g'(x)\,dx = \int f(u)\,du, \quad u = g(x)",
                "description": "Reverses the chain rule for integration. Substitute u = g(x) and du = g'(x)dx to simplify the integrand, then convert back.",
                "grade_levels": ["ncea-3"],
                "keywords": ["integration", "substitution", "reverse chain rule", "change of variable", "calculus", "u-sub"],
                "related_ids": [110, 319, 304],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 326,
                "subject": "math",
                "category": "Calculus",
                "name": "Separable Differential Equations",
                "latex": r"\frac{dy}{dx} = f(x)g(y) \implies \int \frac{1}{g(y)}\,dy = \int f(x)\,dx",
                "description": "Solves first-order differential equations where variables can be separated. Move all y terms to one side and x terms to the other, then integrate both sides.",
                "grade_levels": ["ncea-3"],
                "keywords": ["differential equation", "separable", "variables", "first order", "ODE", "calculus"],
                "related_ids": [112, 304, 327],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 327,
                "subject": "math",
                "category": "Calculus",
                "name": "Related Rates",
                "latex": r"\frac{dA}{dt} = \frac{dA}{dr} \times \frac{dr}{dt}",
                "description": "Uses the chain rule to find the rate of change of one quantity with respect to time when it depends on another quantity that also changes with time.",
                "grade_levels": ["ncea-3"],
                "keywords": ["related rates", "chain rule", "rate of change", "time", "derivative", "calculus"],
                "related_ids": [319, 300, 326],
                "curriculum": ["ncea-3"],
            },
            # ---------- Algebra ----------
            {
                "id": 328,
                "subject": "math",
                "category": "Complex Numbers",
                "name": "Complex Numbers",
                "latex": r"z = a + bi, \quad i^2 = -1",
                "description": "A complex number has a real part a and an imaginary part b, where i is the imaginary unit satisfying i^2 = -1. Complex numbers extend the real number system.",
                "grade_levels": ["ncea-3"],
                "keywords": ["complex number", "imaginary", "real part", "i", "algebra", "a+bi"],
                "related_ids": [119, 329, 330],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 329,
                "subject": "math",
                "category": "Complex Numbers",
                "name": "Modulus of a Complex Number",
                "latex": r"|z| = |a + bi| = \sqrt{a^2 + b^2}",
                "description": "The modulus of z = a + bi is the distance from the origin to the point (a, b) in the Argand diagram. Calculated using Pythagoras' theorem.",
                "grade_levels": ["ncea-3"],
                "keywords": ["modulus", "complex number", "magnitude", "Argand", "distance", "absolute value"],
                "related_ids": [119, 328, 330],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 330,
                "subject": "math",
                "category": "Complex Numbers",
                "name": "Argument of a Complex Number",
                "latex": r"\arg(z) = \arctan\!\left(\frac{b}{a}\right)",
                "description": "The argument of z = a + bi is the angle measured anticlockwise from the positive real axis. Care must be taken to identify the correct quadrant.",
                "grade_levels": ["ncea-3"],
                "keywords": ["argument", "complex number", "angle", "Argand", "arctan", "phase"],
                "related_ids": [120, 329, 331],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 331,
                "subject": "math",
                "category": "Complex Numbers",
                "name": "De Moivre's Theorem",
                "latex": r"[r(\cos\theta + i\sin\theta)]^n = r^n(\cos n\theta + i\sin n\theta)",
                "description": "Raises a complex number in polar form to the power n by raising the modulus to n and multiplying the argument by n. Used to find roots of complex numbers.",
                "grade_levels": ["ncea-3"],
                "keywords": ["De Moivre", "theorem", "complex", "power", "roots", "polar form"],
                "related_ids": [122, 329, 330],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 332,
                "subject": "math",
                "category": "Algebra",
                "name": "Conic Sections — Ellipse",
                "latex": r"\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1",
                "description": "The standard equation of an ellipse centred at the origin with semi-major axis a along the x-axis and semi-minor axis b along the y-axis.",
                "grade_levels": ["ncea-3"],
                "keywords": ["ellipse", "conic section", "semi-major", "semi-minor", "equation", "curve"],
                "related_ids": [333, 45, 286],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 333,
                "subject": "math",
                "category": "Algebra",
                "name": "Conic Sections — Hyperbola",
                "latex": r"\frac{x^2}{a^2} - \frac{y^2}{b^2} = 1",
                "description": "The standard equation of a hyperbola centred at the origin with vertices at (plus or minus a, 0) and asymptotes y = (plus or minus b/a)x.",
                "grade_levels": ["ncea-3"],
                "keywords": ["hyperbola", "conic section", "asymptote", "vertex", "equation", "curve"],
                "related_ids": [332, 45, 298],
                "curriculum": ["ncea-3"],
            },
            # ---------- Statistics ----------
            {
                "id": 334,
                "subject": "math",
                "category": "Statistics",
                "name": "Poisson Distribution",
                "latex": r"P(X = r) = \frac{e^{-\lambda}\lambda^r}{r!}",
                "description": "Models the probability of r events occurring in a fixed interval when events happen independently at a constant average rate lambda.",
                "grade_levels": ["ncea-3"],
                "keywords": ["Poisson", "distribution", "probability", "lambda", "rate", "discrete"],
                "related_ids": [126, 335, 312],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 335,
                "subject": "math",
                "category": "Statistics",
                "name": "Binomial Distribution",
                "latex": r"P(X = r) = \binom{n}{r} p^r (1-p)^{n-r}",
                "description": "Gives the probability of exactly r successes in n independent trials, each with the same probability p of success.",
                "grade_levels": ["ncea-3"],
                "keywords": ["binomial", "distribution", "probability", "trials", "success", "discrete"],
                "related_ids": [90, 334, 336],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 336,
                "subject": "math",
                "category": "Statistics",
                "name": "Normal Approximation to Binomial",
                "latex": r"X \sim B(n,p) \approx N(np,\; np(1-p)) \quad\text{when } np > 5 \text{ and } n(1-p) > 5",
                "description": "When n is large and p is not too close to 0 or 1, the binomial distribution can be approximated by a normal distribution with mean np and variance np(1-p).",
                "grade_levels": ["ncea-3"],
                "keywords": ["normal approximation", "binomial", "distribution", "continuity correction", "statistics", "large sample"],
                "related_ids": [335, 311, 92],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 337,
                "subject": "math",
                "category": "Statistics",
                "name": "Hypothesis Testing — Z-Test",
                "latex": r"z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}}",
                "description": "Tests whether a sample mean is significantly different from a hypothesised population mean. The z-statistic is compared to critical values or used to find a p-value.",
                "grade_levels": ["ncea-3"],
                "keywords": ["hypothesis test", "z-test", "significance", "p-value", "null hypothesis", "statistics"],
                "related_ids": [311, 338, 127],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 338,
                "subject": "math",
                "category": "Statistics",
                "name": "Confidence Interval for a Proportion",
                "latex": r"\hat{p} \pm z^* \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}",
                "description": "Constructs an interval estimate for the true population proportion using the sample proportion, sample size, and the critical z-value for the desired confidence level.",
                "grade_levels": ["ncea-3"],
                "keywords": ["confidence interval", "proportion", "z-value", "estimation", "sample", "statistics"],
                "related_ids": [314, 337, 127],
                "curriculum": ["ncea-3"],
            },
            # ---------- Trigonometry ----------
            {
                "id": 339,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Trigonometric Identities — Double Angle",
                "latex": r"\sin 2A = 2\sin A\cos A, \quad \cos 2A = \cos^2 A - \sin^2 A",
                "description": "The double angle identities express sin(2A) and cos(2A) in terms of sin(A) and cos(A). Used to simplify expressions and solve trigonometric equations.",
                "grade_levels": ["ncea-3"],
                "keywords": ["double angle", "identity", "sin", "cos", "trigonometry", "formula"],
                "related_ids": [114, 115, 284],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 340,
                "subject": "math",
                "category": "Trigonometry",
                "name": "Inverse Trigonometric Functions and Parametric Equations",
                "latex": r"\sin^{-1}x,\; \cos^{-1}x,\; \tan^{-1}x; \quad x = f(t),\; y = g(t)",
                "description": "Inverse trig functions return the angle for a given ratio. Parametric equations define x and y separately in terms of a parameter t, useful for describing curves.",
                "grade_levels": ["ncea-3"],
                "keywords": ["inverse trig", "arcsin", "arccos", "arctan", "parametric", "parameter", "curve"],
                "related_ids": [108, 339, 284],
                "curriculum": ["ncea-3"],
            },
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM formulas WHERE id >= 271 AND id <= 340")
