"""Seed NCEA Physics formulas

Revision ID: 011_seed_ncea_physics
Revises: 010_seed_ncea_math
Create Date: 2026-03-03
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "011_seed_ncea_physics"
down_revision: Union[str, None] = "010_seed_ncea_math"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    formulas_table = sa.table(
        "formulas",
        sa.column("id", sa.BigInteger),
        sa.column("subject", sa.String),
        sa.column("category", sa.String),
        sa.column("name", sa.String),
        sa.column("latex", sa.Text),
        sa.column("description", sa.Text),
        sa.column("grade_levels", postgresql.ARRAY(sa.String)),
        sa.column("keywords", postgresql.ARRAY(sa.String)),
        sa.column("related_ids", postgresql.ARRAY(sa.BigInteger)),
        sa.column("curriculum", postgresql.ARRAY(sa.String)),
    )

    op.bulk_insert(
        formulas_table,
        [
            # ==================== NCEA LEVEL 1 (Year 11) — IDs 341-358 ====================
            # ---------- Mechanics ----------
            {
                "id": 341,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Speed",
                "latex": r"v = \frac{d}{t}",
                "description": "Speed is the distance travelled divided by the time taken. This is the most fundamental kinematic relationship.",
                "grade_levels": ["ncea-1"],
                "keywords": ["speed", "distance", "time", "velocity", "motion", "kinematics"],
                "related_ids": [17, 132],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 342,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Acceleration",
                "latex": r"a = \frac{\Delta v}{\Delta t}",
                "description": "Acceleration is the rate of change of velocity with respect to time. A positive value indicates speeding up in the direction of motion.",
                "grade_levels": ["ncea-1"],
                "keywords": ["acceleration", "velocity", "time", "rate of change", "kinematics", "delta"],
                "related_ids": [18, 133, 341],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 343,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Force (Newton's Second Law)",
                "latex": r"F = ma",
                "description": "The net force acting on an object equals its mass multiplied by its acceleration. This is Newton's second law of motion.",
                "grade_levels": ["ncea-1"],
                "keywords": ["force", "mass", "acceleration", "newton", "mechanics", "net force"],
                "related_ids": [13, 134, 344],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 344,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Weight",
                "latex": r"W = mg",
                "description": "Weight is the gravitational force acting on an object, equal to mass times the acceleration due to gravity (g = 9.8 m/s^2 on Earth).",
                "grade_levels": ["ncea-1"],
                "keywords": ["weight", "mass", "gravity", "gravitational", "force", "g"],
                "related_ids": [135, 343, 13],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 345,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Work",
                "latex": r"W = Fd",
                "description": "Work is done when a force moves an object through a distance in the direction of the force. Measured in joules.",
                "grade_levels": ["ncea-1"],
                "keywords": ["work", "force", "distance", "energy", "joules", "displacement"],
                "related_ids": [19, 174, 346],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 346,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Power",
                "latex": r"P = \frac{W}{t}",
                "description": "Power is the rate at which work is done or energy is transferred. Measured in watts (joules per second).",
                "grade_levels": ["ncea-1"],
                "keywords": ["power", "work", "time", "watts", "energy", "rate"],
                "related_ids": [20, 345, 153],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 347,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Kinetic Energy",
                "latex": r"E_k = \frac{1}{2}mv^2",
                "description": "Kinetic energy is the energy an object possesses due to its motion, depending on mass and the square of velocity.",
                "grade_levels": ["ncea-1"],
                "keywords": ["kinetic", "energy", "mass", "velocity", "motion", "speed"],
                "related_ids": [14, 175, 348],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 348,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Gravitational Potential Energy",
                "latex": r"E_p = mgh",
                "description": "Gravitational potential energy is the energy stored in an object due to its height above a reference point in a gravitational field.",
                "grade_levels": ["ncea-1"],
                "keywords": ["potential", "energy", "gravity", "height", "mass", "gravitational"],
                "related_ids": [15, 176, 347],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 349,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Pressure",
                "latex": r"P = \frac{F}{A}",
                "description": "Pressure is the force applied per unit area. Measured in pascals (Pa), where 1 Pa = 1 N/m^2.",
                "grade_levels": ["ncea-1"],
                "keywords": ["pressure", "force", "area", "pascals", "surface", "mechanics"],
                "related_ids": [137, 343],
                "curriculum": ["ncea-1"],
            },
            # ---------- Waves ----------
            {
                "id": 350,
                "subject": "physics",
                "category": "Waves",
                "name": "Wave Speed Equation",
                "latex": r"v = f\lambda",
                "description": "The speed of a wave equals its frequency multiplied by its wavelength. Applies to all types of waves.",
                "grade_levels": ["ncea-1"],
                "keywords": ["wave", "speed", "frequency", "wavelength", "lambda", "propagation"],
                "related_ids": [145, 351],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 351,
                "subject": "physics",
                "category": "Waves",
                "name": "Frequency and Period",
                "latex": r"f = \frac{1}{T}",
                "description": "Frequency is the reciprocal of the period. Frequency measures oscillations per second (Hz), while period is the time for one complete oscillation.",
                "grade_levels": ["ncea-1"],
                "keywords": ["frequency", "period", "hertz", "oscillation", "wave", "reciprocal"],
                "related_ids": [146, 350],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 352,
                "subject": "physics",
                "category": "Waves",
                "name": "Law of Reflection",
                "latex": r"\theta_i = \theta_r",
                "description": "The angle of incidence equals the angle of reflection, both measured from the normal to the reflecting surface.",
                "grade_levels": ["ncea-1"],
                "keywords": ["reflection", "angle", "incidence", "mirror", "normal", "light"],
                "related_ids": [145, 350],
                "curriculum": ["ncea-1"],
            },
            # ---------- Electricity ----------
            {
                "id": 353,
                "subject": "physics",
                "category": "Electricity",
                "name": "Ohm's Law",
                "latex": r"V = IR",
                "description": "The voltage across a component equals the current flowing through it multiplied by its resistance.",
                "grade_levels": ["ncea-1"],
                "keywords": ["voltage", "current", "resistance", "ohm", "circuit", "potential difference"],
                "related_ids": [16, 152, 354],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 354,
                "subject": "physics",
                "category": "Electricity",
                "name": "Electrical Power",
                "latex": r"P = IV",
                "description": "Electrical power is the rate of energy transfer in a circuit, equal to current multiplied by voltage. Measured in watts.",
                "grade_levels": ["ncea-1"],
                "keywords": ["power", "current", "voltage", "watts", "electrical", "energy"],
                "related_ids": [153, 353, 355],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 355,
                "subject": "physics",
                "category": "Electricity",
                "name": "Electrical Energy",
                "latex": r"E = Pt",
                "description": "Electrical energy consumed equals power multiplied by time. Used to calculate energy usage in circuits and appliances.",
                "grade_levels": ["ncea-1"],
                "keywords": ["energy", "power", "time", "electrical", "joules", "consumption"],
                "related_ids": [156, 354, 346],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 356,
                "subject": "physics",
                "category": "Electricity",
                "name": "Charge",
                "latex": r"Q = It",
                "description": "Electric charge transferred equals the current flowing multiplied by the time. Measured in coulombs.",
                "grade_levels": ["ncea-1"],
                "keywords": ["charge", "current", "time", "coulombs", "electrons", "flow"],
                "related_ids": [151, 353],
                "curriculum": ["ncea-1"],
            },
            # ---------- Heat ----------
            {
                "id": 357,
                "subject": "physics",
                "category": "Thermal Physics",
                "name": "Specific Heat Capacity",
                "latex": r"Q = mc\Delta T",
                "description": "The heat energy required to change the temperature of a substance depends on its mass, specific heat capacity, and the temperature change.",
                "grade_levels": ["ncea-1"],
                "keywords": ["heat", "specific heat", "temperature", "mass", "thermal", "energy"],
                "related_ids": [141, 347, 348],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 358,
                "subject": "physics",
                "category": "Thermal Physics",
                "name": "Heat Transfer Efficiency",
                "latex": r"\eta = \frac{E_{\text{useful}}}{E_{\text{total}}} \times 100\%",
                "description": "Efficiency measures the percentage of input energy that is converted to useful output energy. No real process is 100% efficient.",
                "grade_levels": ["ncea-1"],
                "keywords": ["efficiency", "energy", "heat", "transfer", "useful", "loss"],
                "related_ids": [177, 357, 346],
                "curriculum": ["ncea-1"],
            },
            # ==================== NCEA LEVEL 2 (Year 12) — IDs 359-380 ====================
            # ---------- Mechanics (SUVAT & Kinematics) ----------
            {
                "id": 359,
                "subject": "physics",
                "category": "Mechanics",
                "name": "SUVAT: Final Velocity",
                "latex": r"v = u + at",
                "description": "The final velocity equals the initial velocity plus acceleration multiplied by time. First SUVAT equation of motion.",
                "grade_levels": ["ncea-2"],
                "keywords": ["suvat", "velocity", "acceleration", "time", "kinematics", "motion"],
                "related_ids": [161, 342, 360],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 360,
                "subject": "physics",
                "category": "Mechanics",
                "name": "SUVAT: Displacement (Time)",
                "latex": r"s = ut + \frac{1}{2}at^2",
                "description": "Displacement equals initial velocity times time plus half the acceleration times time squared. Used when final velocity is unknown.",
                "grade_levels": ["ncea-2"],
                "keywords": ["suvat", "displacement", "time", "acceleration", "kinematics", "distance"],
                "related_ids": [162, 359, 361],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 361,
                "subject": "physics",
                "category": "Mechanics",
                "name": "SUVAT: Velocity-Displacement",
                "latex": r"v^2 = u^2 + 2as",
                "description": "The square of final velocity equals the square of initial velocity plus twice the acceleration times displacement. Used when time is unknown.",
                "grade_levels": ["ncea-2"],
                "keywords": ["suvat", "velocity", "displacement", "acceleration", "kinematics", "squared"],
                "related_ids": [163, 359, 360],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 362,
                "subject": "physics",
                "category": "Mechanics",
                "name": "SUVAT: Average Velocity",
                "latex": r"s = \frac{1}{2}(u + v)t",
                "description": "Displacement equals half the sum of initial and final velocities multiplied by time. Used when acceleration is unknown.",
                "grade_levels": ["ncea-2"],
                "keywords": ["suvat", "average", "velocity", "displacement", "time", "kinematics"],
                "related_ids": [164, 359, 360],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 363,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Projectile Motion: Horizontal Component",
                "latex": r"x = v_x t",
                "description": "In projectile motion the horizontal displacement equals horizontal velocity times time, as there is no horizontal acceleration (ignoring air resistance).",
                "grade_levels": ["ncea-2"],
                "keywords": ["projectile", "horizontal", "velocity", "displacement", "motion", "component"],
                "related_ids": [165, 364, 359],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 364,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Projectile Motion: Vertical Component",
                "latex": r"y = v_{y_0}t + \frac{1}{2}gt^2",
                "description": "The vertical displacement of a projectile is governed by the initial vertical velocity and gravitational acceleration acting downward.",
                "grade_levels": ["ncea-2"],
                "keywords": ["projectile", "vertical", "gravity", "displacement", "motion", "freefall"],
                "related_ids": [166, 363, 360],
                "curriculum": ["ncea-2"],
            },
            # ---------- Momentum ----------
            {
                "id": 365,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Momentum",
                "latex": r"p = mv",
                "description": "Momentum is the product of an object's mass and velocity. It is a vector quantity with the same direction as the velocity.",
                "grade_levels": ["ncea-2"],
                "keywords": ["momentum", "mass", "velocity", "vector", "motion", "inertia"],
                "related_ids": [21, 167, 366],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 366,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Impulse",
                "latex": r"\Delta p = F\Delta t",
                "description": "Impulse is the change in momentum of an object, equal to the net force applied multiplied by the time interval over which it acts.",
                "grade_levels": ["ncea-2"],
                "keywords": ["impulse", "momentum", "force", "time", "change", "collision"],
                "related_ids": [168, 365, 343],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 367,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Conservation of Momentum",
                "latex": r"m_1 v_1 + m_2 v_2 = m_1 v_1' + m_2 v_2'",
                "description": "In an isolated system, the total momentum before a collision or interaction equals the total momentum after. This is a fundamental conservation law.",
                "grade_levels": ["ncea-2"],
                "keywords": ["conservation", "momentum", "collision", "isolated", "system", "interaction"],
                "related_ids": [169, 365, 366],
                "curriculum": ["ncea-2"],
            },
            # ---------- Circular Motion ----------
            {
                "id": 368,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Centripetal Acceleration",
                "latex": r"a_c = \frac{v^2}{r}",
                "description": "An object moving in a circle experiences centripetal acceleration directed toward the centre, equal to the square of the speed divided by the radius.",
                "grade_levels": ["ncea-2"],
                "keywords": ["centripetal", "acceleration", "circular", "radius", "velocity", "centre"],
                "related_ids": [187, 369, 342],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 369,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Centripetal Force",
                "latex": r"F_c = \frac{mv^2}{r}",
                "description": "The centripetal force required to keep an object moving in a circle equals mass times velocity squared divided by the radius of the circular path.",
                "grade_levels": ["ncea-2"],
                "keywords": ["centripetal", "force", "circular", "radius", "mass", "velocity"],
                "related_ids": [188, 368, 343],
                "curriculum": ["ncea-2"],
            },
            # ---------- Electricity ----------
            {
                "id": 370,
                "subject": "physics",
                "category": "Electricity",
                "name": "EMF and Internal Resistance",
                "latex": r"\varepsilon = I(R + r)",
                "description": "The electromotive force of a source equals the current multiplied by the sum of external resistance and internal resistance.",
                "grade_levels": ["ncea-2"],
                "keywords": ["emf", "internal resistance", "voltage", "current", "battery", "source"],
                "related_ids": [159, 353, 371],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 371,
                "subject": "physics",
                "category": "Electricity",
                "name": "Resistors in Series",
                "latex": r"R_T = R_1 + R_2 + R_3 + \cdots",
                "description": "The total resistance of resistors connected in series is the sum of all individual resistances.",
                "grade_levels": ["ncea-2"],
                "keywords": ["resistors", "series", "resistance", "total", "circuit", "addition"],
                "related_ids": [157, 372, 353],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 372,
                "subject": "physics",
                "category": "Electricity",
                "name": "Resistors in Parallel",
                "latex": r"\frac{1}{R_T} = \frac{1}{R_1} + \frac{1}{R_2} + \frac{1}{R_3} + \cdots",
                "description": "For resistors in parallel, the reciprocal of total resistance equals the sum of the reciprocals of each individual resistance.",
                "grade_levels": ["ncea-2"],
                "keywords": ["resistors", "parallel", "resistance", "reciprocal", "circuit", "branches"],
                "related_ids": [158, 371, 353],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 373,
                "subject": "physics",
                "category": "Electricity",
                "name": "Resistivity",
                "latex": r"\rho = \frac{RA}{L}",
                "description": "Resistivity is a material property relating resistance to the conductor's cross-sectional area and length. Measured in ohm-metres.",
                "grade_levels": ["ncea-2"],
                "keywords": ["resistivity", "resistance", "area", "length", "conductor", "material"],
                "related_ids": [185, 353, 371],
                "curriculum": ["ncea-2"],
            },
            # ---------- Waves ----------
            {
                "id": 374,
                "subject": "physics",
                "category": "Waves",
                "name": "Constructive Interference Condition",
                "latex": r"\Delta x = n\lambda \quad (n = 0, 1, 2, \ldots)",
                "description": "Constructive interference occurs when the path difference between two coherent waves is a whole number of wavelengths.",
                "grade_levels": ["ncea-2"],
                "keywords": ["interference", "constructive", "path difference", "wavelength", "waves", "superposition"],
                "related_ids": [180, 375, 350],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 375,
                "subject": "physics",
                "category": "Waves",
                "name": "Destructive Interference Condition",
                "latex": r"\Delta x = \left(n + \frac{1}{2}\right)\lambda \quad (n = 0, 1, 2, \ldots)",
                "description": "Destructive interference occurs when the path difference between two coherent waves is an odd number of half-wavelengths.",
                "grade_levels": ["ncea-2"],
                "keywords": ["interference", "destructive", "path difference", "wavelength", "waves", "cancellation"],
                "related_ids": [180, 374, 350],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 376,
                "subject": "physics",
                "category": "Waves",
                "name": "Standing Waves: Harmonics",
                "latex": r"L = \frac{n\lambda}{2} \quad (n = 1, 2, 3, \ldots)",
                "description": "For standing waves on a string fixed at both ends, the length equals a whole number of half-wavelengths, producing the harmonic series.",
                "grade_levels": ["ncea-2"],
                "keywords": ["standing wave", "harmonics", "resonance", "wavelength", "string", "nodes"],
                "related_ids": [350, 377, 374],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 377,
                "subject": "physics",
                "category": "Waves",
                "name": "Resonance Frequency",
                "latex": r"f_n = \frac{nv}{2L} \quad (n = 1, 2, 3, \ldots)",
                "description": "The resonant frequencies of a vibrating string or air column are integer multiples of the fundamental frequency, determined by wave speed and length.",
                "grade_levels": ["ncea-2"],
                "keywords": ["resonance", "frequency", "harmonics", "fundamental", "overtone", "vibration"],
                "related_ids": [376, 350, 351],
                "curriculum": ["ncea-2"],
            },
            # ---------- Nuclear ----------
            {
                "id": 378,
                "subject": "physics",
                "category": "Nuclear Physics",
                "name": "Radioactive Decay",
                "latex": r"N = N_0 \left(\frac{1}{2}\right)^{t/t_{1/2}}",
                "description": "The number of undecayed nuclei decreases exponentially over time, halving with each half-life period.",
                "grade_levels": ["ncea-2"],
                "keywords": ["radioactive", "decay", "nuclei", "exponential", "half-life", "activity"],
                "related_ids": [210, 160, 379],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 379,
                "subject": "physics",
                "category": "Nuclear Physics",
                "name": "Half-Life",
                "latex": r"t_{1/2} = \frac{\ln 2}{\lambda}",
                "description": "The half-life is the time taken for half the radioactive nuclei in a sample to decay. It is related to the decay constant by the natural logarithm of 2.",
                "grade_levels": ["ncea-2"],
                "keywords": ["half-life", "decay constant", "radioactive", "lambda", "logarithm", "nuclear"],
                "related_ids": [210, 378, 380],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 380,
                "subject": "physics",
                "category": "Nuclear Physics",
                "name": "Activity",
                "latex": r"A = \lambda N",
                "description": "The activity of a radioactive sample is the number of decays per second, equal to the decay constant multiplied by the number of undecayed nuclei.",
                "grade_levels": ["ncea-2"],
                "keywords": ["activity", "decay constant", "nuclei", "becquerel", "radioactive", "rate"],
                "related_ids": [160, 378, 379],
                "curriculum": ["ncea-2"],
            },
            # ---------- Electromagnetism ----------
            # Note: These fit within the Level 2 ID range alongside the above
            # The motor effect, generator principle, and transformer are covered
            # by IDs 370-373 (electricity) and we add the remaining EM here.
            # However, the spec allocates IDs 359-380 for Level 2 and we have
            # used 359-380 above. The electromagnetism topics (motor effect,
            # generator, transformer) are embedded in the existing entries or
            # referenced via Cambridge cross-links. Let's verify the count:
            # 359-364 (6 SUVAT/projectile) + 365-367 (3 momentum) +
            # 368-369 (2 circular) + 370-373 (4 electricity) +
            # 374-377 (4 waves) + 378-380 (3 nuclear) = 22 formulas. Perfect.

            # ==================== NCEA LEVEL 3 (Year 13) — IDs 381-400 ====================
            # ---------- Mechanics (Rotational) ----------
            {
                "id": 381,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Angular Velocity",
                "latex": r"\omega = 2\pi f",
                "description": "Angular velocity is the rate of rotation measured in radians per second, equal to 2 pi times the frequency of revolution.",
                "grade_levels": ["ncea-3"],
                "keywords": ["angular velocity", "omega", "frequency", "radians", "rotation", "circular"],
                "related_ids": [186, 351, 368],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 382,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Rotational Kinematics",
                "latex": r"\omega = \omega_0 + \alpha t",
                "description": "The angular equivalent of the SUVAT equation v = u + at, relating final angular velocity to initial angular velocity, angular acceleration, and time.",
                "grade_levels": ["ncea-3"],
                "keywords": ["rotational", "kinematics", "angular", "acceleration", "alpha", "omega"],
                "related_ids": [381, 359, 186],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 383,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Torque",
                "latex": r"\tau = Fr",
                "description": "Torque is the rotational equivalent of force, equal to the applied force multiplied by the perpendicular distance from the pivot (moment arm).",
                "grade_levels": ["ncea-3"],
                "keywords": ["torque", "force", "moment", "rotation", "lever arm", "pivot"],
                "related_ids": [171, 136, 343],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 384,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Angular Momentum",
                "latex": r"L = I\omega",
                "description": "Angular momentum is the rotational analogue of linear momentum, equal to the moment of inertia multiplied by angular velocity. Conserved in the absence of external torques.",
                "grade_levels": ["ncea-3"],
                "keywords": ["angular momentum", "moment of inertia", "omega", "conservation", "rotation", "spin"],
                "related_ids": [385, 381, 21],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 385,
                "subject": "physics",
                "category": "Mechanics",
                "name": "Moment of Inertia (Point Mass)",
                "latex": r"I = mr^2",
                "description": "The moment of inertia of a point mass is the product of its mass and the square of its distance from the axis of rotation. It quantifies rotational inertia.",
                "grade_levels": ["ncea-3"],
                "keywords": ["moment of inertia", "mass", "radius", "rotation", "inertia", "point mass"],
                "related_ids": [384, 383, 381],
                "curriculum": ["ncea-3"],
            },
            # ---------- Waves & Quantum ----------
            {
                "id": 386,
                "subject": "physics",
                "category": "Quantum Physics",
                "name": "Photon Energy",
                "latex": r"E = hf",
                "description": "The energy of a photon is directly proportional to its frequency, with Planck's constant h as the proportionality constant.",
                "grade_levels": ["ncea-3"],
                "keywords": ["photon", "energy", "planck", "frequency", "quantum", "light"],
                "related_ids": [207, 387, 388],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 387,
                "subject": "physics",
                "category": "Quantum Physics",
                "name": "Photoelectric Effect",
                "latex": r"hf = \phi + E_k",
                "description": "In the photoelectric effect, a photon's energy is used to overcome the work function of the metal surface, with any remaining energy becoming kinetic energy of the emitted electron.",
                "grade_levels": ["ncea-3"],
                "keywords": ["photoelectric", "work function", "photon", "electron", "kinetic energy", "threshold"],
                "related_ids": [208, 386, 347],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 388,
                "subject": "physics",
                "category": "Quantum Physics",
                "name": "de Broglie Wavelength",
                "latex": r"\lambda = \frac{h}{p}",
                "description": "Every particle has an associated wavelength inversely proportional to its momentum, demonstrating wave-particle duality.",
                "grade_levels": ["ncea-3"],
                "keywords": ["de broglie", "wavelength", "momentum", "wave-particle", "duality", "quantum"],
                "related_ids": [208, 386, 365],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 389,
                "subject": "physics",
                "category": "Quantum Physics",
                "name": "Wave-Particle Duality",
                "latex": r"E = hf = \frac{hc}{\lambda}",
                "description": "Light exhibits both wave and particle properties. Photon energy can be expressed in terms of frequency or wavelength using Planck's constant and the speed of light.",
                "grade_levels": ["ncea-3"],
                "keywords": ["wave-particle", "duality", "photon", "wavelength", "frequency", "planck"],
                "related_ids": [386, 388, 207],
                "curriculum": ["ncea-3"],
            },
            # ---------- Electromagnetism ----------
            {
                "id": 390,
                "subject": "physics",
                "category": "Electromagnetism",
                "name": "Faraday's Law of Induction",
                "latex": r"\varepsilon = -N\frac{\Delta\Phi}{\Delta t}",
                "description": "The induced EMF in a coil is proportional to the rate of change of magnetic flux through the coil, multiplied by the number of turns. The negative sign indicates Lenz's law.",
                "grade_levels": ["ncea-3"],
                "keywords": ["faraday", "induction", "emf", "magnetic flux", "coil", "lenz"],
                "related_ids": [202, 391, 392],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 391,
                "subject": "physics",
                "category": "Electromagnetism",
                "name": "Magnetic Flux",
                "latex": r"\Phi = BA\cos\theta",
                "description": "Magnetic flux is the product of magnetic field strength, the area of the surface, and the cosine of the angle between the field and the normal to the surface.",
                "grade_levels": ["ncea-3"],
                "keywords": ["magnetic flux", "field", "area", "weber", "normal", "angle"],
                "related_ids": [202, 390, 200],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 392,
                "subject": "physics",
                "category": "Electromagnetism",
                "name": "Lenz's Law",
                "latex": r"\varepsilon = -\frac{d\Phi}{dt}",
                "description": "The direction of an induced EMF is such that it opposes the change in magnetic flux that produced it. This is a consequence of conservation of energy.",
                "grade_levels": ["ncea-3"],
                "keywords": ["lenz", "induced", "emf", "opposition", "flux", "conservation"],
                "related_ids": [390, 391, 202],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 393,
                "subject": "physics",
                "category": "Electromagnetism",
                "name": "Inductance",
                "latex": r"\varepsilon = -L\frac{\Delta I}{\Delta t}",
                "description": "The self-induced EMF in an inductor is proportional to the rate of change of current through it, with inductance L as the proportionality constant.",
                "grade_levels": ["ncea-3"],
                "keywords": ["inductance", "inductor", "emf", "current", "henry", "self-induction"],
                "related_ids": [390, 392, 16],
                "curriculum": ["ncea-3"],
            },
            # ---------- Modern Physics (Relativity) ----------
            {
                "id": 394,
                "subject": "physics",
                "category": "Modern Physics",
                "name": "Time Dilation",
                "latex": r"t = \frac{t_0}{\sqrt{1 - \frac{v^2}{c^2}}}",
                "description": "In special relativity, a moving clock runs slower relative to a stationary observer. The proper time t_0 is dilated by the Lorentz factor.",
                "grade_levels": ["ncea-3"],
                "keywords": ["time dilation", "relativity", "lorentz", "proper time", "speed of light", "special"],
                "related_ids": [395, 396, 209],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 395,
                "subject": "physics",
                "category": "Modern Physics",
                "name": "Length Contraction",
                "latex": r"L = L_0\sqrt{1 - \frac{v^2}{c^2}}",
                "description": "In special relativity, the length of an object moving relative to an observer is shorter than its proper length by the Lorentz factor.",
                "grade_levels": ["ncea-3"],
                "keywords": ["length contraction", "relativity", "lorentz", "proper length", "speed of light", "special"],
                "related_ids": [394, 396, 209],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 396,
                "subject": "physics",
                "category": "Modern Physics",
                "name": "Mass-Energy Equivalence",
                "latex": r"E = mc^2",
                "description": "Einstein's famous equation showing that mass and energy are interchangeable. A small amount of mass corresponds to a very large amount of energy.",
                "grade_levels": ["ncea-3"],
                "keywords": ["mass-energy", "equivalence", "einstein", "speed of light", "relativity", "nuclear"],
                "related_ids": [209, 394, 395],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 397,
                "subject": "physics",
                "category": "Modern Physics",
                "name": "Relativistic Energy",
                "latex": r"E = \gamma m c^2 = \frac{mc^2}{\sqrt{1 - \frac{v^2}{c^2}}}",
                "description": "The total energy of a relativistic object includes both rest energy and kinetic energy, scaled by the Lorentz factor gamma.",
                "grade_levels": ["ncea-3"],
                "keywords": ["relativistic", "energy", "lorentz factor", "gamma", "rest mass", "total energy"],
                "related_ids": [396, 394, 209],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 398,
                "subject": "physics",
                "category": "Modern Physics",
                "name": "Bohr Model Energy Levels",
                "latex": r"E_n = -\frac{13.6}{n^2} \text{ eV}",
                "description": "In the Bohr model of hydrogen, the energy of the nth level is inversely proportional to n squared. The ground state (n=1) has the lowest energy at -13.6 eV.",
                "grade_levels": ["ncea-3"],
                "keywords": ["bohr", "energy levels", "hydrogen", "quantum", "orbit", "electron"],
                "related_ids": [386, 207, 389],
                "curriculum": ["ncea-3"],
            },
            # ---------- AC Circuits ----------
            {
                "id": 399,
                "subject": "physics",
                "category": "AC Circuits",
                "name": "RMS Voltage",
                "latex": r"V_{\text{rms}} = \frac{V_0}{\sqrt{2}}",
                "description": "The root mean square voltage of an AC signal equals the peak voltage divided by the square root of 2. RMS values allow comparison with equivalent DC values.",
                "grade_levels": ["ncea-3"],
                "keywords": ["rms", "voltage", "alternating current", "peak", "AC", "effective"],
                "related_ids": [353, 354, 400],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 400,
                "subject": "physics",
                "category": "AC Circuits",
                "name": "Resonant Frequency (LC Circuit)",
                "latex": r"f = \frac{1}{2\pi\sqrt{LC}}",
                "description": "The resonant frequency of an LC circuit is determined by the inductance and capacitance. At resonance, the impedance is minimised and energy oscillates between the inductor and capacitor.",
                "grade_levels": ["ncea-3"],
                "keywords": ["resonance", "frequency", "inductance", "capacitance", "LC circuit", "impedance"],
                "related_ids": [393, 399, 377],
                "curriculum": ["ncea-3"],
            },
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM formulas WHERE id >= 341 AND id <= 400")
