"""Seed NCEA Chemistry formulas

Revision ID: 012_seed_ncea_chemistry
Revises: 011_seed_ncea_physics
Create Date: 2026-03-03
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "012_seed_ncea_chemistry"
down_revision: Union[str, None] = "011_seed_ncea_physics"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    formulas_table = sa.table(
        "formulas",
        sa.column("id", sa.BigInteger),
        sa.column("subject", sa.String),
        sa.column("category", sa.String),
        sa.column("name", sa.String),
        sa.column("latex", sa.Text),
        sa.column("description", sa.Text),
        sa.column("grade_levels", postgresql.ARRAY(sa.String)),
        sa.column("keywords", postgresql.ARRAY(sa.String)),
        sa.column("related_ids", postgresql.ARRAY(sa.BigInteger)),
        sa.column("curriculum", postgresql.ARRAY(sa.String)),
    )

    op.bulk_insert(
        formulas_table,
        [
            # ============================================================
            # NCEA Level 1 (Year 11) — IDs 401-412
            # ============================================================
            {
                "id": 401,
                "subject": "chemistry",
                "category": "Atomic Structure",
                "name": "Atomic Number",
                "latex": r"Z = \text{number of protons} = \text{number of electrons (neutral atom)}",
                "description": "The atomic number (Z) equals the number of protons in the nucleus and uniquely identifies an element. In a neutral atom, it also equals the number of electrons.",
                "grade_levels": ["ncea-1"],
                "keywords": ["atomic number", "protons", "electrons", "element", "nucleus", "identity"],
                "related_ids": [402, 403, 215, 28],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 402,
                "subject": "chemistry",
                "category": "Atomic Structure",
                "name": "Mass Number",
                "latex": r"A = Z + N",
                "description": "The mass number (A) is the total number of protons (Z) and neutrons (N) in the nucleus. It determines the isotope of an element and approximates the atomic mass in atomic mass units.",
                "grade_levels": ["ncea-1"],
                "keywords": ["mass number", "protons", "neutrons", "nucleus", "isotope", "nucleon number"],
                "related_ids": [401, 403, 404, 215],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 403,
                "subject": "chemistry",
                "category": "Atomic Structure",
                "name": "Isotope Notation",
                "latex": r"{}^{A}_{Z}X",
                "description": "Standard isotope notation shows the element symbol (X) with the mass number (A) as a superscript and the atomic number (Z) as a subscript on the left side.",
                "grade_levels": ["ncea-1"],
                "keywords": ["isotope", "notation", "mass number", "atomic number", "element symbol", "nuclide"],
                "related_ids": [401, 402, 404],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 404,
                "subject": "chemistry",
                "category": "Atomic Structure",
                "name": "Relative Atomic Mass from Isotopes",
                "latex": r"A_r = \frac{\sum (\text{isotope mass} \times \text{abundance})}{100}",
                "description": "The relative atomic mass is the weighted average of the masses of all naturally occurring isotopes of an element, calculated using their percentage abundances.",
                "grade_levels": ["ncea-1"],
                "keywords": ["relative atomic mass", "Ar", "isotopes", "weighted average", "abundance", "periodic table"],
                "related_ids": [401, 402, 403, 215],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 405,
                "subject": "chemistry",
                "category": "Reactions",
                "name": "Balancing Chemical Equations",
                "latex": r"\sum \text{atoms of each element (reactants)} = \sum \text{atoms of each element (products)}",
                "description": "A balanced chemical equation has equal numbers of each type of atom on both sides. Coefficients are adjusted to satisfy the law of conservation of mass.",
                "grade_levels": ["ncea-1"],
                "keywords": ["balancing equations", "coefficients", "conservation of mass", "reactants", "products", "stoichiometry"],
                "related_ids": [406, 407, 217, 23],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 406,
                "subject": "chemistry",
                "category": "Reactions",
                "name": "Mole Ratio from Balanced Equation",
                "latex": r"aA + bB \rightarrow cC + dD \;\Rightarrow\; n_A : n_B : n_C : n_D = a : b : c : d",
                "description": "The coefficients in a balanced equation give the mole ratio of reactants and products. This ratio is used to calculate how much product forms from a given amount of reactant.",
                "grade_levels": ["ncea-1"],
                "keywords": ["mole ratio", "stoichiometry", "coefficients", "balanced equation", "proportion", "reacting quantities"],
                "related_ids": [405, 407, 211, 28],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 407,
                "subject": "chemistry",
                "category": "Reactions",
                "name": "Conservation of Mass",
                "latex": r"\text{Total mass of reactants} = \text{Total mass of products}",
                "description": "In a chemical reaction, matter is neither created nor destroyed. The total mass of all reactants equals the total mass of all products, as atoms are merely rearranged.",
                "grade_levels": ["ncea-1"],
                "keywords": ["conservation of mass", "Lavoisier", "reactants", "products", "mass", "atoms rearranged"],
                "related_ids": [405, 406, 212],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 408,
                "subject": "chemistry",
                "category": "Acids and Bases",
                "name": "pH Scale (NCEA Level 1)",
                "latex": r"pH < 7 \;\text{acidic}\;;\; pH = 7 \;\text{neutral}\;;\; pH > 7 \;\text{basic}",
                "description": "The pH scale runs from 0 to 14 and measures how acidic or basic a solution is. Values below 7 are acidic, 7 is neutral, and above 7 are basic (alkaline).",
                "grade_levels": ["ncea-1"],
                "keywords": ["pH", "acid", "base", "neutral", "alkaline", "scale"],
                "related_ids": [409, 410, 26, 262],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 409,
                "subject": "chemistry",
                "category": "Acids and Bases",
                "name": "Neutralisation Reaction",
                "latex": r"\text{acid} + \text{base} \rightarrow \text{salt} + \text{water}",
                "description": "A neutralisation reaction occurs when an acid reacts with a base to produce a salt and water. The hydrogen ions from the acid combine with hydroxide ions from the base to form water.",
                "grade_levels": ["ncea-1"],
                "keywords": ["neutralisation", "acid", "base", "salt", "water", "reaction"],
                "related_ids": [408, 410, 250, 26],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 410,
                "subject": "chemistry",
                "category": "Acids and Bases",
                "name": "Indicator Colour Changes",
                "latex": r"\text{Litmus: red (acid), blue (base)}\;;\; \text{Phenolphthalein: colourless (acid), pink (base)}",
                "description": "Indicators change colour depending on the pH of a solution. Litmus turns red in acid and blue in base; phenolphthalein is colourless in acid and pink in base.",
                "grade_levels": ["ncea-1"],
                "keywords": ["indicator", "litmus", "phenolphthalein", "colour change", "acid", "base"],
                "related_ids": [408, 409, 26],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 411,
                "subject": "chemistry",
                "category": "Carbon Chemistry",
                "name": "General Formula of Alkanes",
                "latex": r"C_nH_{2n+2}",
                "description": "Alkanes are saturated hydrocarbons with only single bonds. Their general formula relates the number of carbon atoms (n) to the number of hydrogen atoms, forming a homologous series.",
                "grade_levels": ["ncea-1"],
                "keywords": ["alkanes", "saturated", "hydrocarbons", "homologous series", "general formula", "single bonds"],
                "related_ids": [412, 246, 217],
                "curriculum": ["ncea-1"],
            },
            {
                "id": 412,
                "subject": "chemistry",
                "category": "Carbon Chemistry",
                "name": "Combustion of Hydrocarbons",
                "latex": r"C_xH_y + \left(x + \frac{y}{4}\right)O_2 \rightarrow x\,CO_2 + \frac{y}{2}\,H_2O",
                "description": "Complete combustion of a hydrocarbon in excess oxygen produces carbon dioxide and water. This is an exothermic reaction and the basis for fossil fuel energy release.",
                "grade_levels": ["ncea-1"],
                "keywords": ["combustion", "hydrocarbon", "carbon dioxide", "water", "exothermic", "oxygen"],
                "related_ids": [411, 405, 223, 30],
                "curriculum": ["ncea-1"],
            },
            # ============================================================
            # NCEA Level 2 (Year 12) — IDs 413-428
            # ============================================================
            {
                "id": 413,
                "subject": "chemistry",
                "category": "Quantitative Chemistry",
                "name": "Moles from Mass (NCEA)",
                "latex": r"n = \frac{m}{M}",
                "description": "The number of moles (n) equals the mass of the substance (m) in grams divided by its molar mass (M) in g/mol. This is the foundational calculation for all quantitative chemistry in NCEA.",
                "grade_levels": ["ncea-2"],
                "keywords": ["moles", "mass", "molar mass", "amount of substance", "calculation", "n=m/M"],
                "related_ids": [414, 415, 211, 28],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 414,
                "subject": "chemistry",
                "category": "Quantitative Chemistry",
                "name": "Concentration (NCEA)",
                "latex": r"c = \frac{n}{V}",
                "description": "Concentration (c) in mol/L equals the number of moles of solute (n) divided by the volume of solution (V) in litres. Used extensively in solution chemistry and titration calculations.",
                "grade_levels": ["ncea-2"],
                "keywords": ["concentration", "molarity", "moles", "volume", "solution", "mol/L"],
                "related_ids": [413, 416, 214, 25],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 415,
                "subject": "chemistry",
                "category": "Quantitative Chemistry",
                "name": "Mass from Moles (NCEA)",
                "latex": r"m = n \times M",
                "description": "The mass of a substance in grams equals the number of moles multiplied by the molar mass. This rearrangement of n=m/M is used to find the expected mass of product or reactant.",
                "grade_levels": ["ncea-2"],
                "keywords": ["mass", "moles", "molar mass", "calculation", "product", "reactant"],
                "related_ids": [413, 414, 212, 28],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 416,
                "subject": "chemistry",
                "category": "Quantitative Chemistry",
                "name": "Titration Calculation (NCEA)",
                "latex": r"\frac{c_1 V_1}{n_1} = \frac{c_2 V_2}{n_2}",
                "description": "Relates the concentrations and volumes of two solutions in a titration using their stoichiometric mole ratio (n1 and n2) from the balanced equation. Used to find unknown concentration or volume.",
                "grade_levels": ["ncea-2"],
                "keywords": ["titration", "concentration", "volume", "mole ratio", "stoichiometry", "volumetric analysis"],
                "related_ids": [414, 413, 233, 25],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 417,
                "subject": "chemistry",
                "category": "Quantitative Chemistry",
                "name": "Gas Molar Volume at RTP (NZ)",
                "latex": r"n = \frac{V}{24.8 \text{ dm}^3}",
                "description": "At room temperature and pressure in New Zealand (approximately 20 degrees C, 1 atm), one mole of any gas occupies 24.8 dm cubed. Used to convert between gas volume and moles.",
                "grade_levels": ["ncea-2"],
                "keywords": ["gas volume", "molar volume", "RTP", "24.8 dm3", "moles", "New Zealand"],
                "related_ids": [413, 418, 213, 23],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 418,
                "subject": "chemistry",
                "category": "Quantitative Chemistry",
                "name": "Dilution Formula",
                "latex": r"M_1 V_1 = M_2 V_2",
                "description": "When diluting a solution, the moles of solute remain constant. The initial concentration times initial volume equals the final concentration times final volume.",
                "grade_levels": ["ncea-2"],
                "keywords": ["dilution", "concentration", "volume", "solution", "molarity", "dilute"],
                "related_ids": [414, 416, 27, 25],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 419,
                "subject": "chemistry",
                "category": "Structure and Bonding",
                "name": "Electron Configuration Notation",
                "latex": r"\text{e.g. Na: } 1s^2\,2s^2\,2p^6\,3s^1 \quad \text{or} \quad 2,\!8,\!1",
                "description": "Electron configuration describes the arrangement of electrons in atomic orbitals. It can be written in full subshell notation or as a shorthand showing electrons per shell.",
                "grade_levels": ["ncea-2"],
                "keywords": ["electron configuration", "orbitals", "shells", "subshells", "arrangement", "energy levels"],
                "related_ids": [401, 420, 421, 245],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 420,
                "subject": "chemistry",
                "category": "Structure and Bonding",
                "name": "Lewis Dot Structures",
                "latex": r"\text{Lewis structure: show all valence electrons as dots/lines around atomic symbols}",
                "description": "Lewis dot structures represent valence electrons as dots or lines (bonding pairs) around element symbols. They show bonding pairs, lone pairs, and help predict molecular geometry.",
                "grade_levels": ["ncea-2"],
                "keywords": ["Lewis structure", "dot diagram", "valence electrons", "bonding pairs", "lone pairs", "covalent"],
                "related_ids": [419, 421, 246],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 421,
                "subject": "chemistry",
                "category": "Structure and Bonding",
                "name": "VSEPR Molecular Shapes",
                "latex": r"\text{Shapes: linear (2), trigonal planar (3), tetrahedral (4), bent, pyramidal}",
                "description": "The Valence Shell Electron Pair Repulsion theory predicts molecular geometry based on the number of electron pairs around a central atom. Electron pairs repel to maximise separation.",
                "grade_levels": ["ncea-2"],
                "keywords": ["VSEPR", "molecular shape", "geometry", "electron pairs", "tetrahedral", "trigonal planar"],
                "related_ids": [420, 419, 246],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 422,
                "subject": "chemistry",
                "category": "Thermochemistry",
                "name": "Heat Energy in Reactions (NCEA)",
                "latex": r"q = mc\Delta T",
                "description": "The heat energy absorbed or released in a reaction is calculated from the mass of solution (m), specific heat capacity of water (c = 4.18 J/g/K), and the temperature change (delta T).",
                "grade_levels": ["ncea-2"],
                "keywords": ["heat energy", "calorimetry", "specific heat capacity", "temperature change", "q=mcT", "enthalpy"],
                "related_ids": [423, 424, 230, 30],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 423,
                "subject": "chemistry",
                "category": "Thermochemistry",
                "name": "Enthalpy from Hess's Law (NCEA)",
                "latex": r"\Delta H_{\text{rxn}} = \sum \Delta H_f(\text{products}) - \sum \Delta H_f(\text{reactants})",
                "description": "Hess's law states that the total enthalpy change is independent of the pathway. The enthalpy of reaction can be calculated from standard enthalpies of formation of products minus reactants.",
                "grade_levels": ["ncea-2"],
                "keywords": ["Hess's law", "enthalpy", "formation", "energy cycle", "pathway", "thermochemistry"],
                "related_ids": [422, 424, 235, 236],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 424,
                "subject": "chemistry",
                "category": "Thermochemistry",
                "name": "Bond Enthalpy Calculation (NCEA)",
                "latex": r"\Delta H = \sum E(\text{bonds broken}) - \sum E(\text{bonds formed})",
                "description": "The enthalpy change of a reaction can be estimated by subtracting the total energy released when new bonds form from the total energy needed to break the bonds in the reactants.",
                "grade_levels": ["ncea-2"],
                "keywords": ["bond enthalpy", "bonds broken", "bonds formed", "energy", "estimation", "exothermic"],
                "related_ids": [422, 423, 223, 237],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 425,
                "subject": "chemistry",
                "category": "Thermochemistry",
                "name": "Enthalpy Level Diagrams",
                "latex": r"\text{Exothermic: products lower than reactants}\;;\; \text{Endothermic: products higher}",
                "description": "Enthalpy level diagrams show the relative energy of reactants and products. In exothermic reactions the products are at a lower energy level; in endothermic reactions the products are higher.",
                "grade_levels": ["ncea-2"],
                "keywords": ["enthalpy diagram", "energy level", "exothermic", "endothermic", "activation energy", "energy profile"],
                "related_ids": [422, 424, 224, 30],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 426,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Equilibrium Constant Kc (NCEA Level 2)",
                "latex": r"K_c = \frac{[C]^c [D]^d}{[A]^a [B]^b}",
                "description": "The equilibrium constant Kc expresses the ratio of product concentrations to reactant concentrations at equilibrium, each raised to the power of their stoichiometric coefficients.",
                "grade_levels": ["ncea-2"],
                "keywords": ["equilibrium constant", "Kc", "concentration", "ratio", "products", "reactants"],
                "related_ids": [427, 414, 239, 29],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 427,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Le Chatelier's Principle (NCEA)",
                "latex": r"\text{System at equilibrium shifts to oppose any change in concentration, temperature, or pressure}",
                "description": "Le Chatelier's principle states that when a system at equilibrium is disturbed, it will shift in the direction that partially counteracts the change, re-establishing a new equilibrium position.",
                "grade_levels": ["ncea-2"],
                "keywords": ["Le Chatelier", "equilibrium shift", "concentration", "temperature", "pressure", "dynamic equilibrium"],
                "related_ids": [426, 240, 239],
                "curriculum": ["ncea-2"],
            },
            {
                "id": 428,
                "subject": "chemistry",
                "category": "Redox",
                "name": "Standard Cell Potential (NCEA Level 2)",
                "latex": r"E_{\text{cell}} = E_{\text{cathode}} - E_{\text{anode}}",
                "description": "The cell potential of an electrochemical cell equals the standard reduction potential of the cathode minus the standard reduction potential of the anode. A positive value indicates a spontaneous reaction.",
                "grade_levels": ["ncea-2"],
                "keywords": ["cell potential", "cathode", "anode", "electrode potential", "electrochemistry", "redox"],
                "related_ids": [244, 245, 26],
                "curriculum": ["ncea-2"],
            },
            # ============================================================
            # NCEA Level 3 (Year 13) — IDs 429-440
            # ============================================================
            {
                "id": 429,
                "subject": "chemistry",
                "category": "Thermodynamics",
                "name": "Gibbs Free Energy (NCEA)",
                "latex": r"\Delta G = \Delta H - T\Delta S",
                "description": "Gibbs free energy determines whether a reaction is thermodynamically spontaneous. It combines enthalpy change (delta H) and entropy change (delta S) at a given absolute temperature (T in Kelvin).",
                "grade_levels": ["ncea-3"],
                "keywords": ["Gibbs free energy", "spontaneity", "enthalpy", "entropy", "temperature", "thermodynamics"],
                "related_ids": [430, 431, 255, 30],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 430,
                "subject": "chemistry",
                "category": "Thermodynamics",
                "name": "Entropy Change (NCEA)",
                "latex": r"\Delta S = \sum S^{\circ}(\text{products}) - \sum S^{\circ}(\text{reactants})",
                "description": "The entropy change of a reaction is the sum of standard molar entropies of products minus the sum for reactants. Entropy increases when there are more gas moles, more disorder, or higher temperature.",
                "grade_levels": ["ncea-3"],
                "keywords": ["entropy", "disorder", "standard entropy", "products", "reactants", "thermodynamics"],
                "related_ids": [429, 431, 254, 30],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 431,
                "subject": "chemistry",
                "category": "Thermodynamics",
                "name": "Spontaneity Conditions (NCEA)",
                "latex": r"\Delta G < 0 \;\text{spontaneous}\;;\; \Delta G > 0 \;\text{non-spontaneous}\;;\; \Delta G = 0 \;\text{equilibrium}",
                "description": "A reaction is spontaneous when delta G is negative. When delta H is negative and delta S is positive the reaction is always spontaneous; when both oppose, temperature determines feasibility.",
                "grade_levels": ["ncea-3"],
                "keywords": ["spontaneity", "Gibbs", "feasibility", "delta G", "thermodynamics", "equilibrium"],
                "related_ids": [429, 430, 256, 255],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 432,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Equilibrium Constant Kp (NCEA)",
                "latex": r"K_p = \frac{p_C^{\,c}\, p_D^{\,d}}{p_A^{\,a}\, p_B^{\,b}}",
                "description": "For gaseous equilibria, Kp is expressed in terms of partial pressures of products over reactants, each raised to the power of their stoichiometric coefficients in the balanced equation.",
                "grade_levels": ["ncea-3"],
                "keywords": ["Kp", "partial pressure", "equilibrium constant", "gaseous equilibrium", "stoichiometry", "pressure"],
                "related_ids": [426, 433, 257, 23],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 433,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Acid Dissociation Constant Ka (NCEA)",
                "latex": r"K_a = \frac{[H^+][A^-]}{[HA]}",
                "description": "Ka quantifies the strength of a weak acid by the equilibrium constant for its dissociation in water. A larger Ka means a stronger weak acid with greater dissociation at equilibrium.",
                "grade_levels": ["ncea-3"],
                "keywords": ["Ka", "acid dissociation", "weak acid", "equilibrium", "hydrogen ion", "dissociation"],
                "related_ids": [434, 436, 260, 26],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 434,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Base Dissociation Constant Kb (NCEA)",
                "latex": r"K_b = \frac{[BH^+][OH^-]}{[B]}",
                "description": "Kb quantifies the strength of a weak base by the equilibrium constant for its reaction with water. Ka and Kb of a conjugate acid-base pair are related by Ka times Kb equals Kw.",
                "grade_levels": ["ncea-3"],
                "keywords": ["Kb", "base dissociation", "weak base", "equilibrium", "hydroxide ion", "conjugate pair"],
                "related_ids": [433, 436, 261, 26],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 435,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Henderson-Hasselbalch Equation (NCEA)",
                "latex": r"pH = pK_a + \log_{10}\frac{[A^-]}{[HA]}",
                "description": "Calculates the pH of a buffer solution from the pKa of the weak acid and the ratio of conjugate base to acid concentration. A buffer resists pH changes when small amounts of acid or base are added.",
                "grade_levels": ["ncea-3"],
                "keywords": ["Henderson-Hasselbalch", "buffer", "pKa", "conjugate base", "weak acid", "buffer pH"],
                "related_ids": [433, 434, 264, 26],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 436,
                "subject": "chemistry",
                "category": "Equilibrium",
                "name": "Solubility Product Ksp (NCEA)",
                "latex": r"K_{sp} = [M^{a+}]^m [X^{b-}]^n \quad \text{for } M_mX_n(s) \rightleftharpoons mM^{a+}(aq) + nX^{b-}(aq)",
                "description": "The solubility product Ksp is the equilibrium constant for a sparingly soluble salt dissolving in water. If the ion product exceeds Ksp, precipitation occurs.",
                "grade_levels": ["ncea-3"],
                "keywords": ["solubility product", "Ksp", "sparingly soluble", "precipitation", "ionic equilibrium", "ion product"],
                "related_ids": [433, 434, 265, 25],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 437,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Rate Law (NCEA)",
                "latex": r"\text{rate} = k[A]^m[B]^n",
                "description": "The rate law expresses reaction rate as the product of a rate constant (k) and reactant concentrations raised to experimentally determined orders (m and n). Orders are not deduced from the balanced equation.",
                "grade_levels": ["ncea-3"],
                "keywords": ["rate law", "rate constant", "order", "concentration", "kinetics", "experimental"],
                "related_ids": [438, 439, 241, 29],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 438,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Arrhenius Equation (NCEA)",
                "latex": r"k = Ae^{-\frac{E_a}{RT}}",
                "description": "The Arrhenius equation relates the rate constant (k) to the activation energy (Ea), absolute temperature (T), gas constant (R = 8.314 J/mol/K), and the pre-exponential factor (A).",
                "grade_levels": ["ncea-3"],
                "keywords": ["Arrhenius", "activation energy", "rate constant", "temperature", "exponential", "frequency factor"],
                "related_ids": [437, 439, 266, 29],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 439,
                "subject": "chemistry",
                "category": "Kinetics",
                "name": "Activation Energy from Graph (NCEA)",
                "latex": r"\ln k = \ln A - \frac{E_a}{R} \cdot \frac{1}{T} \quad;\quad \text{gradient} = -\frac{E_a}{R}",
                "description": "Plotting ln k against 1/T gives a straight line whose gradient equals negative Ea/R. The activation energy is found by multiplying the magnitude of the gradient by R.",
                "grade_levels": ["ncea-3"],
                "keywords": ["Arrhenius plot", "ln k", "1/T", "gradient", "activation energy", "graphical determination"],
                "related_ids": [438, 437, 267, 266],
                "curriculum": ["ncea-3"],
            },
            {
                "id": 440,
                "subject": "chemistry",
                "category": "Organic Chemistry",
                "name": "Structural and Stereoisomerism (NCEA)",
                "latex": r"\text{Structural isomers: same molecular formula, different connectivity}" r"\;;\; \text{Stereoisomers: same connectivity, different spatial arrangement}",
                "description": "Structural isomers have the same molecular formula but differ in how atoms are connected. Stereoisomers (including optical isomers with a chiral carbon) have the same connectivity but different 3D arrangements.",
                "grade_levels": ["ncea-3"],
                "keywords": ["structural isomers", "stereoisomers", "optical isomers", "chiral centre", "molecular formula", "organic chemistry"],
                "related_ids": [411, 246, 217, 24],
                "curriculum": ["ncea-3"],
            },
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM formulas WHERE id >= 401 AND id <= 440")
